const fs=require('fs'),path=require('path'),sharp=require('C:/Users/Mike/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
(async()=>{const m=require('./manifest.json'),v=require('./verification.json');let missing=[],badDimensions=[],opaqueBorders=[],zeroContent=[];
for(const [id,f] of Object.entries(m.frames)){const p=path.join(__dirname,f.file);if(!fs.existsSync(p)){missing.push(p);continue;}const {data,info}=await sharp(p).ensureAlpha().raw().toBuffer({resolveWithObject:true});if(info.width!==f.size[0]||info.height!==f.size[1])badDimensions.push(id);let content=0,border=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const a=data[(y*info.width+x)*4+3];if(a)content++;if(a&&(x===0||y===0||x===info.width-1||y===info.height-1))border++;}if(!content)zeroContent.push(id);if(border)opaqueBorders.push(id);}
for(const [id,s] of Object.entries(m.sequences))for(const f of s.frames)if(!m.frames[f])missing.push(id+':'+f);
const hud=await sharp(path.join(__dirname,m.hud.overlay)).ensureAlpha().raw().toBuffer({resolveWithObject:true});let centerAlpha=0;for(let y=170;y<600;y++)for(let x=80;x<430;x++)if(hud.data[(y*512+x)*4+3])centerAlpha++;
const html=fs.readFileSync(path.join(__dirname,'preview.html'),'utf8').split('<script')[0];for(const match of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const ref=match[1];if(!ref.includes(':')&&!fs.existsSync(path.resolve(__dirname,ref)))missing.push(ref);}
for(const body of m.existingLocomotion.bodyTypes)for(const name of ['aim_1',...m.existingLocomotion.run.flatMap(a=>Array.from({length:4},(_,i)=>a+'_'+i))]){const p=path.resolve(__dirname,m.existingLocomotion.root,body+'_'+name+'.png');if(!fs.existsSync(p))missing.push(p);}
v.validation={checkedAt:'2026-10-04',missing,badDimensions,opaqueBorders,zeroContent,hudClearCenter:{rectangle:[80,170,350,430],nonzeroAlphaPixels:centerAlpha},framesChecked:Object.keys(m.frames).length,sequencesChecked:Object.keys(m.sequences).length};fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(v,null,2)+'\n');console.log(v.validation);if(missing.length||badDimensions.length||opaqueBorders.length||zeroContent.length||centerAlpha)process.exitCode=1;
})();
