from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];O=R/'_shots/finale_structure_1003j'
data=json.loads((O/'report.json').read_text())
forms=''.join('<figure><img loading="lazy" src="mimic-%d-%s.png" alt="%s"><figcaption>%s <span>%s HP on Furious</span></figcaption></figure>'%(i+1,d['id'],d['id'],d['id'].title(),format(d['hp'],',')) for i,d in enumerate(data['forms']))
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Three encounters · Bullets of Fury</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080b16;color:#edf3ff;font:16px/1.55 system-ui}main{max-width:1280px;margin:auto;padding:30px 24px 80px}h1{font-size:clamp(30px,4vw,52px);line-height:1.08}h2{margin-top:42px}p{color:#b9c5dd;max-width:950px}a{color:#a8dbff}.tag{font-size:12px;letter-spacing:2px;color:#f391a3}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.forms{grid-template-columns:repeat(4,1fr)}figure{margin:0;border:1px solid #334059;background:#111829}img{width:100%;display:block;image-rendering:pixelated}figcaption{padding:13px;font-weight:600}figcaption span{display:block;font-size:13px;color:#a8bbd5;font-weight:400}.buttons{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0}button,select{background:#291928;border:1px solid #a56980;color:#fff;border-radius:5px;padding:12px;font:inherit;cursor:pointer}button:hover{background:#49304a}iframe{width:100%;height:850px;border:1px solid #334059}.two{display:grid;grid-template-columns:1fr 1fr;gap:20px}small{color:#adbbce}#status{min-height:24px}@media(max-width:760px){.grid,.forms,.two{grid-template-columns:1fr 1fr}main{padding:20px 12px}}@media(max-width:470px){.grid,.two{grid-template-columns:1fr}}</style>
<main><div class="tag">BULLETS OF FURY · FINALE CORRECTION</div><h1>Three encounters.<br>Dracula owns the transformations.</h1>
<p>The normal drone arrives and mutates. Defeat the mutated drone, then the ghost, then face Dracula and his eight forms. Each transformation remembers its remaining health and broken weapons.</p>
<p><a href="../../index.html?build=finale-1003j" target="_blank">Play updated build</a> · <a href="report.json">Encounter verification</a></p>
<div class="grid"><figure><img src="03-mutated-drone.png" alt="Mutated drone with articulated claws"><figcaption>1. Mutated drone<span>Normal drone arrival → visible mutation → first fight</span></figcaption></figure><figure><img src="04-ghost.png" alt="Ghost in the Code"><figcaption>2. Ghost in the Code<span>Separate life and music, teleporting claw attacks</span></figcaption></figure><figure><img src="06-dracula-fight.png" alt="Dracula with separate arms"><figcaption>3. Dracula / Vile Colossus<span>Eight-life introduction, all eight transformations</span></figcaption></figure></div>
<h2>Try the corrected encounters</h2><p>The full finale starts with the normal drone. The other buttons provide quick access to the individual fights. Use your existing game controls.</p>
<div class="buttons"><select id="difficulty" aria-label="Difficulty"><option value="normal">Normal</option><option value="hard">Hard</option><option value="furious" selected>Furious</option></select><button data-fight="full">Full finale</button><button data-fight="ghost">Ghost fight</button><button data-fight="dracula">Dracula fight</button><button data-fight="rebels">Rebel encounter</button></div><p id="status" role="status"></p><iframe id="arena" title="Playable corrected encounter" hidden></iframe>
<h2>Eight forms, eight persistent lives</h2><p>One health gauge fills eight times during Dracula’s introduction. During combat it shows the current form’s actual remaining HP and color. Dracula returns between forms; changing shape never heals a damaged life.</p>
<div class="grid forms">FORMS</div>
<h2>Stage 6 keeps flying</h2><div class="two"><figure><img src="radio-moving-yuri.png" alt="Cole dialogue over live flying formation"><figcaption>Live protected dialogue<span>Steering, scrolling and animation continue. Dialogue stays timed, unskippable and protected from combat.</span></figcaption></figure><figure><img src="rebels-damaged-pitch-2.png" alt="All five whole rebel ships during a damaged pitch frame"><figcaption>Complete rebel ships<span>Damage flashes retain the entire ship. Starting, formation and last-stand shields are removed.</span></figcaption></figure></div>
<p><small>Verified in native Chromium. These are controlled encounter and dialogue checks; final difficulty balance still needs a human playthrough.</small></p></main>
<script>
const frame=document.querySelector('#arena'),status=document.querySelector('#status');let timer;
document.querySelectorAll('[data-fight]').forEach(btn=>btn.onclick=()=>{
 clearInterval(timer);const fight=btn.dataset.fight,diff=document.querySelector('#difficulty').value;status.textContent='Loading encounter…';frame.hidden=false;
 frame.onload=()=>{let tries=0;timer=setInterval(()=>{const w=frame.contentWindow;if(++tries>1200){clearInterval(timer);status.textContent='Loading took too long. Click an encounter to retry.';return;}if(!w.BOFDEBUG||typeof w.spawnBoss!=='function')return;
 try{w.eval('ht27Stop();debugFight=null;coopOn=false;diffKey='+JSON.stringify(diff)+';DIFF=DIFFS[diffKey];run.pilot="yuri";run.mode="campaign";run.lives=9;beginStage('+(fight==='rebels'?6:8)+');setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;special=null;s6Opening=null;s6Wing=null;fb2Talk=null;stagePlan=[];spawnClock=9999;waveIdx=999;enemies=[];eBullets=[];pBullets=[];powerups=[];boss=null;bossActive=false;subBoss=null;subBossActive=false;stageTimer=0;player.x=worldWidth()/2;player.y=VH-110;camX=player.x-VW/2;player.invuln=3;spawnBoss('+JSON.stringify(fight==='rebels'?'rebelsquad':'vileexistence')+');boss._be=null;');
 if(fight==='ghost'||fight==='dracula')w.eval('j3Encounter(boss,'+(fight==='ghost'?1:2)+');bossPhaseMusic(8,'+(fight==='ghost'?2:3)+');');
 w.eval('Audio.init();Audio.resume();');clearInterval(timer);status.textContent='Encounter ready.';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});
 }catch(e){clearInterval(timer);status.textContent='Encounter could not start. Click to retry.';console.error(e);}},100);};
 frame.src='../../index.html?build=finale-1003j-review';
});
</script></html>'''
(O/'review.html').write_text(page.replace('FORMS',forms),encoding='utf-8')
print(O/'review.html')
