from pathlib import Path
import html
W=Path(__file__).resolve().parent
R=W.parent if W.name=='_BUILD_SOURCE' else Path(r'C:/Users/Mike/Desktop/Github Coding/BulletsOfFury')
O=R/'_shots/hammer_knight_1005'
cards=[('Hammer armor','hammer-armor.png'),('Sideways warning','hammer-left-warning.png'),('Sideways strike','hammer-left-strike.png'),('Healing target','hammer-heal-target.png'),('Healing interrupted','hammer-heal-stopped.png'),('Thrown red Hammer','hammer-thrown-return.png'),('Eight-percent emergency','hammer-emergency.png'),('Actual HAMR8 entry','hammer-password.png'),('Downward / rising slash','leapSlash.gif'),('Shield smite','shieldSmite.gif'),('Charged code fireballs','shieldCode.gif'),('Warned Armageddon','armageddon.gif'),('Stage 5 bottom columns','regular-bottom-lightning.png'),('Stage 5 FOV super','regular-super-fov.png'),('HAMMER bottom columns','hammer-bottom-lightning.png'),('HAMMER FOV super','hammer-super-fov.png'),('HAMA bottom columns','hama-bottom-lightning.png'),('HAMA FOV super','hama-super-fov.png')]
items=''.join('<figure><img loading="lazy" src="'+html.escape(f)+'"><figcaption>'+html.escape(n)+'</figcaption></figure>' for n,f in cards)
O.mkdir(parents=True,exist_ok=True)
(O/'review.html').write_text('''<!doctype html><html><meta charset="utf-8"><title>Code Hammer and knight — native gameplay review</title><style>body{background:#070b0e;color:#e6edf2;font:16px system-ui;margin:28px auto;max-width:1250px;padding:0 20px}h1{font-size:28px}a{color:#8ce5ff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px}figure{margin:0;background:#141c24;border:1px solid #344957;padding:9px}img{width:100%;height:auto;image-rendering:pixelated}figcaption{padding:10px 2px;font-weight:600}p{line-height:1.5;max-width:900px}code{color:#ffd2ad}</style><h1>Code Hammer + knight extension</h1><p>Native game-canvas captures from the local October 5 build. Silent, protected test fixtures verify attacks and rendering; these are not unassisted Furious clears or proof of final balance.</p><p><a href="../../index.html">Play the local build</a> · <a href="../../docs/qa/hammer_knight_1005.json">Native verification report</a>. In Passwords, enter <code>HAMR8</code> for the new copied Hammer or <code>KNIGHT</code> for the sword/shield extension. Choose your difficulty and pilot normally.</p><div class="grid">'''+items+'</div></html>',encoding='utf-8')
print(O/'review.html')
