"""Import Mike's remix and register generated dance sheets without changing their RGBA."""
from pathlib import Path
from PIL import Image
import hashlib,json,shutil,subprocess,wave
import numpy as np
import imageio_ffmpeg

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets/game/hammer_time_0927';OUT.mkdir(parents=True,exist_ok=True)
GEN=Path('C:/Users/Mdogg/.codex/generated_images/01a0e3c8-265d-7731-8ffe-ee42ebb5ba3c')
SOURCES={'boss':('exec-f999edbd-15dc-418d-9033-237bb8f05130.png',4,4),
 'dancers':('exec-6a2bc109-56aa-490f-b026-885e2ee6bdc9.png',4,2),
 'shield':('exec-6b4d8757-dc9b-44bf-af2c-d4edbeb4dc6c.png',4,2),
 'wall':('exec-620cf05d-2519-4f54-aa24-f8f6a32fae8f.png',1,8)}
meta={'sheets':{}}
for key,(filename,cols,rows) in SOURCES.items():
 dest=OUT/(key+'.png')
 if (GEN/filename).exists():shutil.copyfile(GEN/filename,dest)
 im=Image.open(dest);assert im.mode=='RGBA'
 ar=np.array(im);frames=[]
 for row in range(rows):
  for col in range(cols):
   x0=round(col*im.width/cols);x1=round((col+1)*im.width/cols)
   y0=round(row*im.height/rows);y1=round((row+1)*im.height/rows)
   cell=ar[y0:y1,x0:x1];hot=(cell[:,:,3]>180)&(cell[:,:,:3].max(axis=2)>60)
   yy,xx=np.where(hot);assert len(yy)>50
   # Anchor humanoids by the central torso, not a hammer or outstretched hand.
   # Shared cell scale prevents differently sized twirl silhouettes from pulsing.
   ax=(x1-x0)/2;ay=float(np.quantile(yy,.985))
   if key=='boss':
    core=(cell[:,:,2]>cell[:,:,0]*1.3)&(cell[:,:,1]>100)&(cell[:,:,3]>180)
    core[:int((y1-y0)*.20)]=False;core[int((y1-y0)*.62):]=False
    core[:,:int((x1-x0)*.3)]=False;core[:,int((x1-x0)*.73):]=False
    cy,cx=np.where(core)
    if len(cx):ax=float(np.median(cx))
   if key=='wall':
    # Horizontal rails, not the diffuse alpha glow, determine each row's anchor.
    bright=(cell[:,:,3]>160)&(cell[:,:,1]>170)&(cell[:,:,2]>210)
    ys=np.where(bright.sum(axis=1)>im.width*.35)[0]
    assert len(ys)>2
    mid=(ys.min()+ys.max())*.5
    y0=round(y0+mid-46);y1=y0+92;x0=24;x1=im.width-24;ax=(x1-x0)*.5;ay=46
   frames.append([x0,y0,x1-x0,y1-y0,round(ax,2),round(ay,2)])
 meta['sheets'][key]={'path':dest.relative_to(ROOT).as_posix(),'source':filename,'frames':frames,'cellHeight':im.height/rows}

source=Path('C:/Users/Mdogg/Desktop/mchammer.wav')
with wave.open(str(source),'rb') as w:
 sr=w.getframerate();n=w.getnframes();channels=w.getnchannels();assert w.getsampwidth()==2
 samples=np.frombuffer(w.readframes(n),dtype='<i2').astype(np.float32).reshape(-1,channels)/32768
mono=samples.mean(axis=1);hop=sr//25;trim=mono[:len(mono)//hop*hop].reshape(-1,hop)
env=np.sqrt(np.mean(trim*trim,axis=1));env=np.clip(env/max(.001,float(np.quantile(env,.95))),0,1)
onset=np.maximum(0,np.diff(env,prepend=env[0]));ac=np.correlate(onset,onset,'full')[len(onset)-1:]
lags=np.arange(9,19);lag=int(lags[np.argmax(ac[lags])]);bpm=1500/lag
music=ROOT/'assets/game/shared/audio/music/HammerTime.mp3'
subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),'-v','error','-y','-i',str(source),'-map_metadata','-1','-codec:a','libmp3lame','-b:a','192k',str(music)],check=True)
meta['audio']={'path':music.relative_to(ROOT).as_posix(),'seconds':n/sr,'source':str(source),'sourceSHA256':hashlib.sha256(source.read_bytes()).hexdigest(),'envelopeFPS':25,'envelope':[round(float(v),3) for v in env], 'bpm':round(bpm,3),'breakStart':16,'breakEnd':24}
(ROOT/'assets/hammer_time_art_0927.js').write_text('/* Generated by build_hammer_time_0927.py. */\nconst HAMMER_TIME_ART='+json.dumps(meta,separators=(',',':'))+';\n',encoding='utf-8',newline='\n')
taxonomy=ROOT/'assets/data/ART_TAXONOMY.json';data=json.loads(taxonomy.read_text(encoding='utf-8'))
for key in SOURCES:data['ht27_'+key]={'role':'effect' if key in ('shield','wall') else 'boss_animation','sheet':None,'note':'Built-in image generation; HAMMER secret encounter only. Original RGBA preserved, measured cells/anchors in hammer_time_art_0927.js. Owning build _BUILD_SOURCE/build_hammer_time_0927.py; prompts docs/hammer_time_prompts_0927.json.'}
taxonomy.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
print(json.dumps({'sheets':{k:len(v['frames']) for k,v in meta['sheets'].items()},'audioSeconds':n/sr,'estimatedBPM':bpm,'break':[16,24]}))
