from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'_shots/stage3_combat_1004k'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stage 3 combat · Bullets of Fury</title>
<style>*{box-sizing:border-box}body{margin:0;background:#091624;color:#e8f6ff;font:16px/1.5 system-ui}main{max-width:1160px;margin:auto;padding:32px 20px}h1{font-size:44px;line-height:1.1}p{max-width:900px;color:#bacfe0}button,select{font:inherit;padding:12px;background:#193749;color:#fff;border:1px solid #4d9bad;border-radius:4px;cursor:pointer}a{color:#8bdfff}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}iframe{width:100%;height:850px;border:1px solid #477b90}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}img{width:100%;image-rendering:pixelated}figure{margin:0;background:#10273a}figcaption{padding:12px}#status{min-height:28px}small{color:#9fbacc}@media(max-width:700px){.grid{grid-template-columns:1fr}h1{font-size:32px}}</style>
<main><h1>Frost Cruiser and Rime Wall</h1><p>The Cruiser adds a warned, committed charge. Rime Wall keeps its existing attacks and adds deployable orbiting turrets and paired missile volleys. Lasers track while charging, then lock before release. Gun pellets cannot be shot down; fire/ice balls and missiles can.</p>
<div class="controls"><select id="pilot" aria-label="Pilot">'''
for k in ['yuri','cole','decker','axel','falva','lizzie','freezer','juggernaut','maverick']:page+=f'<option value="{k}">{k.title()}</option>'
page+='''</select><button data-kind="frostcruiser">Miniboss · Furious</button><button data-kind="cryospear">Boss · Furious</button><button data-kind="stage">Full Stage 3 · Furious</button><label><input type="checkbox" id="safe"> Practice invulnerability</label></div>
<p id="status" role="status">Choose a fight. Practice saves use a separate namespace.</p><iframe id="arena" title="Playable Stage 3 practice" hidden allow="autoplay"></iframe>
<p><a href="../../index.html?build=stage3-combat-1004k">Open the updated game</a> · Stage 3 password: <strong>DAM5</strong>.</p>
<h2>Verified in the game</h2><div class="grid"><figure><img src="rime-orbit-stream.png" alt="Rime Wall deploys and aims its orbital guns"><figcaption>Real moving weapon modules, with matching hitboxes.</figcaption></figure><figure><img src="rime-laser-release.png" alt="Rime Wall fires charged laser streams"><figcaption>Charged beams keep their promised lanes.</figcaption></figure><figure><img src="cruiser-charge-warning.png" alt="Cruiser prepares its charge with a warning lane"><figcaption>The charge warning precedes movement.</figcaption></figure><figure><img src="ice-interception.png" alt="An intercepted ice ball shatters"><figcaption>Authored elemental impact reels and debris.</figcaption></figure></div><h2>Spread Fire muzzle alignment</h2><img src="spread-all-pilots.png" alt="Spread Fire attached to all nine pilot noses"><p><small>Recording reviewed across its timeline at 12-second intervals, then Stage 3 examined at 2-second intervals. Combat HP and elemental transformations retained.</small></p></main>
<script>
const frame=document.querySelector('#arena'),status=document.querySelector('#status');
document.querySelectorAll('button').forEach(button=>button.onclick=()=>{const kind=button.dataset.kind,pilot=document.querySelector('#pilot').value,safe=document.querySelector('#safe').checked;frame.hidden=false;status.textContent='Loading the updated fight…';
frame.onload=()=>{const w=frame.contentWindow,timer=setInterval(()=>{try{if(!w.__bofFrames||!w.eval('typeof er26Set==="function"&&typeof s3kOwns==="function"'))return;
w.eval('map4hPreviewStorage();ht27Stop();debugFight=null;coopOn=false;pilotIndex=PILOTS.findIndex(p=>p.key==='+JSON.stringify(pilot)+');diffKey="furious";DIFF=DIFFS.furious;startRun(3);beginStage(3);setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;thaw=null;run.pilot='+JSON.stringify(pilot)+';run.mode="campaign";');
if(kind!=='stage')w.eval('stagePlan=[];spawnClock=9999;waveIdx=999;enemies=[];eBullets=[];pBullets=[];powerups=[];groundTargetingReset();tb28Reset();polishLanes=[];boss=null;bossActive=false;subBoss=null;subBossActive=false;subBossDone=true;subBossTriggered=true;stageTimer=0;'+(kind==='frostcruiser'?'spawnSubBoss__inner("frostcruiser");const B=subBoss;':'spawnBoss("cryospear");const B=boss;')+'B._be=null;B._scene=null;B.enter=false;B._noHit=false;B.x=worldWidth()/2;B.y=B._er26.home;B._drawY=B.y;B._s3Nuclear={mode:"ice",introDone:true};B._er26.form="ice";B._er26.nuclearRevealed=true;er26Set(B,"recover");');
w.eval('player.x=worldWidth()/2;player.y=VH-110;player.invuln='+(safe?'1e9':'2')+';Audio.init();Audio.resume();Audio.startMusic('+(kind==='stage'?'"stage3"':kind==='frostcruiser'?'"miniboss3"':'"boss3"')+');');clearInterval(timer);status.textContent='Furious encounter ready.';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});
}catch(e){clearInterval(timer);status.textContent='Could not start the encounter. Click to retry.';console.error(e);}},100);};frame.src='../../index.html?build=stage3-combat-1004k-practice';});
</script></html>'''
(O/'review.html').write_text(page,encoding='utf-8');print(O/'review.html')
