"""Build the director review from verified native capture artifacts."""
import json
from pathlib import Path
OUT=Path('_shots/director_0927')
log=(OUT/'suite-final.log').read_text(encoding='utf-8')
passed=sum(line.lstrip().startswith('ok  ') for line in log.splitlines())
assert 'BUILD OK, 0 ERRORS' in log
specs=[
 ('tempest-hard','Hard · Silver Eclipse','The reference pace: separate engine and laser modules, marked bombs and missile launches.','tempest-hard-video-1.png','24 seconds · captured game SFX'),
 ('tempest-furious','Furious · Crimson Eclipse','Black armor, red reactors, faster lateral passes, tighter charge/recovery timing and paired missile lanes. One bomb lane stays open. Destroying engines slows it; shooting a charging cannon interrupts the beam.','tempest-furious-12.png','30 seconds · captured game SFX'),
 ('module-cascades','Modular destruction','Large broken parts trigger eighteen staggered blasts from the game’s explosion library. Cascades follow the moving hardpoint, with sparks, smoke and short impact shakes.','module-cascades-video-0.png','22 seconds · four staged module breaks'),
 ('player-weapons','Primary weapons','The real weapon loop cycles through all nine weapon slots. Gun flares, missile ignition and elemental effects now have their own shapes.','player-weapons-video-0.png','30 seconds · captured game SFX'),
 ('player-specials','Pilot weapons and charge effects','Maverick charge and helix tap, Falva roller, Decker shotgun, Freezer breath, Yuri lightning and ordinary fire.','special-decker-0.png','23 seconds · game SFX, capture headroom applied'),
 ('muzzle-reels','16 families · 96 frames','Six generated frames per family. Ballistic, elemental, energy and specialist sheets use measured ignition anchors.','muzzles-2.png','8 seconds · silent animation gallery'),
 ('pilot-thrusters','All nine pilots','Six heat-pulse frames animate the exhaust already painted into each ship. Hull pixels and transparency outside the flame mask are unchanged.','pilots-2.png','8 seconds · silent animation gallery')]
cards=''.join(f'<article><h2>{title}</h2><p>{desc}</p><video controls playsinline preload="metadata" poster="{poster}" src="{key}.webm"></video><div class="caption">{caption}</div></article>' for key,title,desc,poster,caption in specs)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fury Fighters · Director upgrades</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#080f19;color:#e8f1fb;font:16px/1.55 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:32px 24px 70px}.eyebrow{color:#8eddff;font-size:12px;font-weight:800;letter-spacing:.17em}h1{font-size:clamp(30px,4vw,48px);line-height:1.12;margin:14px 0}h2{font-size:23px;line-height:1.2;margin:0 0 12px}p{max-width:94ch}a{color:#8cdbff}nav{display:flex;gap:22px;flex-wrap:wrap;margin:24px 0}.notice{border-left:4px solid #e9b56a;background:#182535;padding:14px 20px;margin-bottom:26px}.stats{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.stats span{background:#11283c;border:1px solid #2c4e67;padding:9px 14px;border-radius:6px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{padding:20px;background:#111e2d;border:1px solid #2a4056;border-radius:12px}article p{color:#bfd1e1;min-height:98px}video{width:100%;max-height:570px;display:block;background:#000}.caption{font-size:13px;color:#94b0c7;margin-top:12px}.details{margin-top:28px;padding:20px;border:1px solid #2a4056;border-radius:10px;background:#111e2d}ul{padding-left:23px}@media(max-width:760px){main{padding:24px 14px}.grid{grid-template-columns:1fr}article p{min-height:0}}</style>
<main><div class="eyebrow">BULLETS OF FURY · SEPTEMBER 27</div><h1>Weapons with their own impact</h1><p>New muzzle animation families, chained modular explosions, red-and-black Furious Tempest, and animated native pilot thrusters. Watch Hard beside Furious first, then inspect the weapon and exhaust reels.</p>
<nav><a href="../../index.html">Open the game</a><a href="../../bossmode.html">Boss practice</a><a href="../../docs/DIRECTOR_UPGRADE_0927.md">Development notes</a></nav>
<div class="stats"><span>16 effect families</span><span>96 generated frames</span><span>9 animated pilots</span><span>'''+f'{passed:,} assertions · 0 failures'+'''</span></div>
<div class="notice"><strong>Native Chromium inspection.</strong> These are controlled encounters and weapon demonstrations, with immunity and staged module damage where needed. They verify rendering, effects, attack states and sound; they are not campaign wins or a certification of final difficulty balance. Music is muted for SFX inspection.</div>
<div class="grid">'''+cards+'''</div><div class="details"><h2>Checks and counterplay</h2><ul><li>Normal, Hard and Furious Tempest each exercised for 35 simulated seconds. All projectiles remain finite; camera zoom stays at 1.</li><li>Furious covers about four times Hard’s lateral distance in the same sample. Bombs retain a marked escape lane, and the cannon charge remains longer than one second.</li><li>A large broken module schedules eighteen blasts. Duplicate hits cannot restart it; simultaneous queues are bounded and clear on a stage change.</li><li>All nine pilot hulls retain their original alpha and every pixel outside the authored exhaust mask. Idle, bank and perspective flight poses use the pulse animation; rapid roll frames retain their authored poses.</li><li>All generated reels and the special-weapon routes are inspected through the actual game renderer. Browser page and console error lists are empty.</li></ul><p><a href="report.json">Native effects and encounter report</a> · <a href="specials.json">Special-weapon report</a> · <a href="videos.json">Recording measurements</a> · <a href="suite-final.log">Full test output</a></p></div></main></html>'''
(OUT/'review.html').write_text(html,encoding='utf-8')
print(f'Review built: {passed} assertions, {len(specs)} clips')
