"""Import authored pixels and build the owning lazy registry; no painted sprites."""
from pathlib import Path
from PIL import Image
import json, argparse, shutil, hashlib

def build(root, art_root, radar, jets):
    out=root/'assets/game/mission_repair_0929';out.mkdir(parents=True,exist_ok=True)
    src=root/'_ART_SOURCES/mission_repair_0929';src.mkdir(parents=True,exist_ok=True)
    registry={}
    for name,path in [('radar',radar),('bluejets',jets)]:
        shutil.copy2(path,src/(name+'.png'))
        im=Image.open(path).convert('RGBA');count=4 if name=='radar' else 3
        if name=='radar':
            # Generated static occupies the central horizontal strip; crop its black padding.
            bounds=im.convert('RGB').getbbox();top,bottom=bounds[1],bounds[3]
            size=(160,48);frames=[]
        else:top,bottom=0,im.height;size=(128,128);frames=[]
        atlas=Image.new('RGBA',(size[0]*count,size[1]))
        for i in range(count):
            cell=im.crop((round(i*im.width/count),top,round((i+1)*im.width/count),bottom))
            if name=='radar':cell=cell.resize(size,Image.Resampling.NEAREST)
            else:
                cell=cell.crop(cell.getbbox());scale=110/max(cell.size)
                cell=cell.resize(tuple(round(v*scale) for v in cell.size),Image.Resampling.NEAREST)
                pad=Image.new('RGBA',size);pad.alpha_composite(cell,((size[0]-cell.width)//2,(size[1]-cell.height)//2));cell=pad
            atlas.alpha_composite(cell,(i*size[0],0));frames.append([i*size[0],0,*size])
        atlas.save(out/(name+'.png'))
        registry[name]={'key':'mission29_'+name,'path':'assets/game/shared/combat/mission_repair_0929/'+name+'.png','frames':frames,'fps':18 if name=='radar' else 1}
    pack=art_root/'assets/game/weapon_animation_0928'
    families=json.loads((pack/'manifest.json').read_text())['families']
    for name,d in families.items():
        if not name.startswith('beam_'):continue
        # Compute a shared ink box so alpha padding cannot shorten/shift a beam per frame.
        boxes=[Image.open(pack/f['file']).getbbox() for f in d['frames']]
        ink=[min(b[0] for b in boxes),min(b[1] for b in boxes),max(b[2] for b in boxes),max(b[3] for b in boxes)]
        ink=[ink[0],ink[1],ink[2]-ink[0],ink[3]-ink[1]]
        registry[name]={'key':'mission29_'+name,'path':'assets/game/shared/player_weapons/weapon_animation_0928/'+d['atlas'],
            'frames':[f['rect'] for f in d['frames']],'fps':d['fps'],'ink':ink,'anchor':d['anchor']}
        with Image.open(pack/d['atlas']) as a:
            for x,y,w,h in registry[name]['frames']:assert x+w<=a.width and y+h<=a.height
    (out/'manifest.json').write_text(json.dumps(registry,indent=2)+'\n')
    (src/'provenance.json').write_text(json.dumps({'date':'2026-09-29','tool':'built-in image_gen','sourceFiles':[str(radar),str(jets)],
        'references':['cinematic_campaign/war_origin_0924/radar_bezel_native.png','stage6_enemy_attacks/storm_dart/01.png'],
        'imports':'Equal cells cropped, nearest-neighbor resized, padded, packed. Beam cells from September 28 owning manifest.'},indent=2)+'\n')
    (root/'assets/mission_art_0929.js').write_text('/* Generated by build_mission_art_0929.py */\nconst MISSION29_ART='+json.dumps(registry,separators=(',',':'))+';\n',encoding='utf-8',newline='\n')
    print(f'{len(registry)} families, {sum(len(a["frames"]) for a in registry.values())} frames')

if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('--root',type=Path,required=True);a.add_argument('--art-root',type=Path,required=True)
    a.add_argument('--radar',type=Path,required=True);a.add_argument('--jets',type=Path,required=True);build(**vars(a.parse_args()))
