from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'_shots/rebel_gang_1004'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gang Mode · Bullets of Fury</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080e1b;color:#edf3ff;font:16px/1.5 system-ui}main{max-width:1250px;margin:auto;padding:30px 24px 70px}h1{font-size:clamp(36px,5vw,60px);line-height:1.1;margin:10px 0}h2{margin-top:40px}p{max-width:900px;color:#b9c9df}.tag{font-size:12px;letter-spacing:2px;color:#76e9ed}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.two{grid-template-columns:repeat(2,1fr)}figure{margin:0;background:#111c30;border:1px solid #304965}img{width:100%;display:block;image-rendering:pixelated}figcaption{padding:14px}figcaption span{display:block;font-size:13px;color:#adbed7}a{color:#80eaff}.buttons{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}button,select{padding:12px;border:1px solid #4e7c97;background:#19334b;color:#fff;font:inherit;cursor:pointer;border-radius:5px}button:hover{background:#295673}iframe{width:100%;height:900px;border:1px solid #4e7c97}#status{min-height:24px}table{border-collapse:collapse;width:100%;max-width:950px}td,th{text-align:left;padding:12px;border-bottom:1px solid #304965}small{color:#adbed7}@media(max-width:750px){.grid{grid-template-columns:1fr 1fr}main{padding:24px 12px}}@media(max-width:490px){.grid{grid-template-columns:1fr}}</style>
<main><div class="tag">BULLETS OF FURY · REBEL ENCOUNTER</div><h1>Gang Mode Initiate!</h1><p>Five personal weapons. Three wounded pilots trigger the squad's overcharge. Decker brings the team together under an experimental cloak—until Kaia finds the signal.</p>
<div class="buttons"><select id="difficulty" aria-label="Difficulty"><option value="normal">Normal</option><option value="hard">Hard</option><option value="furious" selected>Furious</option></select><select id="pilot" aria-label="Pilot"><option value="yuri">Yuri</option><option value="decker">Decker</option><option value="cole">Cole</option><option value="falva">Falva</option></select><button data-fight="intro">Full rebel encounter</button><button data-fight="fight">Fight now</button><button data-fight="gang">Gang Mode preview</button><button data-fight="scene">Decker scene preview</button></div><p id="status" role="status">Use your existing game controls. Preview buttons jump to the selected encounter beat.</p><iframe id="arena" title="Playable Rebel encounter" hidden></iframe>
<table><tr><th>Pilot</th><th>Personal weapon</th><th>Gang upgrade</th></tr><tr><td>Voss</td><td>Pink Fusion cannon · original asterisk tell</td><td>Shootable missile salvos</td></tr><tr><td>Nyx</td><td>Cloaked three-shot ambush</td><td>Sustained stealth between attacks</td></tr><tr><td>Rook</td><td>Visible twin heavy machine guns</td><td>Turbo movement and faster bursts</td></tr><tr><td>Kaia</td><td>Falva rollerball with splitting satellites</td><td>Destructible Axel-style helper orb</td></tr><tr><td>Jace</td><td>Cloaked strafing attack</td><td>Turbo strafe</td></tr></table>
<h2>Personal weapons</h2><div class="grid"><figure><img src="fusion-charge.png" alt="Voss glows pink while Fusion cannon charges"><figcaption>Voss · Fusion charge<span>Whole-ship pink glow and the original asterisk warning.</span></figcaption></figure><figure><img src="heavy-release.png" alt="Rook fires two heavy gun attachments"><figcaption>Rook · Heavy guns<span>Separate barrel animation and muzzle flashes on an intact ship.</span></figcaption></figure><figure><img src="roller-release.png" alt="Kaia releases Falva's pink rollerball"><figcaption>Kaia · Prism roller<span>Bouncing core with two smaller splitting projectiles.</span></figcaption></figure></div>
<h2>Three of five at half health</h2><div class="grid two"><figure><img src="gang-mode.png" alt="Five rebels charge different colors"><figcaption>Gang Mode<span>No health refill or rebel shields. Each ship keeps its remaining HP.</span></figcaption></figure><figure><img src="effect-wave.png" alt="Decker emits a cyan wave over the friendly formation"><figcaption>Experimental shield wave<span>The whole team forms up while the world keeps scrolling.</span></figcaption></figure></div>
<h2>The counter-scan</h2><div class="grid two"><figure><img src="scene-4.png" alt="Kaia searches for the cloaked team with multiple original Retinas"><figcaption>“Leave it to the ladies…”<span>Original Retina graphics search, converge and expose the formation.</span></figcaption></figure><figure><img src="effect-reveal.png" alt="Cyan and pink energy peels off the revealed team"><figcaption>Cloak broken<span>Generated reveal effects, the Cole/Decker exchange, then combat resumes.</span></figcaption></figure></div>
<p><a href="../../index.html?build=rebel-gang-1004" target="_blank">Open the updated game</a> · <a href="checks.json">Chromium checks</a></p><p><small>Whole authored rebel ships, original portraits and warning system. New Decker effect sheet generated with built-in imagegen. Gameplay and visual checks pass; difficulty feel still benefits from your playthrough.</small></p></main>
<script>
const frame=document.querySelector('#arena'),status=document.querySelector('#status');let timer;
document.querySelectorAll('[data-fight]').forEach(btn=>btn.onclick=()=>{clearInterval(timer);const mode=btn.dataset.fight,diff=document.querySelector('#difficulty').value,pilot=document.querySelector('#pilot').value;status.textContent='Loading encounter…';frame.hidden=false;
frame.onload=()=>{let tries=0;timer=setInterval(()=>{const w=frame.contentWindow;if(++tries>1200){clearInterval(timer);status.textContent='Loading took too long. Click to retry.';return;}if(!w.BOFDEBUG||typeof w.rg4Init!=='function')return;
try{w.eval('ht27Stop();debugFight=null;coopOn=false;diffKey='+JSON.stringify(diff)+';DIFF=DIFFS[diffKey];run.pilot='+JSON.stringify(pilot)+';run.mode="campaign";run.lives=9;beginStage(6);setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;special=null;thunderStorm=null;s6Opening=null;s6Wing=null;fb2Talk=null;stagePlan=[];spawnClock=9999;waveIdx=999;enemies=[];eBullets=[];pBullets=[];powerups=[];boss=null;bossActive=false;subBoss=null;subBossActive=false;stageTimer=0;player.x=worldWidth()/2;player.y=VH-130;camX=player.x-VW/2;player.invuln=3;run.weapon=7;run.wlevel=3;run.wlevels[7]=3;run.bombs=15;spawnBoss("rebelsquad");boss._be=null;rg4Warm();');
if(mode!=='intro')w.eval('rf28Init(boss,boss._rebels);boss._rebels.frIntro={done:true};boss.enter=false;boss._noHit=false;boss._rebels.ships.forEach(q=>{q.mode="fight";q.x=worldWidth()/2+(q.i-2)*70;q.y=125+(q.i%2)*35;});rg4Init(boss);H3.release=false;');
if(mode==='gang'||mode==='scene')w.eval('boss._rebels.ships.slice(0,3).forEach(q=>q.hp=q.max*.5);boss.hp=boss._rebels.ships.reduce((sum,q)=>sum+q.hp,0);rg4Threshold(boss,boss._rebels.gang1004);');
if(mode==='scene')w.eval('boss._rebels.gang1004.scene=null;rg4RescueStart(boss,boss._rebels.gang1004);');
w.eval('Audio.init();Audio.resume();');clearInterval(timer);status.textContent='Encounter ready.';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});
}catch(e){clearInterval(timer);status.textContent='Encounter could not start. Click to retry.';console.error(e);}},100);};frame.src='../../index.html?build=rebel-gang-1004-review';});
</script></html>'''
(O/'review.html').write_text(page,encoding='utf-8')
print(O/'review.html')
