"""Build the local, evidence-labelled review for the corrected modular roster."""
import json
from pathlib import Path

OUT=Path('_shots/modular_roster_0927')
ROSTER=[
 ('cryospear','furious','Stage 3 · Rime Wall','New modular ice bastion. Neutral arrival, nuclear transformation, then alternating elemental forms on Furious. Cannons and rocket racks break independently.'),
 ('olivewarden','hard','Stage 4 miniboss · Iron Warden','Black/brown warship with separate rotating guns, rocket racks and modular escorts. Destroying a weapon interrupts the current attack.'),
 ('stormsovereign','hard','Stage 4 boss · Storm Sovereign','Blue military hull, animated lightning reactor, shield nodes and compact modular gun helpers. The camera keeps its normal scale.'),
 ('spacebomber','normal','Stage 5 · Tempest Void Eclipse','Black Tempest reimagined as a space bomber. Separate engines and forward laser cannons; bombs threaten the pursuit lane.'),
 ('spacebomber','hard','Stage 5 · Tempest Silver Eclipse','Silver spacecraft variant on Hard. Shoot a charging laser module to interrupt the burst; destroy engines to reduce lateral movement.'),
 ('siegebomber','normal','Stage 6 · Eclipse Siege Bomber','The Earth bomber belongs here. Half-viewport wingspan, rearward bomb drops, northbound giant beams and destructible engines/cannons.')
]
cards=[]
for kind,diff,title,desc in ROSTER:
 name=f'{kind}-{diff}'
 cards.append(f'<article><h2>{title}</h2><p>{desc}</p><video controls preload="metadata" poster="{name}-review-1.png" src="{name}.webm"></video><p class="caption">{diff.title()} · 26 seconds · silent inspection recording</p></article>')
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fury Fighters · Modular encounter review</title>
<style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#07111b;color:#e3edf8;font:16px/1.55 system-ui,sans-serif}main{max-width:1260px;margin:auto;padding:34px 24px 80px}h1{font-size:clamp(28px,4vw,46px);line-height:1.1;margin:12px 0}h2{font-size:22px;line-height:1.25;margin:0 0 12px}h3{margin-bottom:8px}.eyebrow{color:#79d7ff;font-weight:700;letter-spacing:.15em;font-size:12px}p{max-width:90ch}a{color:#8ddcff}nav{display:flex;gap:20px;flex-wrap:wrap;margin:22px 0}.notice{padding:16px 20px;border-left:4px solid #e8bc64;background:#172335;margin:22px 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{border:1px solid #29435a;background:#101e2d;padding:20px;border-radius:12px}article p{min-height:75px;color:#c5d3e2}video{display:block;width:100%;max-height:570px;background:#000}.caption{font-size:13px;min-height:0!important;color:#93adc6!important;margin-bottom:0}table{width:100%;border-collapse:collapse;margin:18px 0 30px}th,td{text-align:left;padding:12px;border-bottom:1px solid #29435a;vertical-align:top}th{color:#89d5ff}details{padding:14px 18px;background:#101e2d;border:1px solid #29435a;margin-top:24px}summary{cursor:pointer;font-weight:700}.evidence{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.evidence img{width:100%;height:300px;object-fit:contain;background:#000} @media(max-width:760px){.grid,.evidence{grid-template-columns:1fr}main{padding:24px 14px}article p{min-height:0}th,td{padding:9px}}</style>
<main><div class="eyebrow">BULLETS OF FURY · SEPTEMBER 27</div><h1>The corrected modular roster</h1><p>New parts, readable weapon origins and the corrected Earth/space bomber assignments. These are the current in-engine assemblies, with independently targetable weapons.</p><nav><a href="../../index.html">Open the game</a><a href="../../bossmode.html">Open boss practice</a><a href="../../docs/MODULAR_ROSTER_0927.md">Development notes</a></nav>
<div class="notice"><strong>What these clips prove:</strong> live Chromium rendering, attack sequencing and module presentation. Damage immunity and staged damage/helper activation are used for inspection. These are silent recordings, not campaign wins or proof of final difficulty balance.</div>
<div class="grid">'''+''.join(cards)+'''</div>
<h2 style="margin-top:36px">Difficulty direction</h2><table><thead><tr><th>Mode</th><th>Current direction</th></tr></thead><tbody><tr><td>Easy</td><td>Lower enemy and encounter HP, slower and fewer bullets, longer warnings and recovery windows. Equipment-based adaptive pressure no longer cancels the handicap.</td></tr><tr><td>Normal</td><td>Standard health and readable recovery openings. Breaking a mounted gun cancels its attack and removes its firepower.</td></tr><tr><td>Hard</td><td>Higher durability and faster encounter timing. Silver space Tempest variant.</td></tr><tr><td>Furious</td><td>Highest intended campaign challenge. Stage 3 nuclear/elemental mechanics and access to the final shapeshifting form and true-ending sequence.</td></tr></tbody></table>
<details open><summary>Verification and remaining balance work</summary><p id="counts">Verification report is available below.</p><p>The stage sampler used ordinary damage/lives with automated movement and a fixed Yuri loadout, for up to 180 simulated seconds per stage. It reset between stages and skipped opening cinematics. Stages 1–2 and 7–8 frequently defeated that controller; Stage 6 often outlasted the sample. Those outcomes need player review and longer encounter testing. No uninterrupted human campaign clear or strict stage-by-stage difficulty ranking is claimed.</p><p><a href="report.json">20 encounter fixtures</a> · <a href="focused-report.json">Targeting and final-form checks</a> · <a href="balance/report.json">36 stage samples</a> · <a href="suite-final.log">Full test log</a></p></details>
<details><summary>Destroyed-module checks</summary><p>All four weapons removed through the damage path. Empty hardpoints remain, and those weapons stop shooting.</p><div class="evidence">'''+''.join(f'<figure><img loading="lazy" src="{k}-normal-broken.png" alt="{t} with destroyed weapon modules"><figcaption>{t}</figcaption></figure>' for k,t in [('cryospear','Rime Wall'),('olivewarden','Iron Warden'),('spacebomber','Space Tempest')])+'''</div></details></main></html>'''
log=(OUT/'suite-final.log').read_text(encoding='utf-8')
passed=sum(line.lstrip().startswith('ok  ') for line in log.splitlines())
assert 'BUILD OK, 0 ERRORS' in log
html=html.replace('Verification report is available below.',f'{passed:,} assertions passed in the complete suite. Twenty encounter fixtures cover the five new encounters on Easy, Normal, Hard and Furious. The stage sampler covers all nine stages on all four modes. Browser page and console error lists are empty.')
(OUT/'review.html').write_text(html,encoding='utf-8')
print('Review built:',passed,'passing assertions')
