"""Register exact generated source pixels and measured source rectangles. No raster edits."""
from pathlib import Path
import argparse,hashlib,json,shutil
from PIL import Image
R=Path(__file__).resolve().parents[1]
source=R/'_ART_SOURCES/s4_core_revival_1006/core_revival.png'
out=R/'assets/game/s4_core_revival_1006'
im=Image.open(source);assert im.mode=='RGBA' and im.size==(1448,1086)
data=source.read_bytes();sha=hashlib.sha256(data).hexdigest();cell=362
clips={};frameQA=[]
for row,(name,pivot) in enumerate([('charge',[190,218]),('conduit',[58,190]),('socket',[190,162])]):
 frames=[]
 for col in range(4):
  a=im.getchannel('A').crop((col*cell,row*cell,(col+1)*cell,(row+1)*cell));bbox=a.point(lambda v:255 if v>=24 else 0).getbbox();assert bbox
  x,y,ex,ey=bbox;assert x>0 and y>0 and ex<cell and ey<cell
  frames.append({'rect':[col*cell+x,row*cell+y,ex-x,ey-y],'offset':[x-pivot[0],y-pivot[1]]})
  frameQA.append({'cell':row*4+col,'significantAlphaBounds':list(bbox),'minimumSignificantPadding':min(x,y,cell-ex,cell-ey),'allAlphaBounds':list(a.getbbox())})
 clips[name]={'row':row,'pivot':pivot,'frames':frames}
art={'key':'s4rev1006','path':'assets/game/s4_core_revival_1006/core_revival.png','cell':cell,'clips':clips,'conduitEndpointSpan':267}
manifest={**art,'source':str(source.relative_to(R)).replace('\\','/'),'sha256':sha,'nativeSize':list(im.size),'grid':[4,3],'frameQA':frameQA,'pixelProcessing':'None: source PNG copied byte-for-byte. Draw rectangles omit the low-alpha outer wisps beyond each significant-alpha bounding box, preserving all pixels with alpha >=24.','notes':'Requested dimensions and 40px fully empty padding were not fully honored. Actual equal cells measured at362px; exact cropped source rectangles prevent cross-cell sampling. Fixed per-clip pivots reviewed in native game. Cosmetic only.'}
ap=argparse.ArgumentParser();ap.add_argument('--write',action='store_true');args=ap.parse_args()
js='"use strict";\n/* Generated by _BUILD_SOURCE/build_s4_core_revival_1006.py. */\nconst S4REV1006_ART='+json.dumps(art,separators=(',',':'))+';\n'
if args.write:
 out.mkdir(parents=True,exist_ok=True);shutil.copyfile(source,out/'core_revival.png');(out/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8');(R/'assets/s4_core_revival_art_1006.js').write_text(js,encoding='utf-8')
else:
 assert (out/'core_revival.png').read_bytes()==data
 assert json.loads((out/'manifest.json').read_text())==manifest
 assert (R/'assets/s4_core_revival_art_1006.js').read_text()==js
print(json.dumps({'verified':True,'sourceSha256':sha,'nativeSize':im.size,'clips':list(clips),'minimumSignificantPadding':min(f['minimumSignificantPadding'] for f in frameQA),'pixelsEdited':False}))
