"""Pack generated Fusion pixels; preserve alpha and shared animation scale."""
from pathlib import Path
from PIL import Image
import json, shutil, argparse

def build(root):
    src=root/'_ART_SOURCES/fusion_0930'; src.mkdir(parents=True,exist_ok=True)
    dst=root/'assets/game/fusion_0930'; dst.mkdir(parents=True,exist_ok=True)
    gen=Path('C:/Users/Mike/.codex/generated_images/01a0c9fd-a6cc-73a3-8dca-3e0f7a90a956')
    effect=gen/'exec-587db68b-af83-4351-bc08-aab39ce6c6ed.png'
    icons=gen/'exec-82de6b5d-5f50-467e-bd22-4b5edcdc9fc2.png'
    if not (src/'effects.png').exists():shutil.copy2(effect,src/'effects.png')
    if not (src/'icons.png').exists():shutil.copy2(icons,src/'icons.png')
    effect=src/'effects.png';icons=src/'icons.png'
    im=Image.open(effect).convert('RGBA'); registry={}
    # The generated rows have unequal height. Explicit reviewed cuts retain every
    # pixel; all frames within a row share one scale and fixed cell-centre anchor.
    rows=[('beam',0,.385,96,256),('charge',.385,.615,160,160),
          ('impact',.615,.815,160,160),('scar',.815,1,128,128)]
    for name,t,b,w,h in rows:
        cells=[im.crop((round(i*im.width/4),round(t*im.height),round((i+1)*im.width/4),round(b*im.height))) for i in range(4)]
        bounds=[c.getchannel('A').point(lambda x:255 if x>32 else 0).getbbox() for c in cells]; union=(min(q[0] for q in bounds),min(q[1] for q in bounds),max(q[2] for q in bounds),max(q[3] for q in bounds))
        scale=min((w-8)/(union[2]-union[0]),(h-8)/(union[3]-union[1]))
        size=(round((union[2]-union[0])*scale),round((union[3]-union[1])*scale))
        atlas=Image.new('RGBA',(4*w,h))
        for i,c in enumerate(cells):
            c=c.crop(union).resize(size,Image.Resampling.NEAREST)
            atlas.alpha_composite(c,(i*w+(w-size[0])//2,(h-size[1])//2))
        atlas.save(dst/(name+'.png'))
        registry[name]={'key':'fusion30_'+name,'path':'assets/game/fusion_0930/'+name+'.png','frames':[[i*w,0,w,h] for i in range(4)],'fps':16,'ink':[(w-size[0])//2,(h-size[1])//2,size[0],size[1]]}
    im=Image.open(icons).convert('RGBA')
    for i in range(5):
        c=im.crop((round(i*im.width/5),0,round((i+1)*im.width/5),im.height));c=c.crop(c.getbbox())
        c.thumbnail((100,108),Image.Resampling.NEAREST);out=Image.new('RGBA',(104,112));out.alpha_composite(c,((104-c.width)//2,(112-c.height)//2))
        name='icon_'+str(i+1);out.save(dst/(name+'.png'))
        registry[name]={'key':'fusion30_'+name,'path':'assets/game/fusion_0930/'+name+'.png','frames':[[0,0,104,112]],'fps':0}
    (dst/'manifest.json').write_text(json.dumps(registry,indent=2)+'\n',encoding='utf-8')
    (src/'provenance.json').write_text(json.dumps({'tool':'built-in image_gen','sources':[str(effect),str(icons)],'processing':'Reviewed row cuts; shared per-row bounding box/scale; nearest-neighbour resampling; alpha preserved. No painted pixels.'},indent=2)+'\n',encoding='utf-8')
    (root/'assets/fusion_art_0930.js').write_text('/* Generated by build_fusion_0930.py. */\nconst FUSION30_ART='+json.dumps(registry,separators=(',',':'))+';\n',encoding='utf-8',newline='\n')
    print('Fusion: 16 effect frames and 5 icons packed with alpha.')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('root',type=Path);build(p.parse_args().root)
