"""Register the five authored alien transformations without modifying their pixels.
New sheets only: existing atlases and their frame manifests remain untouched.
"""
from pathlib import Path
from PIL import Image
import json, shutil, hashlib
R=Path(__file__).resolve().parents[1]
S=R/'_ART_SOURCES/finale_1003b'; D=R/'assets/game/finale_1003b'
S.mkdir(parents=True,exist_ok=True); D.mkdir(parents=True,exist_ok=True)
G=Path('C:/Users/Mdogg/.codex/generated_images/01a0e3c8-265d-7731-8ffe-ee42ebb5ba3c')
sources={'furnace':'b7bc63af-2d61-4bfd-91b2-743401d6a4d1','cryo':'be464c2a-44e6-4413-a38d-3b309b51e81a','storm':'1f1755c6-d5c4-48c4-b98a-dd64ae5eb08a','harrier':'42b2cdf0-cc10-449a-adc3-d3019408d4d2','warden':'279cfae8-4312-4eca-881d-2a6352d88120'}
out={}
for name,uid in sources.items():
 src=S/(name+'.png')
 if not src.exists():shutil.copyfile(G/('exec-'+uid+'.png'),src)
 dst=D/src.name;shutil.copyfile(src,dst)
 im=Image.open(src);assert im.mode=='RGBA' and im.getchannel('A').getextrema()[0]==0
 w,h=im.size;assert w%2==0 and h%2==0
 # Equal cells and a common origin keep every whole boss plate aligned.
 out[name]={'key':'finale1003b_'+name,'path':dst.relative_to(R).as_posix(),'cw':w//2,'ch':h//2,'cols':2,'frames':4,'size':[w,h],'source':src.relative_to(R).as_posix(),'sha256':hashlib.sha256(src.read_bytes()).hexdigest()}
(D/'manifest.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
(R/'assets/finale_art_1003b.js').write_text('/* Generated by _BUILD_SOURCE/build_finale_1003b.py. */\nconst FINALE1003B_ART='+json.dumps(out,separators=(',',':'))+';\n',encoding='utf-8')
print(json.dumps({k:v['size'] for k,v in out.items()}))
