"""Code-owned sheets: measured component gutters, untouched generated alpha."""
from pathlib import Path
from PIL import Image
import json, shutil
ROOT=Path('assets/game/modular_roster_0927');ROOT.mkdir(parents=True,exist_ok=True)
GEN=Path('C:/Users/Mdogg/.codex/generated_images/01a0e3c8-265d-7731-8ffe-ee42ebb5ba3c')
SOURCES={
'space':('exec-37fef332-2c17-4b17-9b9b-5bd65558216a.png',[(0,0,512,548),(512,0,1024,548),(1024,0,1536,548),(0,548,512,1024),(512,548,1024,1024),(1024,548,1536,1024)]),
'corefx':('exec-7398e934-6240-465d-95d4-616cb183eee5.png',[(x*444,y*444,(x+1)*444,(y+1)*444) for y in range(2) for x in range(4)]),
'rime':('exec-b56602f8-1c0c-4b1c-ab36-626dcb1edd4b.png',[(0,0,700,615),(700,0,1120,615),(1120,0,1536,615),(0,615,680,1024),(680,615,1120,1024),(1120,615,1536,1024)]),
'storm':('exec-a1ec5b1f-bf1f-4f77-83ed-fdddff64fea8.png',[(0,0,651,721),(651,0,955,721),(955,0,1254,721),(0,721,430,1254),(430,721,780,1254),(780,721,1254,1254)]),
'iron':('exec-4fff7dd1-6eab-4109-829a-16e03108f006.png',[(0,0,770,730),(770,0,1190,670),(1190,0,1536,670),(0,730,580,1024),(580,670,1190,1024),(1190,670,1536,1024)]),
}
meta={}
for name,(source,regions) in SOURCES.items():
 im=Image.open(GEN/source).convert('RGBA');shutil.copyfile(GEN/source,ROOT/(name+'.png'));cells=[]
 for r in regions:
  a=im.crop(r).getchannel('A');bb=a.point(lambda v:255 if v>96 else 0).getbbox();assert bb
  x,y,w,h=r[0]+bb[0],r[1]+bb[1],bb[2]-bb[0],bb[3]-bb[1]
  cells.append([x,y,w,h])
 if name=='corefx':
  relative=[[c[0]-r[0],c[1]-r[1],c[0]-r[0]+c[2],c[1]-r[1]+c[3]] for c,r in zip(cells,regions)]
  box=[min(c[0] for c in relative),min(c[1] for c in relative),max(c[2] for c in relative),max(c[3] for c in relative)]
  cells=[[r[0]+box[0],r[1]+box[1],box[2]-box[0],box[3]-box[1]] for r in regions]
 meta[name]={'path':str(ROOT/(name+'.png')).replace('\\','/'),'source':source,'cells':cells}
Path('assets/modular_roster_art_0927.js').write_text('/* Generated by build_modular_roster_0927.py; measured alpha bounds. */\nconst MR27_ART='+json.dumps(meta,separators=(',',':'))+';\n',encoding='utf-8')
Path('docs/modular_roster_art_0927.json').write_text(json.dumps({'generator':'builtin image_gen','reference_directory':'_shots/modular_roster_0927/references','sheets':meta},indent=2),encoding='utf-8')
print(json.dumps(meta,indent=2))
