"""Package native screenshots, recordings and music as a local review artifact."""
from pathlib import Path
import html,json
out=Path('_shots/muzzles_0926')
videos=[('player-weapons','Player weapons','Machine gun → spread → missiles → laser → orb → chaingun. Three seconds each.'),('player-specials','Pilot charge and release','Maverick → Falva → Decker → Freezer → Yuri. Held charge, release, breath and lightning.'),('magmaward','Inferno Reaver','Furious charred fire now leaves the lower gun pods.'),('olivewarden','Olive Warden','Forward guns and separate rocket pods use their actual mounts.'),('stormsovereign','Storm Sovereign','Visible turret flashes and helper muzzle alignment during live patterns.')]
shots=[('magmaward-firing','Reaver gun pod'),('olivewarden-firing','Warden gun tip'),('stormsovereign-firing','Sovereign lightning muzzle'),('maverick','Maverick charge'),('falva','Falva charge'),('decker','Decker shotgun'),('freezer','Freezer ice breath'),('yuri','Yuri lightning'),('player-0','Machine gun'),('player-1','Spread'),('player-7','Chaingun'),('manual-missile','Missile ignition')]
v=''.join(f'<article><h2>{title}</h2><video controls playsinline preload="metadata" src="{name}.webm"></video><p>{caption}</p></article>' for name,title,caption in videos)
s=''.join(f'<a class="still" href="{name}.png"><img loading="lazy" src="{name}.png" alt="{title}"><span>{title}</span></a>' for name,title in shots)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Bullets of Fury — weapon feedback and Hammerman music</title><style>
*{box-sizing:border-box}body{margin:0;background:#080e16;color:#e8f0f8;font:16px/1.5 system-ui,sans-serif}main{max-width:1220px;margin:auto;padding:32px 24px 72px}h1{font-size:36px;line-height:1.12;margin:8px 0 16px}h2{font-size:21px;margin:0 0 14px}p{color:#b7c8d9}a{color:#8bd8ff}header{max-width:830px;margin-bottom:28px}.tag{font-size:12px;color:#91bdce;letter-spacing:2px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:20px}article,.music{padding:20px;border:1px solid #304252;background:#101e2a;border-radius:10px;margin-bottom:20px}video{display:block;width:100%;max-height:670px;background:#020509}audio{width:100%;margin:10px 0}article p{margin-bottom:0}.stills{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.still{display:block;text-decoration:none;border:1px solid #304252;border-radius:6px;overflow:hidden;background:#101e2a}.still img{width:100%;display:block}.still span{display:block;padding:10px}section{margin:36px 0}.note{padding:14px 18px;border-left:3px solid #75c8e8;background:#13232e}.music-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:20px}
</style><main><header><div class="tag">BULLETS OF FURY · SEPTEMBER 26–27</div><h1>Gun barrels, charge effects<br>and Hammerman Cometh</h1><p>Weapon-specific muzzle flashes, corrected boss firing points, and the new Stage 5 music assignment. All screenshots and video below come from the game’s native Chromium renderer.</p></header><div class="note">5,159 assertions pass · 55 pilot/weapon firing cases · 8 special/missile checks · 0 page or console errors.<br>Recordings use isolated invulnerable fixtures for visual inspection.</div><section><h2>Stage 5 music</h2><div class="music-grid"><div class="music"><b>Miniboss — previous boss theme</b><audio controls preload="metadata" src="../../assets/game/levels/stage_05/audio/music/Level5mb.mp3"></audio></div><div class="music"><b>Boss — Hammerman Cometh</b><audio controls preload="metadata" src="../../assets/game/levels/stage_05/audio/music/Level5b.mp3"></audio></div></div></section><section><h2>In motion</h2><div class="grid">'''+v+'''</div></section><section><h2>Firing-point stills</h2><div class="stills">'''+s+'''</div></section><p><a href="../../docs/WEAPON_MUZZLES_0926.md">Implementation and verification notes</a> · <a href="verification.json">Native verification data</a> · <a href="suite-final.log">Full suite log</a></p></main></html>'''
(out/'review.html').write_text(page,encoding='utf-8')
report=json.loads((out/'verification.json').read_text())
report['suite']={'passed':5159,'failed':0,'exit_code':0,'baseline_passed':5142,'baseline_failed':0,'log':'_shots/muzzles_0926/suite-final.log'}
report['music_import']=json.loads((out/'music.json').read_text())
report['recordings']=json.loads((out/'videos.json').read_text())
Path('docs/qa/weapon_muzzles_0926.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
