"""Register generated full-row muzzle reels. Preserve RGBA and a shared source scale."""
from pathlib import Path
from PIL import Image
import json,shutil,numpy as np
ROOT=Path('assets/game/director_0927');ROOT.mkdir(parents=True,exist_ok=True)
GEN=Path('C:/Users/Mdogg/.codex/generated_images/01a0e3c8-265d-7731-8ffe-ee42ebb5ba3c')
SOURCES={
 'ballistic':('exec-5e1e1737-3c2e-4c02-9399-e810b2db6325.png',['mg','chaingun','spread','shotgun']),
 'elemental':('exec-3b0944c5-334a-46d9-a232-a24c312e5a9e.png',['fire','ice','lightning','toxic']),
 'energy':('exec-8d795751-439d-4c99-af08-5d1cf39ec006.png',['laser','orb','sonic','void']),
 'specialist':('exec-9b2c0e97-929f-451b-a1ba-9a6e96c39947.png',['missile','roller','helix','exhaust'])}
meta={'sheets':{},'reels':{}}
for name,(src,families) in SOURCES.items():
 im=Image.open(GEN/src).convert('RGBA');assert im.size==(1536,1024)
 shutil.copyfile(GEN/src,ROOT/(name+'.png'))
 meta['sheets'][name]={'path':str(ROOT/(name+'.png')).replace('\\','/'),'source':src}
 for row,family in enumerate(families):
  frames=[]
  for col in range(6):
   # The narrow ignition root is centered. Measure its lower edge without
   # pulling the anchor toward detached sparks or broad lateral smoke.
   ar=np.asarray(im)[row*256:(row+1)*256,col*256:(col+1)*256]
   hot=(ar[:,:,3]>160)&(ar[:,:,:3].max(axis=2)>110)
   ys,xs=np.where(hot[:,108:149]);assert len(ys)
   anchor=min(251,int(ys.max())+1)
   frames.append([col*256,row*256,256,256,128,anchor])
  meta['reels'][family]={'sheet':name,'frames':frames}
Path('assets/director_art_0927.js').write_text('/* Generated by build_director_art_0927.py. */\nconst DIRECTOR_ART='+json.dumps(meta,separators=(',',':'))+';\n',encoding='utf-8')
Path('docs/director_art_0927.json').write_text(json.dumps({'generator':'builtin image_gen',**meta},indent=2),encoding='utf-8')
print('16 reels / 96 frames; alpha preserved')
