"""Register measured rectangles/pivots without altering generated RGBA pixels."""
from pathlib import Path
from PIL import Image
import json,hashlib,shutil
R=Path(__file__).resolve().parents[1];S=R/'_ART_SOURCES/herald_1003f';D=R/'assets/game/herald_1003f'
S.mkdir(parents=True,exist_ok=True);D.mkdir(parents=True,exist_ok=True)
src=S/'parts.png'
if not src.exists():shutil.copyfile('C:/Users/Mdogg/.codex/generated_images/01a0e3c8-265d-7731-8ffe-ee42ebb5ba3c/exec-36379e6f-36c6-497b-b4fa-a2c573c75921.png',src)
dst=D/'parts.png';shutil.copyfile(src,dst)
im=Image.open(src);assert im.mode=='RGBA' and im.size==(1254,1254) and im.getchannel('A').getextrema()==(0,255)
parts={
 'core':{'rect':[70,0,310,623],'pivot':[155,300],'attach':[0,0],'scale':.34,'z':1,'hit':[155,315,110,280]},
 'head':{'rect':[493,133,270,435],'pivot':[136,383],'attach':[0,-12],'scale':.21,'z':4,'hit':[136,193,95,150]},
 'wingL':{'rect':[795,0,459,622],'pivot':[425,245],'attach':[-37,-18],'scale':.32,'z':0,'hit':[230,310,115,225]},
 'wingR':{'rect':[0,626,458,622],'pivot':[30,245],'attach':[37,-18],'scale':.32,'z':0,'hit':[225,310,115,225]},
 'gunL':{'rect':[549,646,210,594],'pivot':[56,87],'attach':[-42,12],'scale':.23,'z':2,'hit':[101,329,72,228],'muzzle':[95,497]},
 'gunR':{'rect':[902,646,211,594],'pivot':[155,87],'attach':[42,12],'scale':.23,'z':2,'hit':[110,329,72,228],'muzzle':[113,497]}
}
for name,p in parts.items():
 x,y,w,h=p['rect'];assert x+w<=im.width and y+h<=im.height
 assert im.crop((x,y,x+w,y+h)).getchannel('A').getbbox(),name
out={'key':'hd1003_parts','path':dst.relative_to(R).as_posix(),'size':list(im.size),'parts':parts,'sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'source':src.relative_to(R).as_posix()}
(D/'manifest.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
(R/'assets/herald_art_1003f.js').write_text('/* Generated by build_herald_1003f.py; measured source rectangles and joints. */\nconst HD1003_ART='+json.dumps(out,separators=(',',':'))+';\n',encoding='utf-8')
print(json.dumps({'components':list(parts),'sha256':out['sha256']}))
