"""Own registrations and measured component rectangles. Source pixels stay untouched."""
from pathlib import Path
from PIL import Image
import json, shutil, hashlib
R=Path(__file__).resolve().parents[1]
S=R/'_ART_SOURCES/finale_modular_1003c'; D=R/'assets/game/finale_modular_1003c'
D.mkdir(parents=True,exist_ok=True)
G=Path('C:/Users/Mdogg/.codex/generated_images/01a0e3c8-265d-7731-8ffe-ee42ebb5ba3c')
for name,uid in {'head':'19a3bba8-cf38-40d4-8228-a9c426245177','storm_hull':'c48c26a5-249b-4fe6-9dda-1eb773771b1f'}.items():
 p=S/(name+'.png')
 if not p.exists():shutil.copyfile(G/('exec-'+uid+'.png'),p)
# Boxes measured from the rendered generated sheets, not assumed from prompts.
boxes={
 'furnace':{'core':[381,0,490,630],'left':[30,55,320,580],'right':[903,55,320,580],'legL':[30,640,310,560],'legR':[914,640,310,560],'reactor':[450,733,350,360]},
 'chopper':{'core':[550,0,440,578],'left':[114,64,258,458],'right':[1165,64,257,458],'rackL':[145,590,217,408],'rackR':[1175,590,227,408],'tail':[550,573,430,451]},
 'cryo':{'core':[25,0,450,710],'left':[520,52,300,650],'right':[867,55,355,650],'rackL':[25,716,405,480],'rackR':[819,709,420,484],'reactor':[466,729,320,504]},
 'storm':{'left':[528,50,340,566],'right':[896,50,334,566],'rackL':[30,635,340,580],'rackR':[881,632,346,591],'lightning':[540,631,190,604]},
 'harrier':{'core':[352,0,549,756],'fanL':[0,225,350,390],'fanR':[903,222,351,392],'rackL':[29,807,340,385],'rackR':[883,807,356,385],'beam':[516,768,223,439]},
 'warden':{'core':[330,0,590,660],'left':[28,138,314,490],'right':[909,138,321,490],'gun':[79,707,300,461],'legL':[440,661,360,558],'legR':[883,661,358,558]},
 'knight':{'core':[60,18,358,387],'swordArm':[962,0,280,408],'shieldArm':[52,423,262,387],'legL':[530,423,219,388],'legR':[967,418,219,394],'sword':[136,815,177,407],'shield':[508,815,292,407],'joint':[970,880,264,299]},
 'head':{'head':None},'storm_hull':{'core':None},
 'sword_fx':{str(i):[(i%4)*384,(i//4)*512,384,512] for i in range(8)}
}
out={}
for name,parts in boxes.items():
 src=S/(name+'.png');dst=D/src.name;shutil.copyfile(src,dst)
 im=Image.open(src);assert im.mode=='RGBA' and im.getchannel('A').getextrema()[0]==0
 rects={}
 for part,box in parts.items():
  if box is None:
   x,y,ex,ey=im.getchannel('A').point(lambda a:255 if a>8 else 0).getbbox();box=[x,y,ex-x,ey-y]
  x,y,w,h=box;assert x>=0 and y>=0 and x+w<=im.width and y+h<=im.height,(name,part,box)
  rects[part]=box
 out[name]={'key':'fmc_'+name,'path':dst.relative_to(R).as_posix(),'size':list(im.size),'rects':rects,'source':src.relative_to(R).as_posix(),'sha256':hashlib.sha256(src.read_bytes()).hexdigest()}
(D/'manifest.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
(R/'assets/finale_modular_art_1003c.js').write_text('/* Generated by build_finale_modular_1003c.py; measured source rectangles. */\nconst FMC_ART='+json.dumps(out,separators=(',',':'))+';\n',encoding='utf-8')
print(json.dumps({k:len(v['rects']) for k,v in out.items()}))
