"""Owns exact generated-source import and grid extraction; never repaints pixels."""
from pathlib import Path
from PIL import Image
import json,hashlib,shutil
R=Path(__file__).resolve().parents[1] if Path(__file__).parent.name=='_BUILD_SOURCE' else Path(r'C:\Users\Mike\Desktop\Github Coding\BulletsOfFury')
G=Path(r'C:\Users\Mike\.codex\generated_images\01a10ef4-27c3-71d2-97c8-0d9fa5c0bb2f')
S=R/'_ART_SOURCES/hardcorps_1007'; O=R/'assets/game/hardcorps_1007'
S.mkdir(parents=True,exist_ok=True);O.mkdir(parents=True,exist_ok=True)
sources={
 'void':('exec-cddd7430-d41b-4c72-bd1d-497a3ff6e0c8.png',4,4),
 'helix':('exec-2f20d844-63e3-4166-8323-31938010bc6f.png',4,4),
 'cast':('exec-4ac4a885-b8a9-4cf8-a556-f2fd77d5cb61.png',2,4)}
prompts={
 'void':'''Production animation spritesheet for a 2D Neo Geo / Sega 32X shmup. Redesign reference void as a vastly smoother EVIL CHROMIUM BLACK VORTEX with glossy liquid black-chrome symbiote tendrils and fine silver-white / violet / crimson electrical veins. EXACTLY SIXTEEN equally sized animation frames in a perfectly regular 4 columns by 4 rows grid, square overall sheet. Every tile centers the identical circular vortex at identical scale and pivot with at least 16% transparent empty padding on every side; no clipped strands, no overlap. The animation is ONE continuous smooth 360-degree inward-spinning loop, advancing 22.5 degrees in each successive reading-order frame, maintaining circular silhouette and size. Deep fully opaque near-black center like a hole in space, tightly coiled tubular chrome arms funneling inward, thin sharply defined lightning running through the arms, occasional tiny silver energy shards caught near rim. OPAQUE BLACK MATERIAL and dark interior must stay visible; genuine transparent alpha only outside effect. Strong silver and violet directional highlights, restrained saturated crimson accents, firm dark pixel edges, crisp pixel clusters at game sprite scale. No flat halo, no radial soft glow cloud, no text, labels, borders, character or backdrop. Consistent sequence, not sixteen designs. Preserve overall sinister black/chrome identity of reference while making a fluid stable vortex.''',
 'helix':'''Production VFX spritesheet for an evil liquid black-chromium SYMBIOTE TRANSFORMATION spiral in a Neo Geo/Sega32X pixel-art top-down shmup. EXACT SIXTEEN animation frames in a regular 4 columns x 4 rows square grid. Each equally sized cell has the same pivot and scale and 15 percent completely empty transparent padding. Continuous looping motion: three slender glossy black-chrome living ribbons corkscrew around an invisible upright humanoid volume in a spherical HELIX, like a living coiled serpent circling above, behind and below a boss while it changes shape. Interior has large clear transparent openings so underlying boss remains visible. Strong silver beveled highlights with narrow crimson/violet energy veins, dark outlines. Clearly asymmetric spiral with an upper back arc and lower front arc, smoothly advancing rotation through sixteen sequential phases. Thin branching tendrils connect the ribbons; occasional small sharp square code fragments follow the coil. Opaque material, NO aura, NO fuzzy halo, NO circular flat ring, NO neon smoke. Crisp high-detail pixel clusters, production alpha, no characters, no text, numbers, frames or backdrop. All sixteen images are sequential frames of ONE effect, not different designs.''',
 'cast':'''Production animation SPRITESHEET of the exact reference black/chrome/red Code Hammer robot casting dark energy. Tall PORTRAIT sheet: EXACTLY TWO COLUMNS and FOUR ROWS, eight cells total. Layout 1024 wide by 2048 tall if possible, each square tile contains ONE complete pose at the SAME SMALL SCALE with 18% EMPTY TRANSPARENT MARGIN on all sides, all feet at consistent baseline and red chest reactor at same x. Entire robot including hammer fits inside every cell without clipping. Eight sequential poses reading order: idle; free RIGHT hand lifts; free hand beside head; free arm fully raised ABOVE HELMET with open claw palm; fully raised palm charges small sharp violet/black knot; full overhead spell release; recoil elbow bends; arm lowers to idle. Opposite hand retains the large crimson-and-black hammer hanging at hip throughout, separate from casting hand. Exact reference silver pointed helmet, evil red eyes, silver-black articulated armor, red round chest reactor and knee emitters, black tendrils at shoulders; fixed 3/4-front slightly overhead camera. Fully opaque character pixels, crisp NeoGeo pixel clusters with thick black outline. Absolutely NO shadows under or around robot, NO blurry glow, NO fog, NO background gradients. Only tiny crisp violet finger sparks in poses 5 and 6. TRUE ALPHA TRANSPARENCY outside the complete robot, NO TEXT, NO grid lines. Make small sprites in generous spaced square slots, not a poster. Eight poses of the same character, identical scale.'''}
reactors=[(220,218),(661,218),(220,663),(661,663),(220,1108),(660,1107),(220,1518),(660,1518)]
hands=[(121,281),(551,199),(136,575),(596,500),(153,936),(595,935),(139,1435),(563,1575)]
heads=[(370,325),(810,325),(370,770),(810,770),(370,1215),(810,1215),(370,1628),(810,1628)]
arts={}; manifest={'generator':'image_gen','date':'2026-10-07','policy':'Preserve source; exact grid extraction only. No resampling, masks or pixel repaint.','sources':{}}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
for name,(source,cols,rows) in sources.items():
 src=S/(name+'_source.png')
 if not src.exists():shutil.copyfile(G/source,src)
 im=Image.open(src).convert('RGBA');W,H=im.size;arr=[]
 for i in range(cols*rows):
  x0=round((i%cols)*W/cols);x1=round((i%cols+1)*W/cols);y0=round((i//cols)*H/rows);y1=round((i//cols+1)*H/rows)
  cell=im.crop((x0,y0,x1,y1));dst=O/(name+'_'+str(i)+'.png');cell.save(dst,optimize=True)
  a={'key':'hc7_'+name+'_'+str(i),'path':dst.relative_to(R).as_posix(),'w':cell.width,'h':cell.height,'sourceBox':[x0,y0,x1,y1],'sha256':sha(dst)}
  if name=='cast':
   a.update(px=(reactors[i][0]-x0)/cell.width,py=(reactors[i][1]-y0)/cell.height,hand=[hands[i][0]-x0,hands[i][1]-y0],head=[heads[i][0]-x0,heads[i][1]-y0])
  arr.append(a)
 arts[name]=arr;manifest['sources'][name]={'path':src.relative_to(R).as_posix(),'generatorFile':source,'sha256':sha(src),'dimensions':[W,H],'mode':'RGBA','grid':[cols,rows],'prompt':prompts[name],'reference':'assets/game/levels/stage_08/boss/hammer_knight_1005/hammer_0.png' if name=='cast' else 'assets/game/levels/stage_08/stage/alien_arena_1005/void_10.png' if name=='void' else None}
stage=S/'stage4_airbase.png'
if stage.exists():manifest['sources']['stage4_airbase']={'path':stage.relative_to(R).as_posix(),'sha256':sha(stage),'dimensions':list(Image.open(stage).size),'deployed':'assets/game/levels/stage_04/stage/hardcorps_1007/stage4_airbase.png','generatorFile':'exec-fc37b5d0-f130-42f8-95ad-d38bf515d505.png','reference':'assets/game/levels/stage_04/stage/stage4_highway_0915.png','prompt':'''Create a replacement production background tile for Bullets of Fury, a top-down vertically scrolling Neo Geo / Sega 32X military shmup. Reference is the CURRENT stage road only for crisp pixel-cluster texture, desert orange sand and asphalt palette. Make a much richer LOST ABANDONED AIRBASE IN THE DESERT, viewed perfectly straight overhead with no perspective/horizon. One tall portrait image 1024x1536 or larger proportional. A broad but readable cracked central highway runs straight vertically from the exact top center to bottom center, with faded yellow divider and road edges at matching positions at both edges so it repeats vertically. Highway connected to looping perimeter access roads bending around sunken hangars, dusty aprons, abandoned fuel tanks, radar dishes, concrete bunkers, wrecked unoccupied aircraft silhouettes, sand drifts and scrub. Facilities mostly on left and right thirds, dark neutral clear central flight area for bullets. Large interesting authored structures and readable terrain, restrained detail not visual noise. Decommissioned airfield, military science-fiction scale, sun-bleached ochre, dusty tan, charcoal tarmac, faded olive metal, cracked concrete. Crisp hand-placed-looking pixel clusters with dark outlines, no painterly blur, no glow. This is a seamless VERTICAL SCROLL TILE: top and bottom 10 percent have the same straight highway and compatible sand and apron areas, no landmark crosses top/bottom seam. No pilots, enemy units, projectiles, HUD, menu, typography or labels. Fill the entire canvas with terrain, no border.'''}
(S/'generation_manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
(O/'finale_manifest.json').write_text(json.dumps(arts,indent=2),encoding='utf-8')
(R/'assets/hardcorps_finale_art_1007.js').write_text('"use strict";\nconst HC7_ART='+json.dumps(arts,separators=(',',':'))+';\n',encoding='utf-8',newline='\n')
print(json.dumps({'frames':sum(map(len,arts.values())),'deployedBytes':sum((R/a['path']).stat().st_size for arr in arts.values() for a in arr),'sources':{k:v['sha256'] for k,v in manifest['sources'].items()}}))
