from pathlib import Path
import html
W=Path(__file__).resolve().parent;R=W.parent if W.name=='_BUILD_SOURCE' else Path(r'C:/Users/Mike/Desktop/Github Coding/BulletsOfFury')
O=R/'_shots/finale_ai_1006';O.mkdir(parents=True,exist_ok=True)
cards=[('Furious Hammer: two warned side strikes','hammer-chain.gif'),('Furious knight: three warned code volleys','knight-code.gif'),('All 16 authored native poses','motion-contact.jpg'),('Furious ghost warp','ghost-furious.png'),('Furious colossus and followup','colossus-furious.png')]
cards += [(name+' — Furious',f'copy-{n}-furious.png') for n,name in [(1,'Code chopper'),(2,'Code Furnace'),(3,'Code ice ship'),(4,'Code storm ship'),(6,'Code carrier'),(7,'Code sewer beast')]]
items=''.join('<figure><img loading="lazy" src="'+html.escape(f)+'"><figcaption>'+html.escape(n)+'</figcaption></figure>' for n,f in cards)
(O/'review.html').write_text('''<!doctype html><html><meta charset="utf-8"><title>Stage 8 form AI and motion pass</title><style>body{background:#070b0e;color:#e6edf2;font:16px system-ui;margin:28px auto;max-width:1250px;padding:0 20px}h1{font-size:28px}a{color:#8ce5ff}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}figure{margin:0;background:#141c24;border:1px solid #344957;padding:9px}img{width:100%;height:auto;image-rendering:pixelated}figcaption{padding:10px 2px;font-weight:600}p{line-height:1.5;max-width:900px}code{color:#ffd2ad}</style><h1>Stage 8 — stronger forms and complete Hammer motion</h1><p>Real local game-canvas captures. The animated clips are silent protected combat fixtures; the motion contact shows controlled native poses. These do not claim an unassisted Furious clear or final human balance approval.</p><p><a href="../../index.html">Play the updated build</a> · <a href="../../docs/qa/finale_ai_1006.json">Verification report</a> · <a href="../hammer_knight_1005/review.html">Prior Hammer/knight mechanics</a>. Passwords: <code>HAMR8</code>, <code>KNIGHT</code>, <code>FINAL3</code>.</p><p>Six distinct donor followups use one warned burst on Normal, two on Hard and up to three on Furious. Busy native boss attacks defer those casts. Furious knight adds an independently warned smite and alternating code volleys; Hammer returns the side swing after a fresh warning. Original armor, restore counter and emergency reserve remain.</p><div class="grid">'''+items+'</div></html>',encoding='utf-8')
print(O/'review.html')
