from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'_shots/rebel_arsenal_1004c';O.mkdir(parents=True,exist_ok=True)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rebel arsenals · Bullets of Fury</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080e1b;color:#edf3ff;font:16px/1.5 system-ui}main{max-width:1250px;margin:auto;padding:30px 24px 70px}h1{font-size:clamp(36px,5vw,60px);line-height:1.1;margin:10px 0}h2{margin-top:36px}p{max-width:900px;color:#b9c9df}.tag{font-size:12px;letter-spacing:2px;color:#76e9ed}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.two{grid-template-columns:repeat(2,1fr)}figure{margin:0;background:#111c30;border:1px solid #304965}img{width:100%;display:block;image-rendering:pixelated}figcaption{padding:14px}figcaption span{display:block;font-size:13px;color:#adbed7}a{color:#80eaff}.buttons{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}button,select{padding:10px;border:1px solid #4e7c97;background:#19334b;color:#fff;font:inherit;cursor:pointer;border-radius:5px}button:hover{background:#295673}iframe{width:100%;height:900px;border:1px solid #4e7c97}#status{min-height:24px}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid #304965}.art{max-height:620px;object-fit:contain;background:#142033}small{color:#adbed7}@media(max-width:750px){.grid{grid-template-columns:1fr 1fr}main{padding:24px 12px}}@media(max-width:490px){.grid{grid-template-columns:1fr}}</style>
<main><div class="tag">BULLETS OF FURY · FIVE AGAINST FIVE</div><h1>Personal arsenals. Shared fury.</h1><p>Five pilots with machine guns, their own special pickups, and different ways to pressure your team. Shoot enemy ability boxes to delay their specials. Watch the original warnings, intercept rockets, and break Jace’s helix ball before it bursts.</p>
<div class="buttons"><select id="difficulty" aria-label="Difficulty"><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option><option value="furious" selected>Furious</option></select><select id="pilot" aria-label="Pilot">'''
for k in ['yuri','decker','cole','axel','falva','lizzie','maverick','freezer','juggernaut']:page+=f'<option value="{k}">{k.title()}</option>'
page+='''</select><button data-mode="intro">Full encounter</button><button data-mode="fight">Fight now</button><button data-mode="gang">Gang Mode</button></div>
<div class="buttons"><button data-mode="turbo">Voss turbo</button><button data-mode="fusion">Voss Fusion</button><button data-mode="slug">Rook .50 cal</button><button data-mode="helix">Jace helix</button><button data-mode="rockets">Kaia rockets</button><button data-mode="cloak">Nyx stealth</button></div>
<div class="buttons"><select id="survivor" aria-label="Counter-scan survivor"><option value="kaia">Kaia alive</option><option value="nyx">Kaia down · Nyx scans</option><option value="jace">Both ladies down · Jace scans</option><option value="rook">Jace down · Rook scans</option><option value="voss">Only Voss remains</option></select><button data-mode="scene">Decker cloak scene</button></div>
<p id="status" role="status">Choose an encounter. Practice does not write campaign saves.</p><iframe id="arena" title="Playable Rebel dogfight" hidden allow="autoplay"></iframe>
<table><tr><th>Pilot</th><th>Special</th><th>Counterplay</th></tr><tr><td>Voss</td><td>Turbo dash and repeated offscreen rams; retained pink Fusion</td><td>Warning rows commit before each pass</td></tr><tr><td>Rook</td><td>Alternating .50-cal slug chainguns and charge rams</td><td>Read the lane, dodge the long burst</td></tr><tr><td>Jace</td><td>Red/orange helix ball detonating in eight directions</td><td>Shoot the ball before its nova</td></tr><tr><td>Nyx</td><td>Faint stealth tracing with ambush gunfire</td><td>Watch her trace; missile acquisition and HP hide</td></tr><tr><td>Kaia</td><td>Attached dual rocket pods, alternating locked/free missiles</td><td>Destroy her teal/black rockets or deny the box</td></tr></table>
<h2>Authored boxes and icons</h2><img class="art" src="../../assets/game/levels/stage_06/boss/rebel_arsenal_1004c/ui.png" alt="Five generated chrome special boxes and hex icons: Voss, Nyx, Rook, Kaia and Jace">
<h2>Inside the game</h2><div class="grid"><figure><img src="turbo-release.png" alt="Voss executes a pink turbo dash"><figcaption>Turbo ram<span>Whole hull rotates through a warned, committed dash.</span></figcaption></figure><figure><img src="alternating-rockets.png" alt="Kaia launches alternating teal missiles"><figcaption>Twin rocket rack<span>Anchored pods fire one at a time.</span></figcaption></figure><figure><img src="helix-eight-way-nova.png" alt="Eight orange energy balls expand from Jace's helix explosion"><figcaption>Helix nova<span>Actual Maverick ball and charge palette swap; eight mini balls.</span></figcaption></figure></div>
<div class="grid two"><figure><img src="cloak-ambush.png" alt="Nyx's faint cloak tracing and ambush fire"><figcaption>Ghostknife cloak<span>Her HP badge and missile target disappear while cloaked.</span></figcaption></figure><figure><img src="scanner-rook.png" alt="Rook owns the counter-scan dialogue after Kaia, Nyx and Jace fall"><figcaption>Survivor counter-scan<span>Kaia → Nyx → Jace → Rook → Voss. Living Voss corrects Rook’s big-boss boast.</span></figcaption></figure></div>
<p><a href="../../index.html?build=rebel-arsenal-1004c" target="_blank">Open the updated game</a> · <a href="checks.json">Native Chromium checks</a></p><small>Generated UI/effect sheets, existing ship/portrait/warning art, and true luminance-preserving palette swaps. Automated verification checks behavior and pixels; final difficulty feel needs your playthrough.</small></main>
<script>
const frame=document.querySelector('#arena'),status=document.querySelector('#status');let timer;
document.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{clearInterval(timer);const mode=btn.dataset.mode,diff=document.querySelector('#difficulty').value,pilot=document.querySelector('#pilot').value,scanner=document.querySelector('#survivor').value;status.textContent='Loading encounter…';frame.hidden=false;
frame.onload=()=>{let tries=0;timer=setInterval(()=>{const w=frame.contentWindow;if(++tries>1200){clearInterval(timer);status.textContent='Loading took too long. Click to retry.';return;}if(!w.BOFDEBUG||typeof w.ra4SupplyTick!=='function')return;
try{w.Storage.prototype.setItem=function(){};w.Storage.prototype.removeItem=function(){};
w.eval('ht27Stop();debugFight=null;coopOn=false;diffKey='+JSON.stringify(diff)+';DIFF=DIFFS[diffKey];run.pilot='+JSON.stringify(pilot)+';run.mode="campaign";run.lives=9;beginStage(6);setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;special=null;thunderStorm=null;s6Opening=null;s6Wing=null;fb2Talk=null;stagePlan=[];spawnClock=9999;waveIdx=999;enemies=[];eBullets=[];pBullets=[];powerups=[];boss=null;bossActive=false;subBoss=null;subBossActive=false;subBossDone=subBossTriggered=true;stageTimer=0;player.x=worldWidth()/2;player.y=VH-130;camX=player.x-VW/2;player.invuln=180;run.weapon=7;run.wlevel=3;run.wlevels[7]=3;run.bombs=10;groundTargetingReset();s6WingInit();s6WingLaunch(4,true);Object.assign(s6Wing,{all:true,route:"right",beats:3,fakeDone:true,supplyIndex:3,choice:false,boxes:[]});spawnBoss("rebelsquad");boss._be=null;rg4Warm();');
if(mode!=='intro')w.eval('rf28Init(boss,boss._rebels);boss._rebels.frIntro={done:true};boss.enter=false;boss._noHit=false;boss._rebels.ships.forEach(q=>{q.mode="fight";q.warp=0;q.x=worldWidth()/2+(q.i-2)*70;q.y=125+(q.i%2)*35;});rg4Init(boss);H3.release=false;');
if(mode==='gang')w.eval('boss._rebels.ships.slice(0,3).forEach(q=>q.hp=q.max*.5);boss.hp=boss._rebels.ships.reduce((n,q)=>n+q.hp,0);rg4Threshold(boss,rg4State());');
if(mode==='scene'){const priority=['kaia','nyx','jace','rook','voss'],dead=priority.slice(0,priority.indexOf(scanner));w.eval('boss._rebels.ships.filter(q=>'+JSON.stringify(dead)+'.includes(q.key)).forEach(q=>{q.dead=true;q.hp=0;});boss.hp=boss._rebels.ships.reduce((n,q)=>n+q.hp,0);rg4State().gang=true;rg4RescueStart(boss,rg4State());');}
if(['turbo','fusion','slug','helix','rockets','cloak'].includes(mode)){const key={turbo:'voss',fusion:'voss',slug:'rook',helix:'jace',rockets:'kaia',cloak:'nyx'}[mode];w.eval('rg4State().rescueDone=true;rg4State().releaseAt=rg4State().age+8;boss._rebels.ships.forEach(q=>q.rg4.cd=8);rg4Attack(boss._rebels.ships.find(q=>q.key==='+JSON.stringify(key)+'),boss._rebels,rg4State(),'+JSON.stringify(mode)+');');}
w.eval('Audio.init();Audio.resume();Audio.startMusic("stagex");');clearInterval(timer);status.textContent='Encounter ready.';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});
}catch(e){clearInterval(timer);status.textContent='Encounter could not start. Click to retry.';console.error(e);}},100);};frame.src='../../index.html?build=rebel-arsenal-1004c-practice';});
</script></html>'''
(O/'review.html').write_text(page,encoding='utf-8')
print(O/'review.html')
