"""Register measured generated code FX; keep authored source pixels untouched."""
from pathlib import Path
from PIL import Image
import json, shutil, hashlib
R=Path(__file__).resolve().parents[1]
S=R/'_ART_SOURCES/codewall_1003d'; D=R/'assets/game/codewall_1003d'
D.mkdir(parents=True,exist_ok=True)
out={}
for name in ['wall','impact','shatter','morph']:
 src=S/(name+'.png'); im=Image.open(src)
 assert im.mode=='RGBA' and im.getchannel('A').getextrema()==(0,255)
 if name=='wall':
  # Twelve measured digit baselines. Frame gutters are deliberately excluded.
  rects={'blueRows':[105,115,422,432],'blueRim':[704,87,461,465],
         'redRows':[105,719,422,432],'redRim':[704,673,474,506]}
 else:
  cols=4;rows=3 if name=='morph' else 2
  rects={str(i):[round((i%cols)*im.width/cols),round((i//cols)*im.height/rows),
                round((i%cols+1)*im.width/cols)-round((i%cols)*im.width/cols),
                round((i//cols+1)*im.height/rows)-round((i//cols)*im.height/rows)] for i in range(cols*rows)}
 for box in rects.values():
  x,y,w,h=box;assert x>=0 and y>=0 and x+w<=im.width and y+h<=im.height
 dst=D/src.name;shutil.copyfile(src,dst)
 out[name]={'key':'cwd_'+name,'path':dst.relative_to(R).as_posix(),'size':list(im.size),'rects':rects,
            'source':src.relative_to(R).as_posix(),'sha256':hashlib.sha256(src.read_bytes()).hexdigest()}
(D/'manifest.json').write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8')
(R/'assets/codewall_art_1003d.js').write_text('/* Generated by build_codewall_1003d.py. */\nconst CWD_ART='+json.dumps(out,separators=(',',':'))+';\n',encoding='utf-8')
print('Registered four authored code-wall sources with measured cells.')
