"""Publish only Mike's seven selected revisions and their approved component sheets.
Copies authored pixels unchanged; bounds/pivots and XART registration are one output.
"""
from pathlib import Path
from PIL import Image
import json,shutil,hashlib
R=Path(__file__).resolve().parents[1];S=R/'_ART_SOURCES/monster_mutator_1003/revision2';D=R/'assets/game/mutator_1003';D.mkdir(parents=True,exist_ok=True)
selected={'01':'bluehybrid','03':'hexpyre','04':'hellram','06':'riflelocust','07':'impharrow','08':'furnacemaw','11':'hellhugger'}
m=json.loads((S/'manifest.json').read_text(encoding='utf-8'));out={}
for f in m['files']:
 if not f['active'] or f['id'] not in selected:continue
 name=selected[f['id']]+('_parts' if f['kind']=='parts' else '')
 src=S/f['file'];dst=D/(name+'.png');shutil.copyfile(src,dst)
 im=Image.open(src);a=im.getchannel('A');assert a.getextrema()[0]==0
 x0,y0,x1,y1=a.point(lambda v:255 if v>16 else 0).getbbox()
 out[name]={'key':'mm1003_'+name,'path':str(dst.relative_to(R)).replace('\\','/'),'size':list(im.size),'rect':[x0,y0,x1-x0,y1-y0],'source':str(src.relative_to(R)).replace('\\','/'),'sha256':hashlib.sha256(src.read_bytes()).hexdigest()}
rigs=json.loads((S/'rigs.json').read_text(encoding='utf-8'))['rigs']
for name,rig in rigs.items():rig['key']='mm1003_'+name+'_parts'
payload={'art':out,'rigs':rigs,'selected_ids':list(selected),'source_manifest':str((S/'manifest.json').relative_to(R)).replace('\\','/')}
(D/'manifest.json').write_text(json.dumps(payload,indent=2)+'\n',encoding='utf-8')
(R/'assets/mutator_art_1003.js').write_text('/* Generated by _BUILD_SOURCE/build_mutator_1003.py; authored pixels unchanged. */\nconst MM1003_ART='+json.dumps(out,separators=(',',':'))+';\nconst MM1003_RIGS='+json.dumps(rigs,separators=(',',':'))+';\n',encoding='utf-8')
print('Registered seven approved enemies and three modular kits:',len(out),'unchanged PNGs')
