"""Normalize nine generated flags and derive registered, anchored UI states."""
from pathlib import Path
from PIL import Image,ImageOps,ImageFilter
import json,shutil,hashlib,colorsys
R=Path(__file__).resolve().parents[1];A=R/'_ART_SOURCES/campaign_landscape_1004f';O=R/'assets/game/campaign_landscape_1004f'
jobs=json.loads((A/'flag_generation.json').read_text());assert len(jobs)==9
records=[];layout={}
def palette(im,color):
 out=im.copy();pixels=out.load();original=im.load()
 for y in range(im.height):
  for x in range(im.width):
   r,g,b,a=original[x,y];hi=max(r,g,b);lo=min(r,g,b)
   # Cloth-only saturation mask preserves chrome, ink outlines and ivory glyphs.
   if a<12 or hi-lo<35 or (hi-lo)/max(1,hi)<.35:continue
   lum=(.299*r+.587*g+.114*b)/255
   hue,sat,_=colorsys.rgb_to_hsv(*(c/255 for c in color))
   rgb=colorsys.hsv_to_rgb(hue,sat,min(1,lum*1.65))
   pixels[x,y]=tuple(round(c*255) for c in rgb)+(a,)
 return out
for n,job in enumerate(jobs,1):
 src=A/f'flag_{n}_source.png'
 if not src.exists():shutil.copy2(job['path'],src)
 raw=Image.open(src).convert('RGBA');assert raw.getchannel('A').getextrema()[0]==0
 # Ignore near-transparent generated padding when measuring the visible mast.
 # Preserve original RGBA inside that crop; never recolor or mask its pixels.
 bb=raw.getchannel('A').point(lambda a:255 if a>=16 else 0).getbbox();cut=raw.crop(bb);cut.thumbnail((216,288),Image.Resampling.NEAREST)
 im=Image.new('RGBA',(240,320));im.alpha_composite(cut,((240-cut.width)//2,16))
 alpha=im.getchannel('A');bounds=alpha.getbbox();bottom=alpha.crop((0,int(bounds[3]*.9),240,bounds[3])).getbbox()
 anchor=[(bottom[0]+bottom[2])/480,bounds[3]/320]
 states={'av':im}
 lock=ImageOps.grayscale(im).convert('RGBA');lock.putalpha(alpha);states['lock']=lock
 for state,color in [('done_gold',(255,200,45)),('done_silver',(206,214,226)),('done_green',(70,214,104))]:states[state]=palette(im,color)
 white=Image.new('RGBA',im.size,(255,255,255));white.putalpha(alpha);states['white']=white
 for f,radius in [(0,13),(1,25)]:
  # Selection is a derived silhouette halo behind intact original authored pixels.
  glow=Image.new('RGBA',im.size,(255,48,48));glow.putalpha(alpha.filter(ImageFilter.MaxFilter(radius)).point(lambda a:round(a*.65)))
  glow.alpha_composite(im);states['hi'+str(f)]=glow
 for state,pixels in states.items():pixels.save(O/f'flag_{n}_{state}.png')
 layout[n]={'roman':job['label'],'anchor':anchor,'size':[240,320]}
 records.append({'stage':n,**layout[n],'source':src.name,'crop':bb,'sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'prompt':job['prompt'],'states':list(states)})
manifest={'generator':'OpenAI built-in imagegen, one referenced edit per numeral','normalization':'Alpha crop and nearest-neighbor contain. Cloth-only rank palettes preserve neutral chrome, lettering and alpha. Selected halos are derived silhouettes; no procedural art.','flags':records}
for d in [A,O]:(d/'flag_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
# Bring the approved X into the same normalized canvas without changing its art.
xraw=Image.open(A/'flag_x.png').convert('RGBA');xbb=xraw.getchannel('A').point(lambda a:255 if a>=16 else 0).getbbox()
xcut=xraw.crop(xbb);xcut.thumbnail((216,288),Image.Resampling.NEAREST)
x=Image.new('RGBA',(240,320));x.alpha_composite(xcut,((240-xcut.width)//2,16));x.save(O/'flag_x.png')
xa=x.getchannel('A');xb=xa.getbbox();base=xa.crop((0,int(xb[3]*.9),240,xb[3])).getbbox();xanchor=[(base[0]+base[2])/480,xb[3]/320]
xlock=ImageOps.grayscale(x).convert('RGBA');xlock.putalpha(xa);xlock.save(O/'flag_x_lock.png')
code="'use strict';\n// Generated by build_campaign_flags_1004f.py. Measured mast-base anchors.\nconst MAP4F_FLAGS="+json.dumps(layout,separators=(',',':'))+';\nconst MAP4F_X_ANCHOR='+json.dumps(xanchor)+';\n'
(R/'assets/campaign_flags_art_1004f.js').write_text(code,encoding='utf-8')
p=R/'assets/data/ART_TAXONOMY.json';d=json.loads(p.read_text(encoding='utf-8'));d['map4f_']['note']='Generated physical Fury HQ frontage and X-only flag; nine separately generated I–IX flags, measured mast-base anchors, cloth-only rank swaps and alpha-derived selected/lock/white states. Sources/prompts _ART_SOURCES/campaign_landscape_1004f. Owning workflows build_campaign_markers_1004f.py and build_campaign_flags_1004f.py. Old sources retained; no existing atlas edits.'
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
# Review sheet uses final shipped pixels, not approximations of the game renderer.
sheet=Image.new('RGBA',(240*5,320*2),(5,20,32,255))
for n in range(1,10):sheet.alpha_composite(Image.open(O/f'flag_{n}_av.png'),(((n-1)%5)*240,((n-1)//5)*320))
sheet.alpha_composite(x,(960,320))
sheet.save(O/'flags_preview.png')
print('Built nine Roman flags with eight UI states each and measured mast-base anchors.')
