const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),src=path.join(root,'_shots','stage7_warden_shared_rail_warning_0915','results.json');
if(!fs.existsSync(src))throw new Error('missing Chromium evidence');const qa=JSON.parse(fs.readFileSync(src,'utf8'));if((qa.errors||[]).length||(qa.checks||[]).some(x=>!x.pass))throw new Error('Chromium evidence is not green');
const qout=path.join(root,'docs','qa','stage7_warden_shared_rail_warning_0915.json');fs.mkdirSync(path.dirname(qout),{recursive:true});fs.writeFileSync(qout,JSON.stringify(qa,null,2)+'\n');
const p=path.join(root,'docs','REQUEST_CHECKLIST_0914.json'),list=JSON.parse(fs.readFileSync(p,'utf8')),item=list.items.find(x=>x.id==='ENG-02');if(!item||item.status!=='partial')throw new Error('ENG-02 partial row missing');
list.updated='2026-09-15';list.latestBatch={description:'Stage-7 Toxic Portal Warden rail fan with charge-start aim and safe-gap commitment, five shared green/yellow/red path fields and one unobscured overhead alert',evidence:'STAGE7_WARDEN_SHARED_RAIL_WARNING_0915.md'};fs.writeFileSync(p,JSON.stringify(list,null,2).replace(/\n/g,'\r\n')+'\r\n');
const shared=path.join(root,'docs','SHARED_NONLASER_WARNING_0915.md'),text=fs.readFileSync(shared,'utf8'),mark='## Toxic Portal Warden rail follow-up';if(!text.includes(mark))fs.appendFileSync(shared,`\n${mark}\n\nThe Stage-7 Toxic Portal Warden now commits its rail aim and safe-side gap when the 0.86-second charge begins. Five shared green/yellow/red fields preview the five spear paths and one matching alert renders in front of the giant hull. Chromium 15/15 and focused section 335 7/7 pass. See [STAGE7_WARDEN_SHARED_RAIL_WARNING_0915.md](STAGE7_WARDEN_SHARED_RAIL_WARNING_0915.md).\n`);
function appendOnce(file,mark,text){const p=path.join(root,file),s=fs.readFileSync(p,'utf8');if(!s.includes(mark))fs.appendFileSync(p,'\n'+text.trim()+'\n');}
appendOnce('CLAUDE.md','## 2026-09-15 Toxic Portal Warden shared rail warning',`\n## 2026-09-15 Toxic Portal Warden shared rail warning\nENG-02 advances: the Stage-7 Warden commits its five-spear rail fan and safe-side gap at charge start, then previews the actual paths through shared green/yellow/red fields and one matching alert. Fields render behind the boss; the alert renders in front after Chromium exposed hull occlusion in the first capture. Focused 7/7 and corrected Chromium 15/15 pass with zero errors; the confirmation suite has the exact 57-name baseline. ENG-02 remains partial. See docs/STAGE7_WARDEN_SHARED_RAIL_WARNING_0915.md.\n`);
appendOnce('HANDOFF_CODEX.md','## Codex update — 2026-09-15: Toxic Portal Warden rail warning',`\n## Codex update — 2026-09-15: Toxic Portal Warden rail warning\n\n- ENG-02 advances: the Stage-7 Toxic Portal Warden rail fan now commits its aim and safe-side gap at charge start. Five shared green/yellow/red fields show every released spear lane; one matching overhead alert renders in front of the giant hull.\n- Focused 7/7 and corrected Chromium 15/15 pass with zero errors. Evidence: docs/STAGE7_WARDEN_SHARED_RAIL_WARNING_0915.md. Tally remains 122 complete / 9 partial / 18 pending.\n`);
console.log('CLOSED_STAGE7_WARDEN_SHARED_RAIL_WARNING_0915');
