const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),src=path.join(root,'_shots','hammer_shared_leap_warning_0915','results.json');
if(!fs.existsSync(src))throw new Error('missing Chromium evidence');const qa=JSON.parse(fs.readFileSync(src,'utf8'));if((qa.errors||[]).length||(qa.checks||[]).some(x=>!x.pass))throw new Error('Chromium evidence is not green');
const qout=path.join(root,'docs','qa','hammer_shared_leap_warning_0915.json');fs.mkdirSync(path.dirname(qout),{recursive:true});fs.writeFileSync(qout,JSON.stringify(qa,null,2)+'\n');
const p=path.join(root,'docs','REQUEST_CHECKLIST_0914.json'),list=JSON.parse(fs.readFileSync(p,'utf8')),item=list.items.find(x=>x.id==='ENG-02');if(!item||item.status!=='partial')throw new Error('ENG-02 partial row missing');
list.updated='2026-09-15';list.latestBatch={description:'Shared green/yellow/red corridor and overhead warning for the Chrome Hammer committed leap/slam while retaining its landing reticle and one-hand boomerang',evidence:'HAMMER_SHARED_LEAP_WARNING_0915.md'};fs.writeFileSync(p,JSON.stringify(list,null,2).replace(/\n/g,'\r\n')+'\r\n');
const shared=path.join(root,'docs','SHARED_NONLASER_WARNING_0915.md'),text=fs.readFileSync(shared,'utf8'),mark='## Chrome Hammer leap/slam follow-up';if(!text.includes(mark))fs.appendFileSync(shared,`\n${mark}\n\nThe Chrome Hammer leap/slam now projects the shared green/yellow/red FOV and overhead alert down its committed travel corridor while retaining the authored landing reticle. The target is sampled once before the tell and cannot chase a late dodge. Its completed one-hand boomerang remains unchanged. Chromium 16/16 and focused section 334 7/7 pass. See [HAMMER_SHARED_LEAP_WARNING_0915.md](HAMMER_SHARED_LEAP_WARNING_0915.md).\n`);
function appendOnce(file,mark,text){const p=path.join(root,file),s=fs.readFileSync(p,'utf8');if(!s.includes(mark))fs.appendFileSync(p,'\n'+text.trim()+'\n');}
appendOnce('CLAUDE.md','## 2026-09-15 Chrome Hammer shared leap warning',`\n## 2026-09-15 Chrome Hammer shared leap warning\nENG-02 advances: the Chrome Hammer leap/slam now uses the shared green/yellow/red FOV and overhead alert along its committed travel corridor while retaining the exact landing reticle. Late dodges do not redirect it, and the completed one-hand boomerang is unchanged. Focused 7/7, Chromium 16/16 zero errors, full suite 56-name subset of the 57-name baseline with no new failures. ENG-02 remains partial. See docs/HAMMER_SHARED_LEAP_WARNING_0915.md.\n`);
appendOnce('HANDOFF_CODEX.md','## Codex update — 2026-09-15: Chrome Hammer shared leap warning',`\n## Codex update — 2026-09-15: Chrome Hammer shared leap warning\n\n- ENG-02 advances: the Chrome Hammer leap/slam now owns the shared green/yellow/red path field and matching overhead alert while preserving the original committed landing reticle. Late player movement cannot steer the attack.\n- The completed one-hand boomerang timing and behavior are unchanged. Focused 7/7, Chromium 16/16 with zero errors, full suite 56-name subset of the 57-name baseline and no new failure names. Evidence: docs/HAMMER_SHARED_LEAP_WARNING_0915.md. Tally remains 122 complete / 9 partial / 18 pending.\n`);
console.log('CLOSED_HAMMER_SHARED_LEAP_WARNING_0915');
