const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),src=path.join(root,'_shots','sovereign_shared_ram_warning_0915','results.json');
if(!fs.existsSync(src))throw new Error('missing Chromium evidence');const qa=JSON.parse(fs.readFileSync(src,'utf8'));if((qa.errors||[]).length||(qa.checks||[]).some(x=>!x.pass))throw new Error('Chromium evidence is not green');
const qout=path.join(root,'docs','qa','sovereign_shared_ram_warning_0915.json');fs.mkdirSync(path.dirname(qout),{recursive:true});fs.writeFileSync(qout,JSON.stringify(qa,null,2)+'\n');
const p=path.join(root,'docs','REQUEST_CHECKLIST_0914.json'),list=JSON.parse(fs.readFileSync(p,'utf8')),item=list.items.find(x=>x.id==='ENG-02');if(!item||item.status!=='partial')throw new Error('ENG-02 partial row missing');
list.updated='2026-09-15';list.latestBatch={description:'Shared non-laser warning migration for the Storm Sovereign unpowered ram, including an unobscured alert anchor below its dual gauges',evidence:'SOVEREIGN_SHARED_RAM_WARNING_0915.md'};fs.writeFileSync(p,JSON.stringify(list,null,2).replace(/\n/g,'\r\n')+'\r\n');
const shared=path.join(root,'docs','SHARED_NONLASER_WARNING_0915.md'),text=fs.readFileSync(shared,'utf8'),mark='## Stage 4 Sovereign follow-up';if(!text.includes(mark))fs.appendFileSync(shared,`\n${mark}\n\nThe unpowered Storm Sovereign ram now uses the same shared field and overhead alert. Its 0.40-second tracking window, committed lane and one-second release remain intact. An optional shared alert anchor places the sign below Stage 4's dual gauges so it is fully visible. Chromium 14/14 and focused section 332 8/8 pass. See [SOVEREIGN_SHARED_RAM_WARNING_0915.md](SOVEREIGN_SHARED_RAM_WARNING_0915.md).\n`);
function appendOnce(file,mark,text){const p=path.join(root,file),s=fs.readFileSync(p,'utf8');if(!s.includes(mark))fs.appendFileSync(p,'\n'+text.trim()+'\n');}
appendOnce('CLAUDE.md','## 2026-09-15 Sovereign shared ram warning',`\n## 2026-09-15 Sovereign shared ram warning\nENG-02 advances: the unpowered Stage-4 Sovereign ram now uses the shared green/yellow/red FOV and overhead alert while preserving early tracking, late lane commitment and its complete dive/flyover/return. A shared optional alert anchor keeps the sign below the dual boss/shield gauges. Focused 8/8, Chromium 14/14 zero errors, full suite 56 established names with no new failures. ENG-02 remains partial. See docs/SOVEREIGN_SHARED_RAM_WARNING_0915.md.\n`);
appendOnce('HANDOFF_CODEX.md','## Codex update — 2026-09-15: Sovereign shared ram warning',`\n## Codex update — 2026-09-15: Sovereign shared ram warning\n\n- ENG-02 advances: the live unpowered Sovereign ram now owns the shared green/yellow/red field and matching overhead alert, commits after 0.40 seconds and releases at one second without changing its dive/flyover/return.\n- The shared warning renderer accepts an encounter alert anchor; Stage 4 uses it below the dual gauges. Focused 8/8 and Chromium 14/14 with zero errors; the full suite has 56 established names and no new failures. Evidence: docs/SOVEREIGN_SHARED_RAM_WARNING_0915.md. The tally remains 122 complete / 9 partial / 18 pending.\n`);
console.log('CLOSED_SOVEREIGN_SHARED_RAM_WARNING_0915');
