const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),src=path.join(root,'_shots','razorback_shared_ram_warning_0915','results.json');
if(!fs.existsSync(src))throw new Error('missing Chromium evidence');const qa=JSON.parse(fs.readFileSync(src,'utf8'));if((qa.errors||[]).length||(qa.checks||[]).some(x=>!x.pass))throw new Error('Chromium evidence is not green');
const qout=path.join(root,'docs','qa','razorback_shared_ram_warning_0915.json');fs.mkdirSync(path.dirname(qout),{recursive:true});fs.writeFileSync(qout,JSON.stringify(qa,null,2)+'\n');
const p=path.join(root,'docs','REQUEST_CHECKLIST_0914.json'),list=JSON.parse(fs.readFileSync(p,'utf8')),item=list.items.find(x=>x.id==='ENG-02');if(!item||item.status!=='partial')throw new Error('ENG-02 partial row missing');
list.updated='2026-09-15';list.latestBatch={description:'Shared non-laser warning migration for the Razorback body ram, with green-only tracking and a yellow/red committed dodge lane across Normal, Hard and Furious',evidence:'RAZORBACK_SHARED_RAM_WARNING_0915.md'};fs.writeFileSync(p,JSON.stringify(list,null,2).replace(/\n/g,'\r\n')+'\r\n');
const shared=path.join(root,'docs','SHARED_NONLASER_WARNING_0915.md'),text=fs.readFileSync(shared,'utf8'),mark='## Razorback body-ram follow-up';if(!text.includes(mark))fs.appendFileSync(shared,`\n${mark}\n\nThe Razorback body ram now uses the shared green/yellow/red FOV and overhead alert. It tracks only during green, commits at yellow and holds through red and release on Normal, both independent Hard tanks and the Furious hyper tank. Chromium 15/15 and focused section 333 9/9 pass. See [RAZORBACK_SHARED_RAM_WARNING_0915.md](RAZORBACK_SHARED_RAM_WARNING_0915.md).\n`);
function appendOnce(file,mark,text){const p=path.join(root,file),s=fs.readFileSync(p,'utf8');if(!s.includes(mark))fs.appendFileSync(p,'\n'+text.trim()+'\n');}
appendOnce('CLAUDE.md','## 2026-09-15 Razorback shared ram warning',`\n## 2026-09-15 Razorback shared ram warning\nENG-02 advances: Razorback body rams now use the shared green/yellow/red FOV and overhead alert, track only in green and commit for yellow/red through release. Normal, Hard pair actors and Furious all preserve their movement limits. Focused 9/9, Chromium 15/15 zero errors, full suite exact 57-name baseline. ENG-02 remains partial. See docs/RAZORBACK_SHARED_RAM_WARNING_0915.md.\n`);
appendOnce('HANDOFF_CODEX.md','## Codex update — 2026-09-15: Razorback shared ram warning',`\n## Codex update — 2026-09-15: Razorback shared ram warning\n\n- ENG-02 advances: every live Razorback body ram now owns the shared green/yellow/red field and matching overhead alert. Tracking ends when yellow begins, so late dodges cannot move the committed lane.\n- Normal, both Hard actors and Furious retain their existing movement envelopes. Focused 9/9, Chromium 15/15 with zero errors, full suite exact 57-name baseline. Evidence: docs/RAZORBACK_SHARED_RAM_WARNING_0915.md. Tally remains 122 complete / 9 partial / 18 pending.\n`);
console.log('CLOSED_RAZORBACK_SHARED_RAM_WARNING_0915');
