#!/usr/bin/env python3
"""
emit_section_geom_0801kl.py — MEASURED GEOMETRY FOR THE EIGHT 0801hm BODIES

Writes assets/section_geom.js  ->  window.BOFSG

Why this file exists
--------------------
sxDraw's new-body path drew ONE assembled_* frame and returned, which walked
straight past the whole sectional system. To composite the body from its
sections instead, the draw needs to know where each plate sits. Those numbers
were never recorded anywhere - SX_ANCHOR holds hand-guessed fractions like
{x:-0.24,y:-0.18}, which is also what sxHit uses to decide WHICH section a shot
landed on.

Everything here is measured off the art, not estimated:

  off     per-state top-left of the plate on the assembled canvas. The intact
          offsets are template-matched and verified by reassembly: compositing
          every intact plate at these offsets reproduces assembled_intact with
          MAD 0.00 and 100% coverage, 0 missing / 0 extra pixels, on all eight
          families. That is pixel-exact, so the sectional body is not an
          approximation of the assembled body - it IS the assembled body.

          Damage-state offsets are silhouette-matched against the section's own
          intact plate AFTER the crackle strip, because the bolts were exactly
          what made the canvases disagree.

  size    plate w,h per state. Plates are NOT resized - a destroyed plate is
          legitimately bigger than its intact one (debris spreads outward), and
          cropping to a common canvas was tried and thrown away after it ate
          232 real pixels of ntxl_tail_blade_destroyed.

  c       centroid of the intact plate's opaque pixels, in assembled-canvas
          coordinates, as a FRACTION of the canvas (-0.5..0.5 from centre).
          This replaces SX_ANCHOR for these units so a shot is attributed to the
          section actually under it.

  r       the section's opaque radius as a fraction of canvas width, so hit
          attribution can require a shot to land within the part rather than
          merely nearest to it.

  smoke   anchor for the damage smoke plume: the TOP-CENTRE of the plate's
          opaque mass, so smoke rises off the section instead of out of its
          middle.
"""
import json, os, re
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FAMS = ['nlgt', 'nobd', 'nmrv', 'nglr', 'nslc', 'nrmp', 'ntxl', 'ncyc']
STATES = ('intact', 'damaged', 'critical', 'destroyed')


def main():
    man = json.loads(re.search(r'window\.BOFX=([\s\S]*?\});',
                               open(os.path.join(ROOT, 'assets/manifest.js')).read()).group(1))
    img = man['img']
    off = json.load(open(os.path.join(ROOT, 'assets/section_offsets.json')))
    out = {}

    for fam in FAMS:
        ak = f'{fam}_assembled_intact'
        if ak not in img:
            continue
        CW, CH = Image.open(os.path.join(ROOT, img[ak])).size
        secs = {}
        for sect, states in sorted(off.get(fam, {}).items()):
            ik = f'{fam}_{sect}_intact'
            if ik not in img:
                continue
            a = np.array(Image.open(os.path.join(ROOT, img[ik])).convert('RGBA'))
            m = a[:, :, 3] > 128
            if not m.any():
                continue
            ox, oy = states['intact']
            ys, xs = np.nonzero(m)
            cx = (xs.mean() + ox) / CW - 0.5
            cy = (ys.mean() + oy) / CH - 0.5
            # opaque radius: RMS spread, in canvas-width fractions
            rad = float(np.sqrt(((xs - xs.mean()) ** 2 + (ys - ys.mean()) ** 2).mean())) / CW
            # smoke rises from the top-centre of the section's mass
            top = ys.min()
            tcx = xs[ys < top + max(2, (ys.max() - top) * 0.15)].mean()
            sx = (tcx + ox) / CW - 0.5
            sy = (top + oy) / CH - 0.5

            e = {'off': {}, 'size': {},
                 'c': [round(cx, 5), round(cy, 5)],
                 'r': round(rad, 5),
                 'smoke': [round(sx, 5), round(sy, 5)]}
            for st in STATES:
                k = f'{fam}_{sect}_{st}'
                if k in img and st in states:
                    w, h = Image.open(os.path.join(ROOT, img[k])).size
                    e['off'][st] = [int(states[st][0]), int(states[st][1])]
                    e['size'][st] = [w, h]
            secs[sect] = e
        out[fam] = {'canvas': [CW, CH], 'sections': secs}

    js = ("/* GENERATED by _BUILD_SOURCE/emit_section_geom_0801kl.py — do not hand-edit.\n"
          "   Measured section geometry for the eight 0801hm bodies. The intact offsets\n"
          "   reproduce each assembled_intact frame pixel-exactly (MAD 0.00, 100% coverage),\n"
          "   so a body composited from sections is identical to the assembled plate — but\n"
          "   every section can be damaged, smoked and blown off independently. */\n"
          "window.BOFSG=" + json.dumps(out, sort_keys=True, separators=(',', ':')) + ";\n")
    p = os.path.join(ROOT, 'assets/section_geom.js')
    open(p, 'w').write(js)
    n = sum(len(v['sections']) for v in out.values())
    print(f'wrote {p}  {len(out)} families, {n} sections, {len(js)} bytes')
    for f in ('nobd', 'nglr'):
        print(f'  {f} canvas={out[f]["canvas"]}')
        for s, e in out[f]['sections'].items():
            print(f'     {s:18s} c={e["c"]} r={e["r"]} states={sorted(e["off"])}')


if __name__ == '__main__':
    main()
