#!/usr/bin/env python3
"""
lizzie_new_hull_only_0909.py - LIZZIE FLIES THE NEW HULL EVERYWHERE, NOT JUST IN A ROLL.

Mike, 0909, on the goldified roll frames: "those should be the commited final versions and look
of Lizzie's ship", and on a shot of her in play: "delete these variants."

Only her barrel roll came from the resolution pack, so she was flying the OLD gold delta level
and the NEW hull the instant she rolled - the ship changed design mid-manoeuvre. This retires the
old-hull frames. The pack ships her a ROLL and nothing else, so each retired reel is handled on
its own terms rather than all being deleted:

  FLIGHT  idle / _nf / _l / _r      -> the roll reel's own frames. br0 IS the level view; br1 and
                                       br7 are the shallow banks either side. No new pixels.

  BANK    _pv0.._pv4                -> aliased onto the roll: pv2=br0 level, pv1=br1 and pv3=br7
                                       the shallow leans, pv0=br2 and pv4=br6 the edge-on ends.
                                       Lizzie is NOT in SHIP_TWIST_FLIP, so left runs br1->br2 and
                                       right br7->br6; that is the direction her picker expects.
     ⚠ THE pv KEYS ARE ALIASED, NOT DELETED, AND THAT IS DELIBERATE. `applyLizzieSkin` builds
       `_lizzieStockRects` from whatever `BOFX.ships['ship_lizzie'+s]` holds and skips a missing
       key - so deleting pv would let the BOMBER costume write pv rects that toggling OFF could
       never restore, leaving her permanently half-bomber. Keeping the keys keeps that symmetric.

  SPIN    _sp0.._sp7                -> REGENERATED by rotating the new level plate 45 degrees a
                                       step. CLAUDE.md forbids deriving a bank by rotation and
                                       licenses it for exactly this one case: "a spin-out IS an
                                       image-plane rotation ... licensed HERE ONLY". Deleting the
                                       reel instead would drop her off the death spin-out, which
                                       is a header rule Mike says never changes.

  SOMERSAULT _so0.._so7             -> DELETED. A somersault needs authored nose-on and tail-on
                                       views and the pack has none for her; rotation cannot make
                                       them. `somersaultAvailable()` gates on so0, so she simply
                                       loses the move until that art exists. This is the one
                                       actual capability lost here and it is reported, not hidden.

  GLOW    _g1 / _g2 on the above    -> DELETED. They are the baked flame's flicker phases and the
                                       pack has no phase art. `shipGlowKey` falls back to the base
                                       frame when BOFX.ships has no phase, so her flame stops
                                       flickering and nothing else changes.

Her sheet is repacked from scratch afterwards so the retired art does not sit in the file, and
every surviving cell is byte-compared against what it was before the rewrite.
"""
import io, json, os, re, sys
import numpy as np
from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
MAN = os.path.join(ROOT, 'assets/manifest.js')
GAME = os.path.join(ROOT, 'assets/game.js')
SHEET = os.path.join(ROOT, 'assets/game/atlas/ships/ship_lizzie.png')
PAD = 2

src = io.open(MAN, encoding='utf-8', newline='').read()
i = src.index('"ships"')
j = src.index('{', i)
d = 0
for k in range(j, len(src)):
    if src[k] == '{':
        d += 1
    elif src[k] == '}':
        d -= 1
        if d == 0:
            SPAN = (j, k + 1)
            SHIPS = json.loads(src[j:k + 1])
            break

g = io.open(GAME, encoding='utf-8', newline='').read()
gst = g.index('const LIZZIE_B42_RECTS={')
gen = g.index('};', gst) + 2
B42 = {m.group(1): [int(v) for v in m.group(2).split(',')]
       for m in re.finditer(r'"([^"]*)":\[([0-9,\s]+)\]', g[gst:gen])}
if len(B42) != 17:
    print('expected 17 B-42 rects, parsed %d' % len(B42))
    sys.exit(1)

old = Image.open(SHEET).convert('RGBA')
K = lambda s: 'ship_lizzie' + s

# --- what the surviving stock set looks like -------------------------------------------------
ALIAS = {'': '_br0', '_nf': '_br0', '_l': '_br1', '_r': '_br7',
         '_pv2': '_br0', '_pv1': '_br1', '_pv3': '_br7', '_pv0': '_br2', '_pv4': '_br6'}
DROP = ['_so%d' % q for q in range(8)] + \
       [s + p for s in ['', '_l', '_r', '_pv0', '_pv1', '_pv2', '_pv3', '_pv4'] for p in ('_g1', '_g2')]
for s in DROP:
    if K(s) not in SHIPS:
        print('nothing to drop at ' + K(s))

# the spin-out, rotated off the new level plate
lvl = SHIPS[K('_br0')]
lvlimg = old.crop((lvl[0], lvl[1], lvl[0] + lvl[2], lvl[1] + lvl[3]))
CW, CH = lvl[6], lvl[7]
spin = []
for q in range(8):
    rot = lvlimg.rotate(-45 * q, resample=Image.NEAREST, expand=True)
    a = np.array(rot)
    ys, xs = np.where(a[:, :, 3] > 40)
    rot = rot.crop((xs.min(), ys.min(), xs.max() + 1, ys.max() + 1))
    if rot.width > CW or rot.height > CH:
        f = min(CW / rot.width, CH / rot.height)
        rot = rot.resize((max(1, int(rot.width * f)), max(1, int(rot.height * f))), Image.LANCZOS)
    spin.append(rot)

# --- rebuild the cell list, then repack her sheet ---------------------------------------------
items = []            # (id, PIL image, offX, offY)
# the spin keys are REGENERATED below, so they are neither kept nor byte-compared - the first
# run listed them in both and packed each of them twice.
REGEN = ['_sp%d' % q for q in range(8)]
keep = [s for s in [k.replace('ship_lizzie', '') for k in SHIPS if k.startswith('ship_lizzie')]
        if s not in DROP and s not in ALIAS and s not in REGEN]
for s in sorted(keep):
    e = SHIPS[K(s)]
    items.append(('ships:' + K(s), old.crop((e[0], e[1], e[0] + e[2], e[1] + e[3])), e[4], e[5]))
for q, im in enumerate(spin):
    items.append(('ships:' + K('_sp%d' % q), im, (CW - im.width) // 2, (CH - im.height) // 2))
for suf, e in B42.items():
    items.append(('b42:' + suf, old.crop((e[0], e[1], e[0] + e[2], e[1] + e[3])), e[4], e[5]))

area = sum((im.width + PAD * 2) * (im.height + PAD * 2) for _, im, _, _ in items)
W = 1 << (max(256, int((area * 1.18) ** 0.5)) - 1).bit_length()
placed, x, y, rowh = {}, 0, 0, 0
for nm, im, _, _ in sorted(items, key=lambda t: -t[1].height):
    ww, hh = im.width + PAD * 2, im.height + PAD * 2
    if x + ww > W:
        x, y, rowh = 0, y + rowh, 0
    placed[nm] = (x + PAD, y + PAD)
    x += ww
    rowh = max(rowh, hh)
H = y + rowh

sheet = Image.new('RGBA', (W, H), (0, 0, 0, 0))
newships = {k: v for k, v in SHIPS.items() if not (k.startswith('ship_lizzie') and
            (k.replace('ship_lizzie', '') in DROP))}
newb42 = {}
for nm, im, ox, oy in items:
    nx, ny = placed[nm]
    sheet.paste(im, (nx, ny))
    row = [nx, ny, im.width, im.height, ox, oy, CW, CH]
    if nm.startswith('ships:'):
        newships[nm[6:]] = row
    else:
        newb42[nm[4:]] = row
for s, tgt in ALIAS.items():
    newships[K(s)] = list(newships[K(tgt)])          # the same cell, by design
sheet.save(SHEET)
# WARNING: THE SHEET IS SAVED BEFORE THE MANIFEST, SO A CRASH BETWEEN THEM LEAVES A TREE WHERE
# THE PIXELS MOVED AND THE RECTS DID NOT. That happened on the first run - a print() carrying a
# unicode arrow died on a cp1252 console AFTER the save and BEFORE the write, which is a worse
# outcome than failing outright. Nothing between here and the writes may do IO of its own.

# --- verify: everything that survived is byte-identical, and the aliases really alias ----------
chk = Image.open(SHEET).convert('RGBA')
bad = []
for s in sorted(keep):
    o, n = SHIPS[K(s)], newships[K(s)]
    a = np.array(old.crop((o[0], o[1], o[0] + o[2], o[1] + o[3])))
    b = np.array(chk.crop((n[0], n[1], n[0] + n[2], n[1] + n[3])))
    if a.shape != b.shape or not np.array_equal(a, b):
        bad.append(K(s))
for suf, o in B42.items():
    n = newb42[suf]
    a = np.array(old.crop((o[0], o[1], o[0] + o[2], o[1] + o[3])))
    b = np.array(chk.crop((n[0], n[1], n[0] + n[2], n[1] + n[3])))
    if a.shape != b.shape or not np.array_equal(a, b):
        bad.append('b42' + suf)
for s, tgt in ALIAS.items():
    if newships[K(s)] != newships[K(tgt)]:
        bad.append('alias ' + s)
if bad:
    print('ABORT - %d cells did not survive: %s' % (len(bad), ', '.join(bad[:10])))
    sys.exit(1)

print('lizzie sheet %dx%d, %.2f MB' % (W, H, os.path.getsize(SHEET) / 1e6))
print('kept   %d authored cells + 17 B-42' % len(keep))
print('aliased %d flight/bank keys onto the roll: %s' % (len(ALIAS), ', '.join(
    (s or '(idle)') + '->' + t for s, t in ALIAS.items())))
print('rebuilt 8 spin frames by rotation off the new level plate')
print('dropped %d cells: the 8 somersault frames and %d glow phases' % (len(DROP), len(DROP) - 8))
print('verify: every surviving cell byte-identical, all %d aliases resolve to their target' % len(ALIAS))
print('lizzie now has %d ship keys (was 49)' % len([k for k in newships if k.startswith('ship_lizzie')]))
print('')
print('*** SHE CAN NO LONGER SOMERSAULT - somersaultAvailable() gates on so0 and it is gone.')
print('  That needs an authored nose-on and tail-on pass; rotation cannot produce them.')

io.open(MAN, 'w', encoding='utf-8', newline='').write(
    src[:SPAN[0]] + json.dumps(newships, separators=(',', ':'), sort_keys=False) + src[SPAN[1]:])
nl = '\r\n' if '\r\n' in g[:20000] else '\n'
lines = ['const LIZZIE_B42_RECTS={']
for suf, r in newb42.items():
    lines.append('  %s:%s,' % (json.dumps(suf), json.dumps(r, separators=(',', ','))))
lines.append('};')
io.open(GAME, 'w', encoding='utf-8', newline='').write(g[:gst] + nl.join(lines) + g[gen:])
io.open(os.path.join(ROOT, 'assets/data/lizzie_b42_source_rects.json'), 'w',
        encoding='utf-8', newline='\n').write(json.dumps(newb42, indent=1) + '\n')
print('wrote the sheet, the manifest, LIZZIE_B42_RECTS and the b42 json')
