const fs=require('fs'),path=require('path'),p=path.resolve(__dirname,'..','assets','game.js');let s=fs.readFileSync(p,'utf8');if(s.includes('\r'))throw new Error('game.js must remain LF-only');
function one(a,b,label){const n=s.split(a).length-1;if(n!==1)throw new Error(label+' expected once, found '+n);s=s.replace(a,b);}
one(
"function s9FusionWardenFire(w,phase){\n  /* Simulation time owns the wheel. performance.now() kept moving while paused and made the same\n     encounter produce different lanes in headless runs, replays and slow frames. The Wardens\n     counter-rotate from the encounter clock instead. */\n  const rot=phase+(w.side==='L'?1:-1)*phase*1.85;\n  if((Math.floor(phase*2)&1)===0){\n    for(let i=0;i<10;i++){if(i===2||i===7)continue;eShootT(w.x,w.y+38,rot+i*TAU/10,2.75,'s9warp',{w:18,h:28,silent:i>0});}\n  }else{\n    const a=Math.atan2(player.y-w.y,player.x-w.x);\n    for(let i=-2;i<=2;i++)eShootT(w.x,w.y+38,a+i*0.13,3.75,'s9needle',{w:8,h:34,silent:i>-2});\n  }\n  navalFlash(null,{x:w.x,y:w.y+38},.84,BPFX_MUZZLE_LASER,{n:8,hpx:52,life:.14,\n    follow:()=>w&&!w.disabled?{x:w.x,y:w.y+38}:null});\n}",
"function s9FusionWardenFire(w,phase,committedAim){\n  /* Simulation time owns the wheel. performance.now() kept moving while paused and made the same\n     encounter produce different lanes in headless runs, replays and slow frames. The Wardens\n     counter-rotate from the encounter clock instead. */\n  const rot=phase+(w.side==='L'?1:-1)*phase*1.85;\n  if((Math.floor(phase*2)&1)===0){\n    for(let i=0;i<10;i++){if(i===2||i===7)continue;eShootT(w.x,w.y+38,rot+i*TAU/10,2.75,'s9warp',{w:18,h:28,silent:i>0});}\n  }else{\n    const a=Number.isFinite(committedAim)?committedAim:Math.atan2(player.y-w.y,player.x-w.x);\n    for(let i=-2;i<=2;i++)eShootT(w.x,w.y+38,a+i*0.13,3.75,'s9needle',{w:8,h:34,silent:i>-2});\n  }\n  navalFlash(null,{x:w.x,y:w.y+38},.84,BPFX_MUZZLE_LASER,{n:8,hpx:52,life:.14,\n    follow:()=>w&&!w.disabled?{x:w.x,y:w.y+38}:null});\n}\nfunction s9FusionWardenWarningStart(owner,w,phase,key){\n  const radial=(Math.floor(phase*2)&1)===0;w._s9VolleyWarn={t:0,warm:.62,phase,radial,aim:radial?null:Math.atan2(player.y-w.y,player.x-w.x),key};\n  combatWarningTick(owner,key,0,.62,true);return w._s9VolleyWarn;\n}\nfunction s9FusionWardenWarningAngles(w){\n  const A=w&&w._s9VolleyWarn;if(!A)return [];if(!A.radial)return [-2,-1,0,1,2].map(i=>A.aim+i*.13);\n  const rot=A.phase+(w.side==='L'?1:-1)*A.phase*1.85,out=[];for(let i=0;i<10;i++)if(i!==2&&i!==7)out.push(rot+i*TAU/10);return out;\n}\nfunction s9FusionWardenWarningTick(owner,w,dt){\n  const A=w&&w._s9VolleyWarn;if(!A)return false;A.t+=dt;combatWarningTick(owner,A.key,Math.min(A.t,A.warm),A.warm);\n  if(A.t<A.warm)return false;s9FusionWardenFire(w,A.phase,A.aim);w._s9VolleyWarn=null;return true;\n}\nfunction s9FusionWardenWarningDraw(owner,w,front){\n  const A=w&&w._s9VolleyWarn;if(!A||w.disabled)return false;const p={x:w.x,y:w.y+38},k=clamp(A.t/A.warm,0,1),angles=s9FusionWardenWarningAngles(w);\n  if(!front)for(const a of angles)combatWarningDraw(owner,{x:p.x,y:p.y,ex:p.x+Math.cos(a)*650,ey:p.y+Math.sin(a)*650,progress:k,width:A.radial?15:18,fieldOnly:true});\n  else{const a=A.radial?Math.PI/2:A.aim;combatWarningDraw(owner,{x:p.x,y:p.y,ex:p.x+Math.cos(a)*650,ey:p.y+Math.sin(a)*650,progress:k,alertOnly:true});}\n  return true;\n}",
'queue committed stage9 volleys behind shared warnings');
one(
"    if(w._fire<=0){s9FusionWardenFire(w,F.t);w._fire=(w.hp<=w.maxhp*.5)?rnd(.58,.84):rnd(.76,1.08);}",
"    if(w._s9VolleyWarn){if(s9FusionWardenWarningTick(b,w,dt))w._fire=(w.hp<=w.maxhp*.5)?rnd(.58,.84):rnd(.76,1.08);}\n    else if(w._fire<=0)s9FusionWardenWarningStart(b,w,F.t,'stage9-event-horizon');",
'warn Event Horizon before release');
one("  ctx.save();ctx.translate(w.x,w.y);ctx.rotate(w.spin||0);ctx.globalAlpha=w.disabled?.58:1;","  s9FusionWardenWarningDraw(b,w,false);\n  ctx.save();ctx.translate(w.x,w.y);ctx.rotate(w.spin||0);ctx.globalAlpha=w.disabled?.58:1;",'Event Horizon fields behind hull');
one("  ctx.restore();\n  screenBar(function(){","  ctx.restore();\n  s9FusionWardenWarningDraw(b,w,true);\n  screenBar(function(){",'Event Horizon alert above hull');
one(
"      if(!b.enter&&!w.disabled){w._fire-=dt*DIFF.eFire;if(w._fire<=0){s9FusionWardenFire(w,F.t);w._fire=rnd(.68,.98);}}",
"      if(!b.enter&&!w.disabled){if(w._s9VolleyWarn){if(s9FusionWardenWarningTick(b,w,dt))w._fire=rnd(.68,.98);}\n        else{w._fire-=dt*DIFF.eFire;if(w._fire<=0)s9FusionWardenWarningStart(b,w,F.t,'stage9-warp-sentinel-'+w.side);}}",
'warn each Warp Sentinel independently');
one("  for(const w of [F.left,F.right]){\n    const ratio=","  for(const w of [F.left,F.right])s9FusionWardenWarningDraw(b,w,false);\n  for(const w of [F.left,F.right]){\n    const ratio=",'Sentinel fields behind pair');
one("  }\n  return true;\n}\n\nfunction shipBossInit", "  }\n  for(const w of [F.left,F.right])s9FusionWardenWarningDraw(b,w,true);\n  return true;\n}\n\nfunction shipBossInit",'Sentinel alerts above pair');
fs.writeFileSync(p,s,'utf8');console.log('PATCHED_STAGE9_HORIZON_SHARED_VOLLEY_WARNING_0915');
