"""Local review of actual game captures and generated source art."""
from pathlib import Path
import html,json
R=Path(__file__).resolve().parents[1];O=R/'_shots/herald_1003f'
cards=[]
for name,label in [('skulls-tell','Skull volley warning'),('lances-fire','Wing beam attack'),('salvo-fire','Skull salvo'),('cannon-hit','Independent cannon hit flash'),('cannon-broken','Cannon detached'),('wing-broken','Wing emitter destroyed'),('modular-destruction','Modular defeat')]:
 cards.append(f'<figure><a href="{name}.png" target="_blank"><img loading="lazy" src="{name}.png" alt="{label}"></a><figcaption>{label}</figcaption></figure>')
enemies=[]
for name,label in [('riflelocust','Rifle Locust'),('hellram','Hellram'),('hellhugger','Hellhugger'),('hexpyre','Hexpyre'),('impharrow','Imp Harrow'),('bluehybrid','Blue Hybrid'),('furnacemaw','Furnace Maw'),('stalker','Retina Stalker'),('prism','Code Prism'),('gravity','Gravity Orbiter')]:
 enemies.append(f'<figure><a href="../enemy_warnings_1003f/{name}-red.png" target="_blank"><img loading="lazy" src="../enemy_warnings_1003f/{name}-red.png" alt="{label}: original warning system"></a><figcaption>{label}</figcaption></figure>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Herald returns · Level 8</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0c10;color:#e8e5df;font:16px/1.5 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:26px}h1{font-size:clamp(30px,5vw,48px);margin:6px 0}h2{font-size:24px}p{max-width:850px;color:#c4c0b8}a{color:#ffae86}.eyebrow{color:#ff825e;font-size:13px;letter-spacing:2px}.actions{display:flex;flex-wrap:wrap;gap:12px;margin:22px 0}.actions a{padding:10px 16px;border:1px solid #865047;border-radius:4px;text-decoration:none;background:#211619}.hero{display:grid;grid-template-columns:1fr 1fr;gap:22px;align-items:start}video{width:100%;background:#000;max-height:78vh}aside{padding:20px;background:#17191f;border:1px solid #35343a}aside img{width:100%;max-height:370px;object-fit:contain}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}figure{margin:0;background:#17191f;border:1px solid #35343a}figure img{width:100%;display:block}figcaption{padding:10px;font-size:14px}.small{font-size:13px;color:#a8a9b1}section{margin-top:30px}button{font:inherit;background:#40221d;border:1px solid #c56c50;color:#fff;padding:9px;cursor:pointer}#arena{width:100%;height:850px;border:1px solid #423832;background:#000}#arena[hidden]{display:none}@media(max-width:740px){main{padding:14px}.hero{grid-template-columns:1fr}.grid{grid-template-columns:1fr 1fr}#arena{height:680px}}@media(max-width:440px){.grid{grid-template-columns:1fr}}</style><main>
<header><span class="eyebrow">LOCAL BUILD · OCTOBER 3F</span><h1>Herald of Death returns.</h1><p>Restored at Level 8's halfway point, with regenerated art and six independently animated components. Destroy a cannon to stop its volleys; tear off a wing to remove its beam. The skull is a weak point.</p><div class="actions"><a href="../../index.html?build=herald-1003f" target="_blank">Play updated build</a><a href="#warnings">Original enemy warnings</a><a href="../../assets/game/herald_1003f/parts.png" download>Download component sheet</a></div></header>
<div class="hero"><div><video controls preload="metadata" poster="skulls-tell.png" src="herald-motion.webm"></video><p class="small">Actual engine replay: Furious attacks, independent movement, cannon/wing breakage and defeat. Invulnerable pilot used for inspection.</p></div><aside><h2>Rebuilt as a real rig</h2><img src="../../assets/game/herald_1003f/parts.png" alt="Generated body, skull, wings and cannons"><p>Separate pivots, hit flashes, hit areas and Retina targets. Existing projectile art, explosions, sounds and original warning graphics remain in use.</p><p>The old Herald was stored in an alternate slot during the September 13 changes. Its campaign slot had been empty since then. This restoration keeps that archive and assigns the upgraded Herald to Level 8.</p><button id="launch">Try the miniboss · Furious</button><p class="small">Starts an isolated fight in the actual game. Uses your existing game controls.</p></aside></div>
<iframe id="arena" title="Herald of Death playable preview" hidden></iframe>
<section><h2>Attacks and breakage</h2><div class="grid">'''+''.join(cards)+'''</div></section>
<section id="warnings"><h2>Original warnings throughout Levels 7–8</h2><p>Every selected mutant and new alien now uses the shared green/yellow/red warning system. Ordinary enemies have the original straight attack bands; targeted strikes have the original Retina. Bosses retain the original FOV and alert art.</p><div class="grid">'''+''.join(enemies)+'''</div></section>
<section><p class="small">Native checks cover Normal and Furious enemy warnings and the Herald's spawn, attacks, targeting, weapon destruction and defeat on all four campaign difficulties. These are controlled encounter checks, not a full campaign clear or final balance rating.</p><p><a href="verification.json">Herald checks</a> · <a href="../enemy_warnings_1003f/verification.json">Enemy warning checks</a> · <a href="../../_ART_SOURCES/herald_1003f/generation.json">Built-in image-generation prompt</a></p></section></main><script>
const btn=document.querySelector('#launch'),frame=document.querySelector('#arena');btn.onclick=()=>{btn.disabled=true;btn.textContent='Loading…';frame.hidden=false;frame.src='../../index.html?build=herald-1003f-review';frame.onload=()=>{const w=frame.contentWindow;const t=setInterval(()=>{if(typeof w.beginStage!=='function'||!w.BOFDEBUG)return;try{w.eval('ht27Stop();debugFight=null;coopOn=false;diffKey="furious";DIFF=DIFFS.furious;run.pilot="yuri";run.mode="campaign";beginStage(8);setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;stagePlan=[];waveIdx=0;spawnClock=9999;enemies=[];eBullets=[];pBullets=[];powerups=[];stageTimer=curStage.length*.45;mapScroll=1202;boss=null;bossActive=false;subBossTriggered=true;subBossDone=false;warnT=0;warnKind=null;spawnSubBoss("heralddeath");player.x=worldWidth()/2;player.y=VH-105;camX=player.x-VW/2;Audio.startMusic("boss8");');clearInterval(t);btn.disabled=false;btn.textContent='Restart the miniboss · Furious';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){clearInterval(t);btn.disabled=false;btn.textContent='Retry miniboss preview';console.error(e);}},100);};};
</script></html>'''
(O/'review.html').write_text(page,encoding='utf-8');print(O/'review.html')
