"""Build local review from actual Chromium captures, not mock game renders."""
from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];O=R/'_shots/codewall_1003d'
shots=[('blue-wall','Chrome binary wall','Horizontal authored rows scroll in alternating directions inside the frame.'),
 ('blue-hit','Independent hit flash','The digits continue moving while a separate blue-white impact plays.'),
 ('blue-shatter','Outward code shatter','Twenty-four small code tiles fly into every direction around a compact burst.'),
 ('red-shield','Knight shield projection','Ruby code follows the physical shield’s position, rotation and destruction.'),
 ('red-hit','Red contact flash','A separate red-white impact leaves the code rows moving.'),
 ('red-shatter','Red projection breaks','The physical shield survives until its own module is destroyed.'),
 ('reconstruction-out','Dismantle scan','Tall chrome-blue scan rails replace the old spherical transformation.'),
 ('reconstruction-in','Rebuild scan','The incoming modular form stays visible as the data sweep completes.')]
cards=''.join(f'<article><a href="{name}.png"><img src="{name}.png" loading="lazy" alt="{html.escape(title)} in the real game"></a><div><h2>{title}</h2><p>{body}</p></div></article>' for name,title,body in shots)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Code wall · October 3</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080c15;color:#e1eafb;font:16px/1.55 system-ui,sans-serif}main{max-width:1160px;margin:0 auto;padding:48px 24px}header{border-bottom:1px solid #284264;padding-bottom:32px;margin-bottom:32px}.eyebrow{color:#77b5ff;letter-spacing:.18em;font-size:12px;text-transform:uppercase}h1{font-size:clamp(30px,5vw,52px);margin:8px 0;line-height:1.14}h2{font-size:18px;margin:0 0 7px}p{color:#aabbd4;margin:10px 0}nav{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0 0}a{color:#9fcaff}nav a{padding:10px 18px;border:1px solid #4773a5;border-radius:5px;text-decoration:none;background:#15243c}.proof{color:#8fd8ba}.film{background:#101927;padding:20px;border:1px solid #263e5e;border-radius:10px;margin-bottom:30px}video{display:block;width:min(100%,640px);max-height:76vh;margin:0 auto;background:#000}small{color:#93a4be}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}article{background:#0f1828;border:1px solid #233d5d;border-radius:8px;overflow:hidden}article img{display:block;width:100%;image-rendering:pixelated}article div{padding:18px}footer{margin-top:30px;border-top:1px solid #263b58;padding-top:22px;font-size:13px}@media(max-width:680px){main{padding:28px 14px}.grid{grid-template-columns:1fr}}</style>
<main><header><div class="eyebrow">Bullets of Fury / Stage 8 / 1003d</div><h1>Chrome code. Red shield.<br>Clean reconstruction.</h1><p>New generated 16-bit art, wired into the modular finale.</p><nav><a href="../../index.html?build=d69cffa4-codewall-1003d">Play updated build</a><a href="#motion">Watch motion</a><a href="verification.json">Native verification</a></nav><p class="proof">6,917 assertions · 147 Chromium checks · zero browser errors</p></header>
<section id="motion" class="film"><h2>In-game animation recording</h2><p>Scrolling, repeated hits, two shield breaks, sword movement and four form transitions.</p><video controls loop playsinline preload="metadata" poster="red-shield.png" src="codewall-motion.webm"></video><p><small>Captured from the game renderer. Guard poses are held longer in this inspection recording so you can see the code and impacts clearly; gameplay timing remains controlled by the encounter.</small></p></section>
<section class="grid">'''+cards+'''</section><footer>Generated with built-in image_gen. <a href="../../assets/game/levels/stage_08/effects/codewall_1003d/manifest.json">Saved asset manifest</a> · <a href="../../_ART_SOURCES/codewall_1003d/prompts.json">Exact generation prompts</a> · <a href="../../docs/CODEWALL_1003D.md">Implementation and verification notes</a></footer></main></html>'''
(O/'review.html').write_text(page,encoding='utf-8');print(O/'review.html')
