"""Create the encounter review using native screenshots and the current runtime."""
from pathlib import Path
import json,html,hashlib,re
R=Path(__file__).resolve().parents[1];O=R/'_shots/campaign_focus_1004b'
cards=[('Rebel Fury · the complete wing','rebel-five-versus-five.png','Player plus four allies. Furious allows two staggered specialists to coordinate fire.'),
 ('A defeated pilot leaves the HUD','rebel-death-no-bar.png','The burning ship and final portrait remain cinematic; its health bar is removed.'),
 ('The escaped Harrier at Stage X','map-focused-right.png','The unchosen encounter moves to the central city. Available after the Rebel route.'),
 ('Rebel Fury at Stage X','map-focused-left.png','The entire five-pilot encounter waits here after choosing the Harrier route.'),
 ('The Vile Colossus','dracula-combat.png','Independent arm swipes, an inward crush, flanking projectiles and an orbiting pull.'),
 ('Knight · windup','knight-coil.png','Generated torso and folded legs attach at measured joints; the original head and weapons stay separate.'),
 ('Knight · airborne strike','knight-airborne.png','Hammer’s actual warning, leap, impact and recovery states drive the pose.'),
 ('Knight · returning blade','knight-sword-throw.png','The visible sword follows the live throw collision and returns to its hand.'),
 ('Knight · heavy arsenal','knight-chaingun.png','The borrowed gun attack now has its own visible attachment and muzzle flashes.'),
 ('Knight · charged ground attack','knight-storm.png','Source shockwaves, original targeting graphics and visible rising hazards.'),
 ('Direct portal arrival','stage8-portal-arrival.png','Stage 7 hands off to Stage 8 in-engine, preserving equipment, lives, score and rank.')]
figs=''.join(f'<figure><a href="{s}" target="_blank"><img src="{s}" loading="lazy" alt="{html.escape(t)}"></a><figcaption><strong>{html.escape(t)}</strong><p>{html.escape(n)}</p></figcaption></figure>' for t,s,n in cards)
template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stage 6 + 8 · Bullets of Fury</title>
<style>*{box-sizing:border-box}body{margin:0;background:#080c16;color:#eef3fa;font:16px/1.5 system-ui}main{max-width:1380px;margin:auto;padding:32px 24px 72px}h1{font-size:clamp(34px,5vw,60px);line-height:1.05;margin:12px 0 20px}h2{margin-top:40px}p{color:#b7c7da;max-width:1000px}.tag{font-size:12px;letter-spacing:.2em;color:#ffa469}.actions{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}button,select{font:inherit;padding:11px 14px;border:1px solid #446182;border-radius:6px;color:#f3f7fd;background:#152a42;cursor:pointer}button:hover{background:#244a6c}button:focus-visible{outline:3px solid #ffc280}#status{min-height:26px}iframe{border:1px solid #446182;width:100%;height:min(940px,92vh);background:#000}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}figure{margin:0;background:#111c2d;border:1px solid #2b415a;border-radius:9px;overflow:hidden}img{display:block;width:100%;max-height:670px;object-fit:contain;background:#020409;image-rendering:pixelated}figcaption{padding:18px}figcaption p{margin:7px 0 0}.music{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.music article{padding:18px;background:#111c2d;border:1px solid #2b415a;border-radius:8px}audio{width:100%;margin-top:12px}a{color:#85dcff}small{color:#b7c7da}.note{padding:16px 20px;background:#142335;border-left:3px solid #6ec8ec}footer{margin-top:36px}@media(max-width:760px){main{padding:22px 12px}.grid,.music{grid-template-columns:1fr}}</style>
<main><header><div class="tag">BULLETS OF FURY · OCTOBER 4 FOLLOW-UP</div><h1>Full wing. Final confrontation.</h1><p>Stage 6’s missing allies and dead health bars are corrected. The remaining encounter moves to Stage X. Dracula’s articulated attacks and the knight’s generated poses are wired into the finale.</p><a href="../../index.html?build=campaign-focus-1004b" target="_blank">Open the updated game</a> · <a href="../../docs/CAMPAIGN_FOCUS_1004B.md">Change notes</a> · <a href="../../docs/qa/campaign_focus_1004b.json">Verification</a></header>
<h2>Play the changes</h2><p>Practice shortcuts use the current game and your controls. Save writes are disabled inside these previews.</p>
<div class="actions"><select id="difficulty" aria-label="Difficulty"><option value="normal">Normal</option><option value="hard">Hard</option><option value="furious" selected>Furious</option></select><select id="pilot" aria-label="Pilot">PILOTS</select></div>
<div class="actions"><button data-mode="rebels">Rebel fight</button><button data-mode="gang">Gang Mode</button><button data-mode="finale">Full Stage 8 finale</button><button data-mode="dracula">Dracula entrance</button><button data-mode="knight">Powered knight</button><button data-mode="harrier-map">Stage X / Harrier map</button><button data-mode="rebels-map">Stage X / Rebels map</button><button data-mode="portal">Portal into Stage 8</button></div>
<p id="status" role="status">Choose a practice encounter.</p><iframe id="arena" title="Playable encounter practice" hidden allow="autoplay"></iframe>
<h2>The three fight tracks</h2><div class="music"><article><strong>1 · Mutated drone</strong><p>Previously the second fight’s track.</p><audio controls preload="metadata" src="../../assets/game/music/Level8b.mp3"></audio></article><article><strong>2 · Ghost in the code</strong><p>Previously the final fight’s track.</p><audio controls preload="metadata" src="../../assets/game/music/Level8b2.mp3"></audio></article><article><strong>3 · Dracula + transformations</strong><p>Your new Final Form recording.</p><audio controls preload="metadata" src="../../assets/game/music/Level8b3.mp3"></audio></article></div>
<p class="note">Stage 6 awards Prism energy. Stage 8 awards Dark Matter. Stage 7 continues directly through the portal into Stage 8, with its earned results recorded in the background.</p>
<h2>From the running game</h2><div class="grid">CARDS</div><footer><small>The new 15:15 recording was inspected across its entire timeline at two-second intervals. Controlled Chromium checks verify rendering, attacks, routes and transitions; they are not a full human campaign clear or a final difficulty verdict. Changes remain local.</small></footer></main>
<script>
const frame=document.querySelector('#arena'),status=document.querySelector('#status');let timer;
document.querySelectorAll('audio').forEach(a=>a.onplay=()=>document.querySelectorAll('audio').forEach(b=>{if(a!==b)b.pause()}));
document.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{clearInterval(timer);document.querySelectorAll('audio').forEach(a=>a.pause());const mode=btn.dataset.mode,diff=document.querySelector('#difficulty').value,pilot=document.querySelector('#pilot').value;status.textContent='Loading practice…';frame.hidden=false;
 frame.onload=()=>{let tries=0;timer=setInterval(()=>{const w=frame.contentWindow;if(++tries>900){clearInterval(timer);status.textContent='Loading took too long. Select the encounter to retry.';return;}if(!w.BOFDEBUG||typeof w.cf4PortalHandoff!=='function')return;
 try{w.Storage.prototype.setItem=function(){};w.Storage.prototype.removeItem=function(){};
 const stage=['finale','dracula','knight'].includes(mode)?8:mode==='portal'?7:6;
 w.eval('ht27Stop();debugFight=null;coopOn=false;diffKey='+JSON.stringify(diff)+';DIFF=DIFFS[diffKey];run.pilot='+JSON.stringify(pilot)+';run.mode="campaign";run.lives=9;beginStage('+stage+');setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;fb2Talk=null;special=null;thunderStorm=null;s6Opening=null;s6Wing=null;stagePlan=[];spawnClock=9999;waveIdx=999;enemies=[];eBullets=[];pBullets=[];powerups=[];boss=null;bossActive=false;subBoss=null;subBossActive=false;subBossDone=true;stageTimer=0;player.x=worldWidth()/2;player.y=VH-130;camX=player.x-VW/2;player.invuln=4;run.weapon=7;run.wlevel=4;run.wlevels[7]=4;run.bombs=12;groundTargetingReset();Audio.init();Audio.resume();');
 if(mode==='rebels'||mode==='gang'){
  w.eval('s6WingInit();s6WingLaunch(8,true);Object.assign(s6Wing,{all:true,route:"right",beats:3,fakeDone:true,supplyIndex:3});spawnBoss("rebelsquad");boss._be=null;rf28Init(boss,boss._rebels);boss._rebels.frIntro={done:true};boss.enter=false;boss._noHit=false;boss._rebels.ships.forEach(q=>{q.mode="fight";q.warp=0;q.x=worldWidth()/2+(q.i-2)*70;q.y=125+(q.i%2)*35;});rg4Init(boss);H3.release=false;Audio.startMusic("stagex");');
  if(mode==='gang')w.eval('boss._rebels.ships.slice(0,3).forEach(q=>q.hp=q.max*.49);rg4Threshold(boss,boss._rebels.gang1004);');
 }else if(stage===8){w.eval('r30Warm();spawnBoss("vileexistence");boss._be=null;');
  if(mode!=='finale')w.eval('j3Encounter(boss,2);bossPhaseMusic(8,3);');
  if(mode==='knight')w.eval('j3Mimic(boss,5);boss._r30.mode="fight";boss.enter=false;gd4Create(boss,5);');
 }else if(mode==='portal')w.eval('cf4PortalHandoff({bonus:0,rank:"A"});');
 else w.eval('campaign.unlockedMax=7;s6WingInit();s6Wing.route='+JSON.stringify(mode==='harrier-map'?'right':'left')+';scLeaveStage({bonus:0,rank:"A"});');
 clearInterval(timer);status.textContent=btn.textContent+' ready. Click the game to play.';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});
 }catch(e){clearInterval(timer);status.textContent='Practice could not start. Select it to retry.';console.error(e);}},100);};frame.src='../../index.html?build=campaign-focus-1004b-practice';});
</script></html>'''
pilots=''.join(f'<option value="{p}"'+(' selected' if p=='yuri' else '')+f'>{p.title()}</option>' for p in ['axel','decker','maverick','freezer','juggernaut','yuri','lizzie','falva','cole'])
(O/'review.html').write_text(template.replace('PILOTS',pilots).replace('CARDS',figs),encoding='utf-8')
print(O/'review.html')
