"""Build the local review from actual Chromium captures, never substitute art."""
from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];O=R/'_shots/finale_modular_1003c'
report=json.loads((O/'verification.json').read_text(encoding='utf-8'))
names=['Orbital Host','Hive Helicopter','Alien Furnace','Cryo Hive','Storm Organism','Null Knight','Void Harrier','Last Warden']
attacks=['talons','rotorMG','magma','iceLance','lightning','knight','carrierLance','wardenMG']
cards=[]
for i,(name,attack) in enumerate(zip(names,attacks),1):
 parts=', '.join(v['id'] for v in report['forms'][i-1]['parts'])
 cards.append(f'''<article id="form-{i}"><h2>{i:02} · {name}</h2><p>{html.escape(parts)}</p><div class="tabs"><button data-shot="form-{i}-idle.png" class="on">Intact rig</button><button data-shot="form-{i}-{attack}-charge.png">Charge / aiming</button><button data-shot="form-{i}-broken.png">Component broken</button></div><a href="form-{i}-idle.png" target="_blank"><img src="form-{i}-idle.png" alt="{name} rendered in the actual game" loading="lazy"></a></article>''')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Modular alien finale · October 3</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0f16;color:#e2eaf5;font:16px/1.5 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:26px}a{color:#72dcff}header{border-bottom:1px solid #384556;margin-bottom:24px;padding-bottom:22px}h1{font-size:clamp(28px,4vw,44px);line-height:1.12;margin:10px 0}h2{font-size:20px;margin:8px 0}p{max-width:850px;color:#b1bdd1}.status{color:#a6f097}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}article{border:1px solid #384556;background:#121925;border-radius:8px;padding:14px;overflow:hidden}article p{font-size:13px;min-height:40px;margin:6px 0}article img{width:100%;display:block}.tabs{display:flex;gap:5px;flex-wrap:wrap;margin:12px 0}button{font:inherit;color:#c9d5e8;border:1px solid #4a5e74;background:#152236;border-radius:4px;padding:7px 9px;cursor:pointer}button.on{background:#17465a;border-color:#67d9ff;color:#fff}video{max-width:640px;width:100%;max-height:80vh;background:#000;display:block}.replay{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin:24px 0}.head{width:100%;max-width:320px;max-height:240px;object-fit:contain;background:#17202b}.note{font-size:14px}.fills{display:flex;gap:6px;flex-wrap:wrap;margin:15px 0}.fills a{border:1px solid #4a5e74;padding:6px 12px;text-decoration:none}@media(max-width:720px){.grid,.replay{grid-template-columns:1fr}main{padding:14px}}</style><main>
<header><span class="status">LOCAL BUILD · MODULAR FINALE 1003C</span><h1>Eight forms. One refilling gauge.</h1><p>Independent authored components now drive each form's weapons, recoil, targeting and breakage. The knight uses the corrected head-only asset, articulated arms, separate sword and shield, and a charged blade with matching collision.</p><a href="../../index.html?build=d69cffa4-modular-finale-1003c" target="_blank">Play the updated build →</a></header>
<section class="replay"><div><h2>Actual engine replay</h2><video controls preload="metadata" poster="knight-head-and-powered-sword.png" src="modular-finale-motion.webm"></video></div><div><h2>Head-only correction</h2><img class="head" src="../../assets/game/finale_modular_1003c/head.png" alt="Corrected alien knight head, without chest or shoulders"><p>The discarded head/chest piece is replaced. The neck attaches to the torso; the sword follows its hand through wind-up, downward strike, horizontal follow-up and recovery.</p><h2>Health display</h2><p>The same bar fills eight successive times in eight colors. During combat, it shows the active form's actual health and color.</p><div class="fills">'''+''.join(f'<a href="fill-{i}.png" target="_blank">Fill {i}</a>' for i in range(1,9))+'''</div><p class="note">Controlled Chromium encounters with an invulnerable pilot. These verify rendering and mechanics; they are not a campaign clear or a final difficulty rating.</p></div></section>
<section class="grid">'''+''.join(cards)+'''</section><p class="status">122 Chromium checks passed · zero page/console errors</p><p><a href="verification.json">Verification evidence</a> · <a href="../../_ART_SOURCES/finale_modular_1003c/prompts.json">Built-in image-generation prompts</a> · <a href="../../_ART_SOURCES/finale_modular_1003c/corrections.json">Head and Storm hull corrections</a></p></main><script>document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{const card=b.closest('article');card.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));card.querySelector('img').src=b.dataset.shot;card.querySelector('a').href=b.dataset.shot;});</script></html>'''
(O/'review.html').write_text(page,encoding='utf-8');print(O/'review.html')
