"""Local combat review: actual engine captures, playable encounter, generated audio."""
from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];O=R/'_shots/combat_1003i'
audio=json.loads((R/'assets/game/shared/combat/combat_1003i/audio-masters.json').read_text())
cards=[('reaver-normal-tell','Original warning art, animated modules'),('reaver-furious-beam','Live gun pivots and attached beam muzzles'),('reaver-furious-disarmed','Destroyed cannon removed from firing and locks'),('beam-warhive','Deployed Warhive cannon: tapered beam'),('beam-carrier','Carrier cannon'),('beam-tempest','Tempest beam')]
gallery=''.join(f'<figure><a href="{n}.png"><img loading="lazy" src="{n}.png" alt="{label}"></a><figcaption>{label}</figcaption></figure>' for n,label in cards)
sounds=''.join(f'<div class="sample"><label for="s{i}">{html.escape(q["name"].replace("_"," ").title())}</label><audio id="s{i}" controls preload="none" src="../../{q["file"]}"></audio><small>{q["seconds"]:.2f} seconds'+(' · sustained loop' if q['loop'] else '')+'</small></div>' for i,q in enumerate(audio))
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Combat feedback · Bullets of Fury</title><style>
*{box-sizing:border-box}body{margin:0;background:#080f19;color:#edf4ff;font:16px/1.55 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:32px 24px 70px}h1{font-size:clamp(30px,4vw,48px);line-height:1.15;margin:10px 0}h2{margin-top:36px}p{color:#b8c9da;max-width:850px}a{color:#8fddff}.eyebrow{font-size:12px;letter-spacing:2px;color:#ffb14f}.hero{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:start}.hero img{display:block;width:100%;image-rendering:pixelated}.panel{padding:22px;background:#101e2d;border:1px solid #2b4155;border-radius:8px}.panel img{margin-top:16px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}figure{margin:0;border:1px solid #2b4155;background:#101e2d}figure img{display:block;width:100%}figcaption{padding:12px;font-size:14px}.samples{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.sample{background:#101e2d;border:1px solid #2b4155;padding:14px}.sample label{display:block;margin-bottom:12px;font-weight:600}audio{width:100%;height:36px}small{display:block;color:#9db4c9;font-size:12px;margin-top:6px}button,select{font:inherit;padding:10px 15px;border:1px solid #b77434;background:#3a2618;color:#fff;border-radius:5px;cursor:pointer}button:hover{background:#614021}#arena{width:100%;height:850px;border:1px solid #2b4155;margin-top:20px}#arena[hidden]{display:none}.links{display:flex;gap:20px;flex-wrap:wrap;margin:24px 0}.swatches{width:100%;max-height:600px;object-fit:contain;background:#09131e}@media(max-width:850px){.hero{grid-template-columns:1fr}.grid,.samples{grid-template-columns:1fr 1fr}main{padding:20px 14px}#arena{height:700px}}@media(max-width:480px){.grid,.samples{grid-template-columns:1fr}}</style>
<main><div class="eyebrow">BULLETS OF FURY · LOCAL COMBAT PASS</div><h1>Break the guns. Hear the fight.</h1>
<p>The Stage 2 Inferno Reaver has six separate components. New animated laser strips and muzzle flashes connect to boss weapons, with twenty generated combat sounds covering the missing effects.</p>
<div class="links"><a href="../../index.html?build=combat-1003i" target="_blank">Play updated build</a><a href="#sounds">Preview the sounds</a><a href="report.json">Combat verification</a><a href="sound-roster.json">Sound verification</a></div>
<div class="hero"><img src="reaver-furious-beam.png" alt="Modular Inferno Reaver firing its twin molten lasers"><div class="panel"><h2 style="margin-top:0">Inferno Reaver</h2><p>Articulated wings and aiming cannons, individual hit flashes, accurate part collisions and missile targets. Destroying a weapon stops its attacks.</p><p>The encounter keeps its existing attack timing and original warnings.</p><label for="difficulty">Difficulty </label><select id="difficulty"><option value="normal">Normal</option><option value="furious" selected>Furious</option></select> <button id="launch">Fight the Reaver</button><small>Isolated encounter using your existing game controls. Restart here to try again.</small><img src="../../assets/game/shared/combat/combat_1003i/reaver_parts.png" alt="Six generated Reaver components"></div></div>
<iframe id="arena" title="Playable Inferno Reaver encounter" hidden></iframe>
<h2>Laser beams and muzzle flashes</h2><p>Three animation frames per color: molten orange, cyan, toxic green, violet, red and gold. The original warning lanes remain in place.</p><img class="swatches" src="laser-contact-sheet.png" alt="Six animated laser color families captured from the game renderer">
<h2>In-game views</h2><div class="grid">'''+gallery+'''</div>
<h2 id="sounds">The sound pass</h2><p>Boss charge and release, sustained beams, Fusion cannon, Cole VI/VII, firewall arrival and burn, targeting, teleports, alien attacks, impacts, code shatter and module breakage. Existing attack recordings stay in use where they already fit.</p><div class="samples">'''+sounds+'''</div>
<p><small>Native Chromium checks cover the modular encounter, laser renderers, Level 6–8 attack and impact routes, actual mixer playback and the eight-form finale. These are controlled encounter checks, not a full campaign clear or a final balance rating.</small></p></main>
<script>
document.querySelectorAll('audio').forEach(a=>a.addEventListener('play',()=>document.querySelectorAll('audio').forEach(b=>{if(a!==b)b.pause()})));
const btn=document.querySelector('#launch'),frame=document.querySelector('#arena');btn.onclick=()=>{btn.disabled=true;btn.textContent='Loading…';frame.hidden=false;frame.src='../../index.html?build=combat-1003i-review';frame.onload=()=>{const w=frame.contentWindow,t=setInterval(()=>{if(typeof w.beginStage!=='function'||!w.BOFDEBUG)return;try{const diff=document.querySelector('#difficulty').value;w.eval('ht27Stop();debugFight=null;coopOn=false;diffKey='+JSON.stringify(diff)+';DIFF=DIFFS[diffKey];run.pilot="yuri";run.mode="campaign";beginStage(2);setState(GS.PLAY);player.reset();BOFCinematicDirector.cancel();story=null;stagePlan=[];waveIdx=0;spawnClock=9999;enemies=[];eBullets=[];pBullets=[];powerups=[];stageTimer=curStage.length*.45;boss=null;bossActive=false;subBossTriggered=true;subBossDone=false;warnT=0;warnKind=null;spawnSubBoss("magmaward");player.x=worldWidth()/2;player.y=VH-105;camX=player.x-VW/2;Audio.startMusic("mini2");');clearInterval(t);btn.disabled=false;btn.textContent='Restart the Reaver';frame.focus();frame.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){clearInterval(t);btn.disabled=false;btn.textContent='Retry encounter';console.error(e);}},100);};};
</script></html>'''
(O/'review.html').write_text(page,encoding='utf-8');print(O/'review.html')
