module.exports=function testUnlockAnnouncements(vm,ctxv,ok){
  console.log('=== 361. WEAPON FOUND - authored four-row announcement plate (0918) ===');
  const R=js=>vm.runInContext(js,ctxv);
  const bd=R('bossDie.toString()').replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g,'');
  ok(/run\.stage===4[^;]*yuriLightningOrbGrantStage4/.test(bd),'the Lightning Orb is granted on the stage-4 boss kill');
  ok(/run\.stage===9[^;]*laserMistUnlock/.test(bd),'Laser Mist is granted on the stage-9 boss kill');
  ok(/run\.stage===5[^;]*chaingunUnlock/.test(bd),'the Chaingun is granted on the stage-5 hammer kill');
  const rows=(n,pk)=>R('JSON.stringify(unlockRowsFor('+n+',"'+pk+'"))');
  ok(rows(4,'yuri').includes('LIGHTNING ORB')&&rows(4,'cole')==='[]','the stage-4 page announces Lightning Orb only to Yuri');
  ok(rows(2,'freezer').includes('ICE BREATH')&&rows(2,'freezer').includes('THERMOSHOCK'),'Freezer receives both stage-2 weapon announcements');
  ok(rows(5,'cole').includes('CHAINGUN')&&rows(9,'cole').includes('LASER MIST'),'stages 5 and 9 announce their actual weapon systems');
  ok(rows(3,'cole')==='[]','a stage with no weapon grant skips the page');
  ok(R("XART._src.weapon_found_0918==='assets/game/ui/forge_0918/weapon_found.png'"),'the dedicated generated Weapon Found plate is registered');
  const us=R('unlocksStart.toString()'),du=R('drawUnlocks.toString()');
  ok(us.includes("XART.rdy('weapon_found_0918')"),'the screen warms its plate before entering');
  ok(du.includes("XART.rdy('weapon_found_0918')")&&du.includes('ctx.drawImage(plate'),'the screen draws the authored full-frame plate');
  ok(R('UNLOCK_VIEW===4&&UNLOCK_MAX>=UNLOCK_VIEW'),'exactly four rows are visible and larger sets scroll');
  ok(du.includes('U.scroll+k')&&du.includes('maxS'),'rows read from the scroll offset');
  ok((du.match(/Input\.menuUp/g)||[]).length===2&&(du.match(/Input\.menuDown/g)||[]).length===2,'up and down are each read once through their availability check and call');
  ok(du.indexOf('const up=')<du.indexOf('if(dn)'),'both consuming inputs are captured before either is acted on');
  ok(du.includes("full.slice(0")&&du.includes('tx+tw/2'),'weapon names type in while remaining centered in their long wells');
  ok(du.includes('unlockTint(row[1])'),'each weapon name uses its own element color');
  const tint=k=>R("unlockTint('"+k+"')");
  ok(tint('micon_chaingun_3')==='#ff9a3a','bullet weapons use orange text');
  ok(tint('micon_lightningorb_3')==='#ffe03a','lightning uses yellow text');
  ok(tint('micon_lasermist_3')==='#3fe3ff','Laser Mist uses aqua text');
  ok(tint('micon_icebreath_3')==='#9fdcff','ice uses ice-blue text');
  ok(tint('micon_fireorb_3')==='#ff3b2a','fire uses neon-red text');
  ok(tint('micon_thermoshock_3')==='#c07cff','Thermoshock uses the fire/ice violet mix');
  ok(/micon_lasermist[\s\S]{0,120}laserMistAtlasBlit/.test(R('iconBlit.toString()'))&&/laserMistWarm/.test(us),'Laser Mist warms and draws from its own atlas');
};
