const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..'),js=fs.readFileSync(path.join(root,'assets/game.js'),'utf8');
const ok=(v,m)=>{assert(v,m);console.log('ok',m)};
ok(/function pickupAnnounce\([^)]*\)[\s\S]*arcadeBanner/.test(js),'pickup acquisition uses the graphical arcade banner');
ok(/turn_furybomb_0918/.test(js)&&/turn_inf_/.test(js)&&/function pickupTurnFrame/.test(js),'authored pickup turn strips are wired');
ok(!/cheap pulsing glow/.test(js),'bomb and score pickup additive disc path is removed');
ok(/bmbar_frame_shield_v2/.test(js)&&/fx=x\+w\*\.067/.test(js),'rectangular shield plate owns a straight fill well');
ok(/lagKey/.test(js)&&/'razorback'\+i/.test(js),'Razorback Duo bars retain independent lag state');
ok(!/if\(R\.state==='turret'\) rzbFlash/.test(js),'Razorback center turret flashes before its turret-only phase');
ok(/edgeMin:10,edgeMax:42/.test(js)&&/y:\(y!=null\?y:VH\+2\)/.test(js),'Stage 2 vents are confined to bottom-fed lava edge gutters');
ok(/s2GeyserWarn/.test(js)&&/s2GeyserErupt/.test(js)&&/firewallPass/.test(js),'fire hazard warning, eruption and pass cues are routed');
ok(/function fztTurnDraw/.test(js)&&/fztTurnDraw\(key,x,y,a,s,alpha,sx,sy,false\)/.test(js),'Furnace body and arms choose authored direction frames');
for(const f of ['assets/game/ui/bossbar_0918/shield_frame_v2.png','assets/game/sounds/s2_geyser_warn_0918.wav','assets/game/sounds/s2_geyser_erupt_0918.wav','assets/game/rotation_frames_0918/fzt_arm_flame_intact_turn.png'])ok(fs.statSync(path.join(root,f)).size>1000,f+' exists');
