module.exports=function(vm,ctxv,ok){
 const fs=require('fs'),path=require('path');
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/furious_review_0927.js'),'utf8'),ctxv,{filename:'furious_review_0927.js'});
 console.log('=== Furious playtest repairs: camera, controls, armor and routes ===');
 const result=JSON.parse(vm.runInContext(`JSON.stringify((()=>{
  const o={};ht27Stop();diffKey='furious';DIFF=DIFFS.furious;run.mode='arcade';run.pilot='yuri';coopOn=false;
  beginStage(4);setState(GS.PLAY);story=null;player.invuln=999;
  const save=ctx.save,restore=ctx.restore;let depth=0;
  ctx.save=function(){depth++;return save.apply(this,arguments);};ctx.restore=function(){depth--;return restore.apply(this,arguments);};
  const e={_modJet:'snow',_modJetAngles:{left:Math.PI/2,right:Math.PI/2},x:340,y:170,w:66,h:56,flash:.1};
  const ready=XART.rdy,get=XART.get;XART.rdy=()=>true;XART.get=()=>({width:128,height:128,naturalWidth:128,naturalHeight:128});
  drawModularJet(e);o['modular jet preserves canvas save stack including damage flash']=depth===0;
  ctx.save=save;ctx.restore=restore;XART.rdy=ready;XART.get=get;
  for(const k in Input.keys)Input.keys[k]=false;keybind.multilock=['y','pad_b3'];_seat=1;
  const savedDown=Input.down;Input.down=k=>!!Input.keys[k];Input.keys.c=true;o['holding C cannot start multi-lock']=!retinaScanHeld();Input.keys.c=false;Input.keys.y=true;o['Y starts the dedicated multi-lock action']=retinaScanHeld();Input.keys.y=false;Input.down=savedDown;
  o['Y gamepad binding no longer belongs to Retina']=KEYBIND_DEFAULT.multilock.includes('pad_b3')&&!KEYBIND_DEFAULT.retina.includes('pad_b3');
  beginStage(5);setState(GS.PLAY);spawnBoss(curStage.boss);bossActive=true;const b=boss,h=b._hammer;b._noHit=false;b.enter=false;h.balance0922=true;hammerState(b,'hammer');hammerBossTick(b,.016);
  const A=h.frArmor;o['Furious gains exactly one additional full health layer']=A.hp===b.maxhp&&A.max===b.maxhp&&h.state==='fr_activation';
  hammerBossTick(b,3.5);const hp=b.hp,ap=A.hp;const d=hammerBossDamage(b,100);b.hp-=d;
  o['armor takes damage before underlying HP']=A.hp===ap-100&&b.hp===hp;
  A.hp=A.max*.49;hammerState(b,'hammer');hammerBossTick(b,.016);o['half armor triggers protected restoration']=h.frRecovery&&h.recovery.armor&&A.barrier>0;
  A.hp=0;A.barrier=0;h.frRecovery=false;h.recovery=null;A.checkpoints=[.75,.50,.35];b.hp=b.maxhp*.14;hammerState(b,'hammer');hammerBossTick(b,.016);
  o['critical health starts front hammer twirl']=h.state==='fr_twirl';h._unused=0;b._hammerModuleHit='hammer';hammerBossDamage(b,h.hammerMax);o['shooting twirling hammer interrupts the final recovery']=h.state==='fr_stun';hammerBossTick(b,2.9);o['critical interruption releases red rage jumps']=A.rage&&h.state==='warn';
  b.hp=b.maxhp-1;fr27Restore(b,.1,false,false);hammerRecoveryTick(b,3);const actual=h.recovery.granted;hammerRecoveryBreak(b);o['interrupt only revokes HP actually granted']=actual<=1.001&&Math.abs(b.hp-(b.maxhp-1))<.001;
  b.hp=b.maxhp*.5;fr27Restore(b,.10,false,true);const heal=h.recovery,hammer=retinaBossTargets(b).find(t=>t._retinaId==='hammer');
  retinaMissileDamage(hammer,24,{kind:'gmiss',x:hammer.x,y:hammer.y});o['locked rocket interrupts healing even while the body barrier is up']=heal.status==='cancelled'&&h.state==='fr_stun';
  h.frRecovery=false;h.recovery=null;A.hp=100;A.barrier=3;hammerState(b,'hammer');b._hammerModuleHit=null;const previousBullet=_dmgBullet;_dmgBullet={kind:'gmiss'};hammerBossDamage(b,24);o['front-facing barrier still blocks body rockets']=A.hp===100;
  _dmgBullet={kind:'gmiss',_frHammerFlank:b};hammerBossDamage(b,24);o['rocket arriving around the wall damages the armor']=A.hp===76;_dmgBullet=previousBullet;
  ht27Pending=true;startRun(5);const secret=boss,D=secret._hammerTime;D.mode='attack';D.locked=false;D.shield=false;secret._noHit=false;hammerState(secret,'warn');hammerBossTick(secret,.01);hammerBossTick(secret,1.2);const activationT=secret._hammer.t;ht27LockStart(secret,D);
  o['soundtrack cue cannot reset an unfinished Chromium activation']=secret._hammer.state==='fr_activation'&&secret._hammer.t===activationT&&!D.locked;
  hammerBossTick(secret,2.3);o['password Chromium sequence reaches its complete armor state']=fr27Armor(secret).activated&&secret._hammer.state==='hammer';ht27Stop();
  beginStage(6);setState(GS.PLAY);story=null;s6Opening=null;s6Wing.choice=true;s6Wing.route=null;const t=stageTimer,x=player.x,y=player.y,scroll=mapScroll;for(let i=0;i<60;i++)updatePlay(1/60);
  o['route decision freezes simulation until confirmation']=stageTimer===t&&player.x===x&&player.y===y&&mapScroll===scroll;
  fr27ChooseRoute(s6Wing,'right');o['right decision is explicit and clears queued input']=s6Wing.autoRoute==='right';
  s6Wing.choice=false;s6Wing.route='right';spawnBoss('rebelsquad');bossActive=true;rebelSquadTick(boss,.1);o['rebel cinematic protects ships and hides the common boss bar']=boss._noHit&&!bossHealthVisible(boss)&&retinaBossTargets(boss).length===0;
  rebelSquadTick(boss,30);o['fight exposes five ships and ten independently targetable modules']=retinaBossTargets(boss).length===15;
  const q=boss._rebels.ships[0],m=fr27RebelModules(q)[0];boss._rebels.hit=0;boss._rebels.frHit='left';rebelSquadDamage(boss,m.hp);o['module destruction removes only its own target']=m.hp===0&&!q.dead&&retinaBossTargets(boss).length===14;
  beginStage(8);o['alien stage always enters through the portal, not a fly-in']=state===GS.WARPENTRY&&l78entry!=null&&run._l78Entry===1;
  beginStage(6);setState(GS.PLAY);s6Opening=null;s6Wing.choice=false;s6Wing.route='left';spawnBoss('warhive');bossActive=true;warhiveTick(boss,2.7);const carrier=boss,W=carrier._whv,oldHP=carrier.hp;_lastHitX=W.cx;_lastHitY=W.cy-38;bossHitTest(_lastHitX,_lastHitY);hitBoss(120);
  o['Harrier hull takes the exact damage shown by its boss bar']=oldHP-carrier.hp===120&&bossHealthVisible(carrier)&&retinaBossTargets(carrier).some(t=>t._retinaId==='hull');
  W.core=0;warhiveTick(carrier,.01);warhiveTick(carrier,4.5);o['Harrier destruction still releases its independently scaled Ace']=W.mode==='ace'&&carrier.maxhp===W.aceMax;
  spawnSubBoss('siegebomber');o['Stage 6 miniboss final HP reduction survives all shared floors']=subBoss.maxhp>=subBoss._bomber.frOriginalHp*.58&&subBoss.maxhp<=subBoss._bomber.frOriginalHp*.58+5&&subBoss.hp===subBoss._bomber.core+subBoss._bomber.parts.reduce((sum,p)=>sum+p.hp,0);
  beginStage(8);o['Alien realm supplies a valid scrolling master before its image decodes']=levelScrollRange()===4096&&_levelCfg().continuousBoss&&curStage.music==='realm8';
  const firstScroll=mapScroll;const oldReady=XART.rdy;XART.rdy=()=>false;drawBG(1);XART.rdy=oldReady;o['Alien terrain advances the encounter clock exactly once']=mapScroll-firstScroll===40&&run._frRealmScroll===78;
  spawnBoss('vileexistence');bossActive=true;boss._symEntry=null;boss.enter=false;vile24Attack(boss);const startShots=eBullets.length;vile24Tick(boss,1.2);o['Mutated vessel releases binary ordnance from live cannon modules']=boss.name==='MUTATED DATA VESSEL'&&eBullets.slice(startShots).filter(q=>q._frRealm===0).length===10;
  beginStage(7);setState(GS.PLAY);spawnBoss('sludgeemperor');bossActive=true;const sewer=boss,M=s7mInit(sewer);M.mode='dead';fr27Exit(sewer,.1);const originalY=sewer.y;fr27Exit(sewer,10);o['Toxic boss wreck stays anchored as the sewer scrolls beneath the escape']=sewer.y-originalY===M.frExit.travel&&M.height===0&&M.lean===0;
  o['Toxic escape uses green authored explosions']=explosions.some(q=>q._frToxic&&BOSS_COMBO.includes(q.xb));fr27Exit(sewer,7.3);o['Exit course reaches the centered portal before the pilot disappears']=Math.abs(player.x-worldWidth()/2)<.001&&Math.abs(player.y-M.frExit.portalY)<.001&&sewer._s7warden.final.shipHidden;
  return o;
 })())`,ctxv));
 for(const [label,passed]of Object.entries(result))ok(passed,label);
};
