module.exports=function(vm,ctxv,ok){
  const fs=require('fs'),path=require('path');
  console.log('=== 306. Shared weapon muzzle releases and Stage 5 music ===');
  vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/weapon_muzzles_0926.js'),'utf8'),ctxv);
  const result=JSON.parse(vm.runInContext(`(()=>{
    const out={};wm26Releases=[];run.stage=1;
    const actor={x:180,y:260,dead:false},other={x:360,y:260,dead:false};
    const f=wm26Emit(actor,182,245,-Math.PI/2,'mg','#77ee22',{player:true});
    wm26Emit(actor,182,245,-Math.PI/2,'mg','#77ee22',{player:true});
    out['fan pellets share one flash per barrel']=wm26Releases.length===1;
    wm26Emit(actor,194,245,-Math.PI/2,'mg',null,{player:true});
    out['separate barrels retain separate flashes']=wm26Releases.length===2;
    const before=wm26Point(f);actor.x+=21;actor.y-=13;const after=wm26Point(f);
    out['moving emitter carries flash without moving projectile']=after.x-before.x===21&&after.y-before.y===-13;
    out['flash retains the fired palette across weapon switches']=f.color==='#77ee22';
    wm26Emit(other,360,245,-Math.PI/2,'missile',null,{player:true});actor.dead=true;wm26Tick(.02);
    out['dead emitter clears without removing the other player']=wm26Releases.length===1&&wm26Releases[0].owner===other;
    wm26Tick(.3);out['flash expires from simulation time']=wm26Releases.length===0;
    wm26Emit(other,360,245,-Math.PI/2,'laser',null,{player:true});run.stage=4;wm26Tick(0);
    out['stage change drops stale weapon flashes']=wm26Releases.length===0;
    boss=null;subBoss=null;enemies=[];wm26EnemyShot(200,200,1,'magma');
    out['midair projectile splits do not fabricate a gun flash']=wm26Releases.length===0;
    out['shotgun and spread use a directional fan']=WM26_REELS.shotgun.up&&WM26_REELS.spread.up;
    out['machinegun no longer uses a circular laser flash']=WM26_REELS.mg.key!=='laser_round_muzzle_';
    out['missiles have ignition artwork']=wm26Family('gmiss')==='missile'&&wm26Family('spaceVolley')==='missile';
    out['ice and lightning remain different feedback families']=wm26Family('iceLance')==='ice'&&wm26Family('yuribolt')==='lightning';
    out['miniboss keeps previous boss music']=BOFA.music.mini5==='assets/game/levels/stage_05/audio/music/Level5mb.mp3';
    out['main boss uses Hammerman Cometh']=BOFA.music.boss5==='assets/game/levels/stage_05/audio/music/Level5b.mp3';
    const ship={_ship:'magmaward',x:300,y:150,_drawY:150,w:200,h:200};
    const p=shipBossMount(ship,'L');wm26Releases=[];wm26EnemyShot(p.x,p.y,Math.PI/2,'magma',ship);
    ship.x+=12;ship.y+=8;ship._drawY+=8;const tracked=wm26Point(wm26Releases[0]);
    out['boss flash follows the same hardpoint as its shot']=Math.abs(tracked.x-shipBossMount(ship,'L').x)<.001&&Math.abs(tracked.y-shipBossMount(ship,'L').y)<.001;
    wm26Releases=[];player.dead=false;player.out=false;player._hammerEvap=0;special=null;
    wm26Emit(player,player.x,player.y-14,-Math.PI/2,'mg',null,{player:true});
    const draw=wm26Draw;let draws=0;wm26Draw=()=>draws++;_cinematicHidePlayer=true;
    wm26DrawPlayer();out['cinematic-hidden ship suppresses its weapon flashes']=draws===0;
    _cinematicHidePlayer=false;wm26DrawPlayer();out['visible ship restores its weapon flashes']=draws>0;
    wm26Draw=draw;wm26Releases=[];return JSON.stringify(out);
  })()`,ctxv));
  for(const [name,pass] of Object.entries(result))ok(pass,'Weapon feedback: '+name);
};
