"""Native Chromium regression: inputs, pixels, lethal infantry, ammo, squad AI.
Fixtures isolate damage/AI invariants; they do not claim a human balance playthrough.
"""
from pathlib import Path
import json, sys
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[3]
sys.path.insert(0,str(ROOT/'_BUILD_SOURCE'))
from shoot import serve
OUT=ROOT/'_shots/ground_1008'
OUT.mkdir(exist_ok=True)
checks=[]
def check(name,value):
    checks.append({'name':name,'passed':bool(value)})
    print(('PASS ' if value else 'FAIL ')+name,flush=True)
port,stop=serve(str(ROOT))
try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch()
  page=browser.new_page(viewport={'width':1100,'height':850})
  errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
  page.on('response',lambda r:errors.append(f'HTTP {r.status} {r.url}') if r.status>=400 else None)
  page.goto(f'http://127.0.0.1:{port}/expansion/topdown/index.html')
  page.wait_for_function('window.TDGAME && TDGAME.G.state==="title"',timeout=60000)
  page.evaluate('TDGAME.freeze();ART.warm(TD.CAMPAIGN_WARM)')
  page.wait_for_function('ART.progress(TD.CAMPAIGN_WARM)===1',timeout=60000)
  page.evaluate("window.press=(k,v)=>window.dispatchEvent(new KeyboardEvent(v?'keydown':'keyup',{key:k}));window.advance=n=>TDGAME.step(n);")
  check('all campaign authored art decodes',page.evaluate('ART.progress(TD.CAMPAIGN_WARM)===1'))
  page.locator('#screen').screenshot(path=str(OUT/'campaign_title.png'))
  page.evaluate("press('arrowright',true);advance(1);press('arrowright',false);advance(1);press('enter',true);advance(1);press('enter',false);advance(50)")
  check('real stage selector deploys Level 3 briefing',page.evaluate('TDGAME.G.mission===3 && TDGAME.G.state==="brief"'))
  page.locator('#screen').screenshot(path=str(OUT/'foot_brief.png'))
  page.evaluate("press('enter',true);advance(1);press('enter',false);advance(15);TDGAME.G.player.inv=0;")
  page.locator('#screen').screenshot(path=str(OUT/'foot_start.png'))
  check('infantry uses authored body with one-hit life rule',page.evaluate('TDGAME.G.player.onfoot && TDGAME.G.player.max===1 && TDGAME.G.player.r===8'))
  check('authored park collision retains a connected route to the fortress',page.evaluate('(()=>{const n=TD.Nav,p=TDGAME.G.player,f=n.field(400,180,0);return f.D[Math.floor(p.y/n.C)*n.cols+Math.floor(p.x/n.C)]>=0;})()'))
  box=page.locator('#screen').bounding_box()
  page.mouse.move(box['x']+box['width']*.72,box['y']+box['height']*.32)
  page.keyboard.down('d');page.mouse.down();page.evaluate('advance(22)');page.mouse.up();page.keyboard.up('d');page.evaluate('advance(1)')
  check('actual mouse fire consumes ammo while running and aiming separately',page.evaluate('TDGAME.G.player.weapons[0].ammo<12 && Math.abs(TD.M.wrap(TDGAME.G.player.aim-TDGAME.G.player.a))>.4'))
  page.locator('#screen').screenshot(path=str(OUT/'foot_run_fire.png'))
  page.evaluate('TD.Input.pointer.active=false;for(const u of TDGAME.G.units)if(u.role!=="sentry")u.dead=true;TDGAME.G.player.inv=9999;')
  result=page.evaluate("""()=>{const G=TDGAME.G,p=G.player,w=p.weapons[p.wi];w.ammo=0;const old=w.reserve;press('r',true);advance(1);press('r',false);advance(80);return w.ammo===12&&w.reserve===old-12&&p.reload===0;}""")
  check('reload transfers finite reserve into the magazine once',result)
  result=page.evaluate("""()=>{const G=TDGAME.G,p=G.player,w=p.weapons[p.wi];w.ammo=0;w.reserve=0;G.shots=[];press('j',true);advance(45);press('j',false);advance(1);return w.ammo===0&&G.shots.length===0;}""")
  check('empty gun never creates free ammunition or damage',result)
  result=page.evaluate("""()=>{const G=TDGAME.G,p=G.player,n=p.smoke;press('u',true);advance(19);const a=p.smoke;advance(30);press('u',false);advance(40);return a===n-1&&p.smoke===n-1&&!p.action&&G.footGrenades.length===0;}""")
  check('grenade commits one consumable at release and detonates once',result)
  page.evaluate("press('f',true);advance(1);press('f',false);press('w',true);advance(10);press('w',false);advance(1)")
  check('prone movement is slower and does not grant universal invisibility',page.evaluate('TDGAME.G.player.stance==="prone" && Math.hypot(TDGAME.G.player.vx,TDGAME.G.player.vy)<1 && !TDGAME.G.player.hidden'))
  page.locator('#screen').screenshot(path=str(OUT/'foot_prone.png'))
  result=page.evaluate("""()=>{const G=TDGAME.G,p=G.player;p.inv=0;G.eshots.push({k:'mg',x:p.x,y:p.y,a:0,vx:0,vy:0,r:4,dmg:1,life:10,t:0});advance(1);const dead=p.dead;advance(114);return dead&&!p.dead&&G.deaths===1&&G.lives===2&&p.hp===1;}""")
  check('one actual hostile projectile causes death and checkpoint life loss',result)
  result=page.evaluate("""()=>{const G=TDGAME.G,p=G.player;p.inv=99999;for(const [id,def] of Object.entries(TD.FOOT_GUNS)){TD.footDrop(G,p.x,p.y,id);advance(1);}return p.weapons.length===6&&p.weapons.every(w=>w.ammo>0&&Number.isFinite(w.reserve));}""")
  check('six authored guns acquire finite magazines and reserves',result)
  result=page.evaluate("""()=>{const G=TDGAME.G;for(const q of G.props)if(q.drop==='spread_shotgun'){TD.hitProp(G,q,99);const n=G.pickups.length;TD.hitProp(G,q,99);return n===G.pickups.length&&q.dead;}}""")
  check('breakable weapon box emits its fixed drop exactly once',result)
  page.evaluate('TDGAME.G.player.x=400;TDGAME.G.player.y=380;advance(4)')
  check('fortress gate has real movement and projectile collision',page.evaluate('TD.World.solidAt(400,125)&&TDGAME.G.boss.name==="FORTRESS SENTRIES"'))
  page.locator('#screen').screenshot(path=str(OUT/'fortress_closed.png'))
  result=page.evaluate("""()=>{const G=TDGAME.G;for(const u of G.units)if(u.role==='sentry')TD.hitUnit(G,u,99,u.x,u.y);advance(2);return G.boss.opened&&!TD.World.solidAt(400,125)&&!TD.World.rayBlock(400,180,400,80);}""")
  check('defeating three sentries opens collision, vision and gate art',result)
  page.evaluate('TDGAME.G.player.x=400;TDGAME.G.player.y=170;advance(50)')
  page.locator('#screen').screenshot(path=str(OUT/'fortress_open.png'))
  page.evaluate("press('w',true);advance(50);press('w',false);advance(210)")
  check('walking through north exit completes infantry mission',page.evaluate('TDGAME.G.state==="clear"'))
  page.evaluate('advance(180)')
  page.evaluate("press('enter',true);advance(1);press('enter',false);advance(50)")
  check('campaign Start advances Level 3 results to Level 4',page.evaluate('TDGAME.G.mission===4&&TDGAME.G.state==="brief"&&TDGAME.G.ally.pilot==="hotwire"'))
  page.evaluate("press('arrowdown',true);advance(1);press('arrowdown',false);advance(1)")
  check('briefing D-pad changes selected companion to Phoenix',page.evaluate('TDGAME.G.ally.pilot==="phoenix"'))
  page.locator('#screen').screenshot(path=str(OUT/'machinists_brief.png'))
  page.evaluate("press('enter',true);advance(1);press('enter',false);advance(70);TDGAME.G.player.inv=0;TDGAME.G.ally.inv=0;")
  page.locator('#screen').screenshot(path=str(OUT/'tank4_start.png'))
  check('second tank mission contains three additional armor roles',page.evaluate('new Set(TDGAME.G.units.map(u=>u.type)).size>=5 && TDGAME.G.units.some(u=>u.type==="rocketTank")&&TDGAME.G.units.some(u=>u.type==="railTank")&&TDGAME.G.units.some(u=>u.type==="siegeTank")'))
  for companion in ['hotwire','phoenix','niel']:
   page.evaluate("""(companion)=>ART.warm(['pt_'+companion+'_hull','pt_'+companion+'_turret','pav_'+companion])""",companion)
   page.wait_for_function("companion=>!!ART.get('pt_'+companion+'_hull')&&!!ART.get('pav_'+companion)",arg=companion)
   result=page.evaluate("""(companion)=>{TD.companion=companion;TDGAME.G.sel=2;TDGAME.start();const G=TDGAME.G;return G.ally.pilot===companion&&!!ART.get('pt_'+companion+'_hull')&&!!ART.get('pav_'+companion);}""",companion)
   check(companion+' companion has decoded tank and matching avatar',bool(result))
  page.evaluate('for(const u of TDGAME.G.units)u.dead=true;TDGAME.G.player.x=400;TDGAME.G.player.y=650;TDGAME.G.player.inv=99999;TDGAME.G.ally.inv=99999;advance(150)')
  check('Machinists arena spawns all three independent rebel tanks',page.evaluate('TDGAME.G.boss.tanks.length===3 && TDGAME.G.boss.state==="fight"'))
  page.locator('#screen').screenshot(path=str(OUT/'machinists_squad.png'))
  result=page.evaluate("""()=>{const G=TDGAME.G,B=G.boss;G.player.x=600;G.player.y=660;G.ally.x=240;G.ally.y=360;advance(90);return B.tanks.some(u=>u.targetPilot===G.ally.pilot)&&B.tanks.some(u=>u.shots>0);}""")
  check('rogue squad targets and fires at the nearby companion',result)
  result=page.evaluate("""()=>{const G=TDGAME.G,B=G.boss;G.player.x=240;G.player.y=360;G.ally.x=650;G.ally.y=650;advance(90);return B.tanks.some(u=>u.targetPilot===G.player.pilot);}""")
  check('rogue squad also retargets and attacks the player',result)
  check('independent track phases derive from actual chassis travel',page.evaluate('TDGAME.G.boss.tanks.some(u=>Math.abs(u.trackDistance[0])>20&&Math.abs(TD.M.wrap(u.look-u.a))>.3)'))
  page.locator('#screen').screenshot(path=str(OUT/'machinists_combat.png'))
  result=page.evaluate("""()=>{const G=TDGAME.G,B=G.boss,u=B.tanks[1];G.eshots.push({k:'laser',owner:u,part:'turret',x:400,y:400,vx:0,vy:0,a:0,dmg:1,life:60,r:3,t:0});B.damage('rolf','turret',999);const good=u.parts.turret===0&&u.recover>0&&!G.eshots.some(s=>s.owner===u&&s.part==='turret')&&TD.FX.list.some(f=>f.key==='wm_tank_rolf_turret_layer'&&f.k==='fragment'&&!f.fade);advance(3);return good;}""")
  check('turret break cancels its fire and detaches matching opaque module',result)
  page.locator('#screen').screenshot(path=str(OUT/'machinists_module_break.png'))
  result=page.evaluate("""()=>{const G=TDGAME.G,a=G.ally;a.inv=0;a.hp=1;TD.hurtAlly(G,2);const down=a.dead;advance(490);return down&&!a.dead&&a.hp===a.max;}""")
  check('downed tank companion visibly regroups and resumes support',result)
  result=page.evaluate("""()=>{const B=TDGAME.G.boss;for(const u of B.tanks){B.damage(u.crew,'turret',999);B.damage(u.crew,'special_module',999);B.damage(u.crew,'hull',999);}advance(240);return TDGAME.G.state==='clear'&&B.tanks.every(u=>u.dead)&&TDGAME.G.wrecks.filter(w=>w.art&&w.art.endsWith('_wreck')).length>=3;}""")
  check('all three modular tank deaths lead to mission completion and wrecks',result)
  page.locator('#screen').screenshot(path=str(OUT/'machinists_results.png'))
  check('zero page, console or missing-asset errors',not errors)
  (OUT/'campaign_verification.json').write_text(json.dumps({'checks':checks,'errors':errors},indent=2))
  browser.close()
finally: stop()
print(f'{sum(c["passed"] for c in checks)}/{len(checks)} checks passed',flush=True)
if not all(c['passed'] for c in checks):sys.exit(1)
