"""Native Chromium: pilot-first boot, stick-free six-button input and Retina.
Synthetic Gamepad reports exercise the browser polling path, not physical hardware.
"""
from pathlib import Path
import json,sys
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[3]
sys.path.insert(0,str(ROOT/'_BUILD_SOURCE'))
from shoot import serve
OUT=ROOT/'_shots/ground_controls_1008';OUT.mkdir(parents=True,exist_ok=True)
checks=[]
def check(n,v):
 checks.append({'name':n,'passed':bool(v)});print(('PASS ' if v else 'FAIL ')+n,flush=True)
port,stop=serve(str(ROOT))
try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch();page=browser.new_page(viewport={'width':1100,'height':850});errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
  page.on('response',lambda r:errors.append(f'HTTP {r.status} {r.url}') if r.status>=400 else None)
  page.goto(f'http://127.0.0.1:{port}/expansion/topdown/index.html')
  page.wait_for_function('window.TDGAME&&TDGAME.G.state==="pilot"',timeout=60000)
  page.evaluate('TDGAME.freeze();ART.warm(TD.PILOT_WARM)')
  page.wait_for_function('ART.progress(TD.PILOT_WARM)===1',timeout=60000)
  page.evaluate("window.press=(k,v)=>window.dispatchEvent(new KeyboardEvent(v?'keydown':'keyup',{key:k}));window.advance=n=>TDGAME.step(n);window.tap=k=>{press(k,true);advance(1);press(k,false);advance(1);};")
  check('boot opens pilot selection with all twelve avatars and full bodies decoded',page.evaluate('TD.PILOTS.length===12&&ART.progress(TD.PILOT_WARM)===1&&TDGAME.G.state==="pilot"'))
  check('roster has exactly two horizontal rows of six',page.evaluate('TD.pilotRects.length===12&&new Set(TD.pilotRects.map(r=>r[1])).size===2&&new Set(TD.pilotRects.map(r=>r[0])).size===6'))
  page.evaluate('TD.pilot="cole";tap("arrowdown");')
  check('D-pad down preserves the column on the second pilot row',page.evaluate('TD.pilot==="juggernaut"'))
  page.evaluate('tap("arrowleft")')
  check('left wraps within the row to Niel',page.evaluate('TD.pilot==="niel"'))
  page.locator('#screen').screenshot(path=str(OUT/'pilot_niel.png'))
  page.evaluate('tap("arrowleft")');page.locator('#screen').screenshot(path=str(OUT/'pilot_phoenix.png'))
  page.evaluate('tap("arrowleft")');page.locator('#screen').screenshot(path=str(OUT/'pilot_hotwire.png'))
  box=page.locator('#screen').bounding_box()
  page.mouse.click(box['x']+57.5/480*box['width'],box['y']+245/360*box['height']);page.evaluate('advance(1)')
  check('mouse roster click selects without launching',page.evaluate('TD.pilot==="cole"&&TDGAME.G.state==="pilot"'))
  page.evaluate('tap("enter")');check('Start confirms pilot before mission selection',page.evaluate('TDGAME.G.state==="title"'))
  page.evaluate('tap("b")');check('logical B returns mission selector to pilot selection',page.evaluate('TDGAME.G.state==="pilot"'))
  page.evaluate('tap("enter");tap("enter");advance(50);tap("enter")')
  check('pilot selection reaches playable Level 2 with chosen pilot',page.evaluate('TDGAME.G.state==="play"&&TDGAME.G.player.pilot==="cole"&&TDGAME.G.mission===2'))
  # Real Gamepad API polling path, with an M30 X-input shaped report and no analog sticks.
  page.evaluate("window.testPad={id:'M30 test X-input',connected:true,buttons:Array.from({length:16},()=>({pressed:false,value:0})),axes:[]};Object.defineProperty(navigator,'getGamepads',{value:()=>[testPad],configurable:true});window.pad=(...ids)=>{testPad.buttons.forEach((b,i)=>{b.pressed=ids.includes(i);b.value=b.pressed?1:0;});};const G=TDGAME.G;G.units=[];G.props=[];G.structures=[];TD.World.load(800,4000,[]);G.player.x=400;G.player.y=1800;G.player.inv=99999;TD.Input.pointer.active=false;advance(1);")
  result=page.evaluate('(()=>{const p=TDGAME.G.player,x=p.x;pad(15,2);advance(25);const ok=p.x>x+30&&Math.abs(TD.M.wrap(p.aim-Math.PI))<.001&&TDGAME.G.shots.some(s=>s.vy<0);pad();advance(1);return ok;})()')
  check('D-pad drives east while X independently fires north with zero axes',result)
  result=page.evaluate('(()=>{pad(2,3);advance(7);const p=TDGAME.G.player,ok=Math.abs(TD.M.wrap(p.aim-Math.PI*3/4))<.001;pad();advance(1);return ok;})()')
  check('adjacent X and Y produce exact northwest diagonal fire',result)
  result=page.evaluate('(()=>{const p=TDGAME.G.player;p.charge=0;p.canCd=0;pad(5);advance(45);const charged=p.charge>=40;pad();advance(1);return charged&&TDGAME.G.shots.some(s=>s.big)&&p.charge===0;})()')
  check('controller C holds charge and releases the powerful cannon',result)
  result=page.evaluate('(()=>{const p=TDGAME.G.player,a=p.a;pad(8,14);advance(20);const ok=Math.abs(TD.M.wrap(p.a-a))<.01;pad();advance(1);return ok;})()')
  check('Mode holds the tank hull while D-pad strafes',result)
  result=page.evaluate('(()=>{const p=TDGAME.G.player,n=p.smoke;pad(8,4);advance(1);pad();advance(1);return p.smoke===n-1;})()')
  check('Mode plus Z throws one smoke grenade',result)
  result=page.evaluate('(()=>{const G=TDGAME.G,p=G.player;p.weapons=[{id:"vulcan",lv:1},{id:"laser",lv:1}];p.wi=0;tap("i");window.dispatchEvent(new WheelEvent("wheel",{deltaY:100}));advance(1);return p.wi===0;})()')
  check('keyboard I and mouse wheel cannot swap tank weapons',result)
  result=page.evaluate('(()=>{const G=TDGAME.G,p=G.player;G.pickups=[{kind:"laser",x:p.x,y:p.y,t:0}];advance(1);return p.weapons.length===1&&p.weapons[0].id==="laser"&&p.wi===0;})()')
  check('new tank weapon pickup replaces the gun without storing a swap inventory',result)
  # Retina on an actual enemy: acquisition, LOS, finite stock, missile steering and damage.
  page.evaluate('const G=TDGAME.G,p=G.player;G.shots=[];G.eshots=[];p.a=p.aim=Math.PI;p.manualAim=120;p.canCd=0;p.retina=null;G.units=[TD.makeUnit("heavy",p.x,p.y-120,{a:0})];G.units[0].hp=G.units[0].max=100;G.units[0].speed=0;G.units[0].cd=9999;advance(20);pad(4);advance(30)')
  check('holding controller Z acquires a visible enemy after the lock delay',page.evaluate('TDGAME.G.player.retina.locked&&TDGAME.G.player.retina.target.id===TDGAME.G.units[0]'))
  page.locator('#screen').screenshot(path=str(OUT/'retina_locked.png'))
  result=page.evaluate('(()=>{const G=TDGAME.G,p=G.player,n=p.missiles;pad(4,5);advance(45);pad(4);advance(1);const round=G.shots.find(s=>s.retinaTarget);const ok=p.missiles===n-1&&round&&round.retinaTarget.id===G.units[0];advance(30);pad();advance(1);return ok&&G.units[0].hp<100&&!p.retina.locked;})()')
  check('C releases a Retina missile, consumes one stock, hits the locked enemy and Z release clears lock',result)
  result=page.evaluate('(()=>{const G=TDGAME.G,p=G.player;p.aim=Math.PI;p.canCd=0;p.retina=null;const u=G.units[0];u.x=p.x;u.y=p.y-100;TD.World.add({x0:p.x-35,y0:p.y-65,x1:p.x+35,y1:p.y-45,t:"b"});pad(4);advance(35);const ok=!p.retina.target;pad();advance(1);return ok;})()')
  check('Retina refuses enemies behind solid cover',result)
  page.evaluate('TDGAME.G.sel=0;TDGAME.start();const G=TDGAME.G;G.units.forEach(u=>u.dead=true);G.player.x=400;G.player.y=635;G.player.inv=999999;advance(180)')
  check('Warrior entry and fight retain camera zoom exactly one',page.evaluate('TD.Cam.zoom===1&&TDGAME.G.boss.name==="THE WARRIOR"'))
  page.locator('#screen').screenshot(path=str(OUT/'warrior_native_scale.png'))
  check('Warrior Retina exposes individual live modular parts',page.evaluate('TDGAME.G.boss.retinaTargets().length===4&&TDGAME.G.boss.retinaTargets().every(q=>q.valid()&&Number.isFinite(q.point().x))'))
  page.evaluate('TDGAME.G.sel=2;TDGAME.start();TDGAME.G.units.forEach(u=>u.dead=true);TDGAME.G.player.x=400;TDGAME.G.player.y=650;TDGAME.G.player.inv=999999;TDGAME.G.ally.inv=999999;advance(160)')
  check('Machinists fight retains camera zoom exactly one',page.evaluate('TD.Cam.zoom===1&&TDGAME.G.boss.retinaTargets().length===15'))
  page.locator('#screen').screenshot(path=str(OUT/'machinists_native_scale.png'))
  result=page.evaluate('(()=>{const B=TDGAME.G.boss,t=B.retinaTargets().find(q=>q.id==="rolf:turret");B.damage("rolf","turret",1000);return !t.valid();})()')
  check('destroyed modular parts invalidate their committed Retina target',result)
  page.evaluate('TDGAME.G.sel=1;TDGAME.start();const G=TDGAME.G;G.units=[];G.props=[];G.player.inv=99999;G.player.x=400;G.player.y=1100;advance(1);')
  result=page.evaluate('(()=>{const G=TDGAME.G,p=G.player;TD.footDrop(G,p.x,p.y,"minigun");advance(1);tap("i");window.dispatchEvent(new WheelEvent("wheel",{deltaY:-100}));advance(1);return p.weapons.length===1&&p.weapons[p.wi].id==="minigun";})()')
  check('infantry pickups replace the gun and wheel/keyboard cannot swap it',result)
  result=page.evaluate('(()=>{const p=TDGAME.G.player,n=p.weapons[0].ammo;pad(15,2);advance(18);const ok=p.weapons[0].ammo<n&&Math.abs(TD.M.wrap(p.aim-Math.PI))<.001&&p.vx>0;pad();advance(1);return ok;})()')
  check('stick-free directional fire also works while running on foot',result)
  result=page.evaluate('(()=>{const p=TDGAME.G.player;p.weapons[0].ammo=0;pad(8,0);advance(1);pad();advance(80);pad(8,2);advance(1);pad();advance(1);return p.weapons[0].ammo>0&&p.stance==="prone";})()')
  check('Mode plus A reloads and Mode plus X toggles prone without firing',result)
  # Learn a nonstandard pad from real neutral/held reports, then use its saved mapping.
  page.evaluate('tap("f2");testPad.id="Nonstandard six-button test";pad();advance(1)')
  for index in [12,13,14,15,3,0,4,1,2,5,6,7]:
   page.evaluate('(i)=>{pad(i);advance(1);pad();advance(1);}',index)
  check('setup learns D-pad and all eight physical buttons on a nonstandard mapping',page.evaluate('TD.Input.setup.done&&JSON.parse(localStorage.getItem("bof_td_controllers"))[testPad.id].start===7'))
  page.evaluate('pad(7);advance(1);pad();advance(1)')
  check('learned Start closes setup and restores gameplay',page.evaluate('TDGAME.G.state==="play"'))
  result=page.evaluate('(()=>{const p=TDGAME.G.player;pad(15,1);advance(12);const ok=p.vx>0&&Math.abs(TD.M.wrap(p.aim-Math.PI))<.001;pad();advance(1);return ok;})()')
  check('learned controller mapping drives and fires with no analog axes',result)
  check('zero browser, console and missing-asset errors',not errors)
  (OUT/'verification.json').write_text(json.dumps({'checks':checks,'errors':errors,'hardware':'Synthetic Gamepad API reports; physical M30 not connected'},indent=2))
  browser.close()
finally:stop()
print(f'{sum(c["passed"] for c in checks)}/{len(checks)} checks passed')
sys.exit(0 if all(c['passed'] for c in checks) else 1)
