from pathlib import Path
import json,re,hashlib,subprocess
import imageio_ffmpeg
R=Path(__file__).resolve().parents[2];O=R/'_shots/retina_scan_0914';V=O/'video';log=(O/'tests.log').read_text(encoding='utf-8');fail=[l.strip()for l in log.splitlines()if 'ASSERT FAIL:'in l];passed=len(re.findall(r'^  ok  ',log,re.M));assert 'FAILED —'in log and passed+len(fail)==3847
base=json.loads((R/'docs/qa/stage_1_5_0914.json').read_text(encoding='utf-8'))['suite']['failureNames'];norm=lambda s:re.sub(r'\d+(?:\.\d+)?','#',s);new=[x for x in fail if norm(x)not in{norm(x)for x in base}];assert not new;missing=[x for x in base if norm(x)not in{norm(x)for x in fail}];assert all('sand tanks spawn'in x for x in missing)
section=log[log.index('=== 305.'):log.index('============================================',log.index('=== 305.'))];assert len(re.findall(r'^  ok  ',section,re.M))==16
browser=json.loads((O/'results.json').read_text(encoding='utf-8'));assert len(browser['checks'])==13 and all(c['pass']for c in browser['checks'])and not browser['errors']and not browser['details']['error']
video=json.loads((V/'report.json').read_text(encoding='utf-8'));assert len(video['takes'])==1 and not video['errors'];t=video['takes'][0];assert t['seconds']==14 and t['audio']['peak']<1 and not t['audio']['errs'];timeline=t['timeline'];assert len(timeline[1]['marks'])==4 and timeline[1]['ammo']-timeline[2]['ammo']==4 and not timeline[-1]['marks']
movie=V/'BulletsOfFury_Retina_MultiLock_0914.mp4';ff=imageio_ffmpeg.get_ffmpeg_exe();crc=V/'final.framecrc';subprocess.run([ff,'-y','-v','error','-i',str(movie),'-map','0:v:0','-f','framecrc',str(crc)],check=True);n=sum(1 for l in crc.read_text().splitlines()if l and not l.startswith('#'));assert n==420;subprocess.run([ff,'-v','error','-i',str(movie),'-f','null','-'],check=True)
runtime=(R/'assets/game.js').read_bytes();tests=(R/'_BUILD_SOURCE/test_fl.js').read_bytes();assert runtime==(O/'game.expected.js').read_bytes()and b'\r\n'not in runtime;assert tests.count(b'\n')==tests.count(b'\r\n');sha=lambda x:hashlib.sha256(x).hexdigest()
report={'suite':{'passed':passed,'failed':len(fail),'exitCode':1,'finalSummaryReached':True,'section305Passed':16,'newFailingAssertionNames':new,'failureNames':fail,'missingBaselineFailures':missing,'baseline':'docs/qa/stage_1_5_0914.json'},'browser':browser,'runtime':{'sha256':sha(runtime),'testSha256':sha(tests),'LF':True,'testsCRLF':True,'sourceReproduction':True},'settings':{'capacity':4,'acquireSeconds':.45,'lockSeconds':5,'launchGapSeconds':.05,'pickup':'eligible missile crate from Stage 2 onward','save':'optional retinaScan boolean in campaign snapshot','death':'clears targets and queue; equipment survives death','stageChange':'clears targets, retains equipment','newRun':'clears equipment'},'video':{'file':str(movie),'frames':n,'seconds':14,'fps':30,'decodeExitCode':0,'runtimeSha256':sha(runtime),'protectedPilot':True,'nativeDebugCarrier':True,'fixture':'Native stage-6 carrier, phase 2 with live nodes at 100HP each; player positioned to bring four authored node positions into the camera; boss mega cooldown deferred to isolate the scanner. Native carrier guns still run. Real keyboard events trigger scans and fire.','audio':'Native effects recorded at 60% in-game SFX, 80% master; no music and no export normalization. Dense carrier mix slightly exceeded full scale at the earlier 74% SFX setting; broad encounter mix remains a future balancing item.','takes':video['takes'],'errors':video['errors']},'visualReview':'Authored pickup, four separate node retinas, flashing expiry and native missiles inspected. Crate effect formerly printed undefined; now uses the existing authored particle shock ring.','pending':['Universal no-one-shot damage rule','Hard/Furious encounter variants','Missile tiers and production assets','Achievements and remaining overnight ledger']}
(R/'docs/qa/retina_scan_0914.json').write_text(json.dumps(report,indent=2),encoding='utf-8');(V/'audit.json').write_text(json.dumps(report['video'],indent=2),encoding='utf-8');print(passed,len(fail),'exit1; native13/0; 420 decoded frames; peak',t['audio']['peak'])
