(function(root){'use strict';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Jet{
constructor(random=Math.random){this.random=random;this.time=0;this.t=0;this.phase='arrival';this.hp=this.max=8000;this.scale=.18;this.mountScale=.18/.76;this.boss={x:450,y:-120,a:0};this.player={x:450,y:870,hp:100,inv:0};this.rig=Array.from({length:4},()=>({hp:300,hit:0,charge:0,flash:0,recoil:0,a:0}));this.bullets=[];this.shots=[];this.beams=[];this.fx=[];this.events=[];this.history=[];this.kills=0;this.fire=0;this.hitFlash=0;this.shake=0;this.wall=1080;this.speed=2200;this.mode='';this.pattern='';this.vulnerable=false;this.state='';this.st=0;this.cycle=0;this.side=1;this.beat=-1;this.ramCount=0;this.stats={rams:0,beams:0,bolts:0};this.motionAxis='none';this.lockX=450;this.ramY=600}
enter(phase){this.phase=phase;this.t=0;this.st=0;this.state='';this.beat=-1;this.beams=[];this.bullets=[];this.shots=[];this.vulnerable=false;this.history.push(phase);this.events.push('transition');if(phase==='pursuit'||phase==='frenzy'){this.ramCount=0;this.change('track');this.boss.y=930}if(phase==='chase'||phase==='hell')this.change('strafe');if(phase==='escape')this.wall=1080;if(phase==='death')this.deathStart={...this.boss}}
change(state){this.state=state;this.st=0;this.beat=-1;this.beams=[];this.events.push('maneuver');if(state==='track')this.targetX=clamp(this.player.x,100,800);if(state==='strafe')this.targetX=this.boss.x<450?760:140;if(state==='edge'){this.side=this.random()<.5?-1:1;this.lockX=this.side<0?65:835;this.ramY=clamp(this.player.y,170,910)}if(state==='ram'){this.ramTarget=this.side<0?850:50;this.stats.rams++;this.events.push('ram')}if(state==='dive'&&this.phase==='hell')for(const q of this.ports(1))this.spawn(q.x,q.y,Math.PI/2,740,'missile');if(state==='punish-rise')this.punishY=clamp(this.player.y-145,120,760)}
move(axis,target,speed,dt){this.motionAxis=axis;const b=this.boss;b[axis]+=clamp(target-b[axis],-speed*dt,speed*dt);return Math.abs(target-b[axis])<.01}
turrets(){return[-1,1].flatMap((side,j)=>[-1,1].map((dir,i)=>({id:j*2+i,x:this.boss.x+side*19,y:this.boss.y+(dir<0?-44:40),localX:side*19,localY:dir<0?-44:40,dir,...this.rig[j*2+i]})))}
damage(n){if(!this.vulnerable)return;const floor={chase:6000,pursuit:4000,hell:2000,frenzy:0}[this.phase];if(floor===undefined)return;if(n>0)this.hitFlash=.045;this.hp=Math.max(floor,this.hp-n);if(this.hp===floor)this.enter({chase:'overtake',pursuit:'return',hell:'falsecrash',frenzy:'death'}[this.phase])}
damageTurret(id,n){const r=this.rig[id];if(!this.vulnerable||r.hp<=0)return;r.hp=Math.max(0,r.hp-n);r.hit=.09;this.hitFlash=.045;if(!r.hp){const q=this.turrets()[id];this.fx.push({x:q.x,y:q.y,anchor:{x:q.localX,y:q.localY},age:0,life:.7,s:35});this.events.push('impact');this.damage(90)}}
hurt(n,input){if(input.practice||input.demo||this.player.inv>0)return;this.player.hp=Math.max(0,this.player.hp-n);this.player.inv=.48;this.shake=8;this.events.push('hurt');if(!this.player.hp)this.enter('defeat')}
spawn(x,y,a,s=480,kind='bolt'){this.bullets.push({x,y,a,s,kind,age:0,life:4,r:kind==='missile'?9:5,hp:kind==='missile'?2:1})}
ports(dir){return this.turrets().filter(q=>q.dir===dir&&q.hp>0)}
bolts(t,dir,rapid=false){const beat=Math.floor(t/(rapid?.16:.25));if(beat===this.beat)return;this.beat=beat;for(const q of this.ports(dir)){this.spawn(q.x,q.y,dir*Math.PI/2,rapid?640:540);this.rig[q.id].flash=.06;this.stats.bolts++;this.events.push('shot')}}
lasers(dir,t,warn=.5,duration=1.25){this.beams=[];const active=t>=warn&&t<warn+duration;if(t>=warn+duration)return;for(const q of this.ports(dir)){const beam={x:q.x,y:q.y,dir,width:active?12:2,active,charge:clamp(t/warn,0,1),id:q.id};this.beams.push(beam);this.rig[q.id].charge=active?0:beam.charge;if(active&&this.rig[q.id].flash<=0){this.rig[q.id].flash=.15;this.events.push('laser')}}if(active)this.stats.beams++}
chase(dt){const hard=this.phase==='hell',b=this.boss;this.vulnerable=true;this.speed=hard?2900:2400;switch(this.state){case 'strafe':this.mode='HIGH-SPEED STRAFE • REAR CANNONS';this.bolts(this.st,1,hard);if(this.move('x',this.targetX,hard?640:530,dt))this.change('laser-track');break;case 'laser-track':this.mode='DUAL REAR LASERS • MOVE OUT OF THE LANES';if(this.st<(hard?.4:.55))this.move('x',clamp(this.player.x,100,800),470,dt);this.lasers(1,this.st,hard?.4:.55,hard?1.45:1.1);if(this.st>(hard?1.85:1.65))this.change('dive');break;case 'dive':this.mode='VERTICAL DIVE • BREAK CONTACT';this.bolts(this.st,1,hard);if(this.move('y',600,hard?920:760,dt))this.change('climb');break;case 'climb':this.mode='CLIMBING • KEEP FIRING';if(this.move('y',210,820,dt))this.change('strafe');break;default:this.change('strafe')}}
pursuit(dt){const hard=this.phase==='frenzy',b=this.boss;this.speed=hard?3400:3000;this.vulnerable=true;switch(this.state){case 'track':this.mode='PURSUER BELOW • DODGE THE TWIN LASERS';this.move('x',clamp(this.player.x,85,815),hard?660:560,dt);this.bolts(this.st,-1,hard);if(this.st>.8)this.change('laser-run');break;case 'laser-run':this.mode='FORWARD LASERS • CLEAR BOTH LANES';if(this.st>(hard?.35:.5))this.move('y',180,hard?700:570,dt);this.lasers(-1,this.st,hard?.35:.5,1.2);if(this.st>(hard?1.55:1.7))this.change('edge');break;case 'edge':this.mode='FLANKING '+(this.side<0?'LEFT':'RIGHT');this.bolts(this.st,b.y<this.player.y?1:-1,hard);if(this.move('x',this.lockX,hard?1000:850,dt))this.change('row');break;case 'row':this.mode='SIDE ATTACK • CHANGE ALTITUDE';if(this.move('y',this.ramY,hard?900:760,dt))this.change('ram-warn');break;case 'ram-warn':this.mode='RAM '+(this.ramCount+1)+' • DODGE VERTICALLY';this.ramWarning=true;if(this.st>(hard?.28:.4))this.change('ram');break;case 'ram':this.mode='SIDE RAM • KEEP MOVING';this.ramWarning=true;if(this.move('x',this.ramTarget,hard?1450:1200,dt)){this.ramCount++;this.change('punish-rise')}break;case 'punish-rise':this.mode='COUNTERATTACK • GET BELOW HIM';if(this.move('y',this.punishY,hard?850:720,dt))this.change('punish');break;case 'punish':this.mode='FIRE NOW • NEXT RAM IN '+Math.max(0,(hard?.72:1)-this.st).toFixed(1)+'s';this.lasers(1,this.st,.35,hard?.37:.65);if(this.st>(hard?.72:1)){if(this.ramCount<(hard?4:3))this.change('edge');else{this.ramCount=0;this.change('reset-row')}}break;case 'reset-row':this.mode='PURSUER DIVING BELOW';if(this.move('y',930,900,dt))this.change('track');break;default:this.change('track')}}
hitHull(x,y){return Math.abs(x-this.boss.x)<44&&Math.abs(y-this.boss.y)<48}
explode(dt,large){if(this.random()<dt*(large?18:5)){const x=(this.random()-.5)*105,y=(this.random()-.5)*110;this.fx.push({x:this.boss.x+x,y:this.boss.y+y,anchor:{x,y},age:0,life:.8,s:large?42:23});this.events.push('impact');if(large)this.shake=12}}
step(dt,input={}){dt=clamp(dt,0,.04);this.events=[];this.time+=dt;this.t+=dt;this.st+=dt;this.cycle+=dt;this.motionAxis='none';this.ramWarning=false;this.beams=[];this.boss.a=0;this.hitFlash=Math.max(0,this.hitFlash-dt);this.shake=Math.max(0,this.shake-dt*25);this.fx=this.fx.filter(f=>(f.age+=dt)<f.life);for(const r of this.rig){r.hit=Math.max(0,r.hit-dt);r.flash=Math.max(0,r.flash-dt);r.charge=0}const p=this.player,b=this.boss;p.inv=Math.max(0,p.inv-dt);if(['victory','defeat'].includes(this.phase))return;
const combat=['chase','hell','pursuit','frenzy'].includes(this.phase);if(combat){let tx=input.pointer?.x,ty=input.pointer?.y;if(input.demo){tx=b.x;ty=b.y<600?840:200}if(tx!==undefined){p.x+=clamp(tx-p.x,-540*dt,540*dt);p.y+=clamp(ty-p.y,-540*dt,540*dt)}else{const n=Math.hypot(input.x||0,input.y||0)||1,m=input.slow?.45:1;p.x+=(input.x||0)/n*480*dt*m;p.y+=(input.y||0)/n*480*dt*m}p.x=clamp(p.x,24,876);p.y=clamp(p.y,80,965)}this.vulnerable=false;
if(this.phase==='arrival'){this.mode='TEMPEST RAZOR • INTERCEPT';if(this.move('y',230,520,dt)&&this.t>1)this.enter('chase')}
else if(this.phase==='chase'||this.phase==='hell')this.chase(dt);
else if(this.phase==='pursuit'||this.phase==='frenzy')this.pursuit(dt);
else if(this.phase==='overtake'||this.phase==='return'){this.speed=3400;const over=this.phase==='overtake';this.mode=over?'OVERTAKE • HOSTILE ON YOUR SIX':'DROP BACK • HOSTILE AHEAD';p.y+=clamp((over?200:870)-p.y,-600*dt,600*dt);this.move('y',over?930:230,720,dt);if(this.t>1.5)this.enter(over?'pursuit':'hell')}
else if(this.phase==='falsecrash'){this.mode='BURNING • STILL IN PURSUIT';this.move('y',1100,850,dt);this.explode(dt,true);if(this.t>1.3)this.enter('frenzy')}
else if(this.phase==='death'){this.mode='REACTOR FAILURE';this.move('y',1200,230,dt);this.explode(dt,true);if(this.t>3.3){this.enter('escape');p.x=450;p.y=760}}
else if(this.phase==='escape'){this.mode='AFTERBURNER • ESCAPE';this.speed=3400;p.y=760-this.t*250;this.wall=1080-this.t*310;this.shake=12;if(this.random()<dt*28)this.fx.push({x:this.random()*900,y:this.wall+this.random()*220,age:0,life:1,s:220+this.random()*180});if(this.t>3.9)this.enter('victory')}
if(this.phase==='frenzy')this.explode(dt,false);
if(combat){this.fire-=dt;if(input.fire!==false&&this.fire<=0){this.fire=.085;for(const dx of [-9,9])this.shots.push({x:p.x+dx,y:p.y-25,life:1.6})}}
for(const s of this.shots){s.y-=1050*dt;s.life-=dt;for(const q of this.bullets)if(q.kind==='missile'&&q.life>0&&s.life>0&&Math.hypot(s.x-q.x,s.y-q.y)<q.r+4){s.life=0;if(--q.hp<=0){q.life=0;this.kills++;this.fx.push({x:q.x,y:q.y,age:0,life:.5,s:35})}}if(s.life>0&&this.vulnerable){for(const q of this.turrets())if(q.hp>0&&Math.abs(s.x-q.x)<8&&Math.abs(s.y-q.y)<11){s.life=0;this.damageTurret(q.id,13);break}if(s.life>0&&this.hitHull(s.x,s.y)){s.life=0;this.damage(input.demo&&this.t<18?0:13)}}}this.shots=this.shots.filter(s=>s.life>0&&s.y>-60);
for(const q of this.bullets){q.age+=dt;q.life-=dt;q.y+=Math.sin(q.a)*q.s*dt;q.x+=Math.cos(q.a)*q.s*dt;if(q.life>0&&Math.hypot(q.x-p.x,q.y-p.y)<q.r+6){q.life=0;this.hurt(q.kind==='missile'?18:10,input)}}this.bullets=this.bullets.filter(q=>q.life>0&&q.y>-100&&q.y<1100&&q.x>-100&&q.x<1000);
for(const beam of this.beams)if(beam.active&&Math.abs(p.x-beam.x)<beam.width/2+6&&(beam.dir<0?p.y<beam.y:p.y>beam.y))this.hurt(20,input);
if(combat&&this.hitHull(p.x,p.y))this.hurt(32,input);if(input.demo&&this.vulnerable&&this.t>22)this.damage(dt*180);
}
}
const api={Jet,clamp};if(typeof module!=='undefined')module.exports=api;else root.JetEngine=api;
})(typeof window!=='undefined'?window:globalThis);
