from pathlib import Path
import json,re,hashlib
R=Path(__file__).resolve().parents[2];O=R/'_shots/arcade_rules_0914';log=(O/'tests.log').read_text(encoding='utf-8');fail=[l.strip()for l in log.splitlines()if 'ASSERT FAIL:'in l];passed=len(re.findall(r'^  ok  ',log,re.M));assert 'FAILED —'in log and passed+len(fail)==3864
base=json.loads((R/'docs/qa/stage_1_5_0914.json').read_text(encoding='utf-8'))['suite']['failureNames'];norm=lambda s:re.sub(r'\d+(?:\.\d+)?','#',s);new=[x for x in fail if norm(x)not in{norm(x)for x in base}];assert not new
section=log[log.index('=== 306.'):log.index('============================================',log.index('=== 306.'))];assert len(re.findall(r'^  ok  ',section,re.M))==17
browser=json.loads((O/'results.json').read_text(encoding='utf-8'));assert len(browser['checks'])==22 and all(c['pass']for c in browser['checks'])and not browser['errors']and not browser['details']['loopError']
runtime=(R/'assets/game.js').read_bytes();tests=(R/'_BUILD_SOURCE/test_fl.js').read_bytes();assert runtime==(O/'game.expected.js').read_bytes()and b'\r\n'not in runtime;assert tests.count(b'\n')==tests.count(b'\r\n');sha=lambda x:hashlib.sha256(x).hexdigest()
report={'suite':{'passed':passed,'failed':len(fail),'exitCode':1,'finalSummaryReached':True,'section306Passed':17,'newFailingAssertionNames':new,'failureNames':fail,'missingBaselineFailures':[x for x in base if norm(x)not in{norm(x)for x in fail}],'baseline':'docs/qa/stage_1_5_0914.json'},'browser':browser,'runtime':{'sha256':sha(runtime),'testSha256':sha(tests),'LF':True,'testsCRLF':True,'syntaxCheckExitCode':0},'rules':{'mode':'arcade','easy':{'lives':7,'continues':7},'normal':{'lives':5,'continues':5},'hard':{'lives':3,'continues':3},'furious':{'lives':3,'continues':1},'continueRestores':'same stock as starting lives','bankScope':'entire run, including Stage 9','campaign':'existing stock and rift retreat rules preserved; save load refreshes DIFF'},'visualReview':'Inspected native contact sheet: all four authored difficulty buttons/descriptions, last-credit prompt and zero-credit prompt. Native HUD and Stage-9 game-over screenshots captured. Real Enter drives continues after controlled exhausted-life setup. No new art or atlas edits.','limitations':['Full Arcade cutscene/map/encounter parity audit remains open.','Existing Stage-9 bonus life grant remains; starting lives are not a maximum-life cap.','Native fixture sets exhausted lives/credits to exercise prompt boundaries; VM tests spend every credit in sequence.','Whole suite remains nonzero due to recorded baseline failures.']}
(R/'docs/qa/arcade_rules_0914.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8');print(passed,'passed /',len(fail),'failed, exit 1; new failures',len(new),'; native 22/0')
