from pathlib import Path
import re,json,hashlib,subprocess
import imageio_ffmpeg
R=Path.cwd();O=R/'_shots/retina_targets_0914';V=R/'_shots/shared_laser_warnings_0914/video';l=(O/'tests.log').read_text(encoding='utf-8');f=[x.strip()for x in l.splitlines()if 'ASSERT FAIL:'in x];n=len(re.findall(r'^  ok  ',l,re.M));assert n==3771 and len(f)==60 and 'FAILED — 60 error(s):'in l
base=json.loads((R/'docs/qa/stage_1_5_0914.json').read_text(encoding='utf-8'))['suite']['failureNames'];norm=lambda x:re.sub(r'\d+(?:\.\d+)?','#',x);assert not[x for x in f if norm(x)not in {norm(x)for x in base}];missing=[x for x in base if norm(x)not in {norm(x)for x in f}];assert missing==['ASSERT FAIL: stage 1: the sand tanks spawn (scroll never)']
b=json.loads((O/'results.json').read_text(encoding='utf-8'));assert len(b['checks'])==12 and all(c['pass']for c in b['checks'])and not b['errors']
v=json.loads((V/'report.json').read_text(encoding='utf-8'));assert len(v['takes'])==2 and not v['errors'];assert all(t['audio']['peak']<1 and not t['audio']['errs']for t in v['takes']);m=V/'BulletsOfFury_Pause_and_Blue_Lasers_0914.mp4';ff=imageio_ffmpeg.get_ffmpeg_exe();crc=V/'final.framecrc';subprocess.run([ff,'-y','-v','error','-i',str(m),'-map','0:v:0','-f','framecrc',str(crc)],check=True);frames=sum(1 for x in crc.read_text().splitlines()if x and not x.startswith('#'));assert frames==570;subprocess.run([ff,'-v','error','-i',str(m),'-f','null','-'],check=True)
run=(R/'assets/game.js').read_bytes();tests=(R/'_BUILD_SOURCE/test_fl.js').read_bytes();assert run==(O/'game.expected.js').read_bytes()and b'\r\n'not in run;assert tests.count(b'\r\n')==tests.count(b'\n');sha=lambda x:hashlib.sha256(x).hexdigest()
report={'suite':{'passed':n,'failed':60,'exitCode':1,'finalSummaryReached':True,'section304Passed':11,'newFailingAssertionNames':[],'failureNames':f,'missingBaselineFailures':missing,'randomBaselineNote':'The historical sand-tank spawn assertion passed this run; this is not claimed as a fix.'},'browser':b,'runtime':{'sha256':sha(run),'beforeSha256':sha((O/'game.before.js').read_bytes()),'testSha256':sha(tests),'LF':True,'testsCRLF':True},'video':{'file':str(m),'frames':frames,'fps':30,'seconds':19,'fullDecodeExitCode':0,'nativeAudioNoNormalization':True,'takes':v['takes'],'errors':v['errors']},'scope':'Retina eligibility for Stage-6 nodes and open bays; Stage-4 nodes/helpers; Regent mother/helpers; existing modular/S9 bodies. Manual missile component damage, invalid hull lock clearing and shared seeking weapon lists. Explosion gain and retrigger limits correct measured death mix clipping.','pending':'Directional five-second multi-lock upgrade, no-one-shot rule, tier upgrade assets, Hard/Furious variants, achievements and other overnight work remain pending.'}
(R/'docs/qa/retina_targets_0914.json').write_text(json.dumps(report,indent=2),encoding='utf-8');(V/'audit.json').write_text(json.dumps(report['video'],indent=2),encoding='utf-8')
p=R/'docs/qa/shared_laser_warnings_0914.json';q=json.loads(p.read_text(encoding='utf-8'));q['video']=report['video'];q['video']['runtimeSha256']=sha(run);p.write_text(json.dumps(q,indent=2),encoding='utf-8')
print('3771/60 exit 1; no new assertion names. Chromium 12/0. Video 570 decoded frames, peaks:',[t['audio']['peak']for t in v['takes']])
