"""Own the small runtime registry. Import metadata; never repaint authored pixels."""
from pathlib import Path
import json, argparse
from PIL import Image

def build(root, art_root=None):
    art = (art_root or root) / 'assets/game/hama_art_0928'
    families = json.loads((art/'manifest.json').read_text())['families']
    # Rectangles are measured on the normalized authored PNGs. Replace helmets
    # only on these front views; the side/back helmets stay part of their plate.
    heads = {
        'boss_lasso_360': {0:[189,185,270,257],11:[168,172,240,242]},
        'boss_vocal_leap': {0:[174,222,270,296]},
        'double_hammer_slam': {2:[180,193,277,273],7:[178,280,265,353]},
        'hammer_toss_helper_throw': {0:[194,241,279,300]},
        'helper_lasso_360': {0:[55,27,121,89],11:[49,27,111,88]},
        'helper_airborne_tumble': {0:[54,33,121,93],7:[56,40,115,96]},
    }
    out = {'version':1, 'source':'assets/game/levels/stage_05/boss/hama_art_0928/manifest.json', 'families':{}}
    for name, d in families.items():
        # Superseded silver moonwalks stay in the source pack as unused art.
        # The shield rise must not change the boss's regular appearance.
        if name.startswith('armored_moonwalk_'): continue
        out['families'][name] = {
            'key':'hama29_'+name, 'path':'assets/game/levels/stage_05/boss/hama_art_0928/'+d['atlas'],
            'size':d['size'], 'anchor':d['anchor'], 'fps':d['fps'],
            'frames':[f['rect'] for f in d['frames']], 'events':d['events'],
            'heads':heads.get(name,{}),
        }
        for f in d['frames']:
            if not (art/f['file']).is_file(): raise ValueError(f['file'])
        with Image.open(art/d['atlas']) as im:
            for x,y,w,h in out['families'][name]['frames']:
                assert x>=0 and y>=0 and x+w<=im.width and y+h<=im.height
    # Local points in raw selected source, converted using the importer's fixed
    # scale/offset. Held target and caption follow the helper actually in the art.
    toss = families['hammer_toss_helper_throw']
    points = {4:[250,565],5:[570,565],6:[851,529],7:[1113,518],8:[109,764],9:[419,780]}
    def normalized(f, p):
        r=toss['frames'][f]; sx,sy=r['sourceRect'][:2]; bx,by=r['sourceAlphaBounds'][:2]
        return [round(r['offset'][0]+(p[0]-sx-bx)*r['sharedScale'],3),
                round(r['offset'][1]+(p[1]-sy-by)*r['sharedScale'],3)]
    out['families']['hammer_toss_helper_throw']['held']={f:normalized(f,p) for f,p in points.items()}
    out['families']['hammer_toss_helper_throw']['launch']=normalized(2,[704,78])
    out['families']['hammer_toss_helper_throw']['helperHeads']={7:[190,278,273,327]}
    dest=root/'assets/hama_frames_art_0929.js'; dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text('/* Generated by _BUILD_SOURCE/hama_art_0928/build_runtime.py. */\nconst HAMA_FRAMES_ART_29='+json.dumps(out,separators=(',',':'))+';\n',encoding='utf-8',newline='\n')
    active=out['families']
    print(f'Registered {len(active)} live reels / {sum(len(d["frames"]) for d in active.values())} authored frames; silver moonwalks unused.')

if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[2]);ap.add_argument('--art-root',type=Path)
    args=ap.parse_args();build(args.root,args.art_root)
