from pathlib import Path
import re,json,hashlib
R=Path.cwd();O=R/'_shots/shared_laser_warnings_0914';H=R/'_BUILD_SOURCE/shared_laser_warnings_0914'
p=R/'_BUILD_SOURCE/test_fl.js';s=p.read_bytes().decode('utf-8');old='only the stage-3 (rime) laser wears the cones - the lava and legion lanes ship unchanged';new='all shared laser families use the color-changing combat FOV';assert s.count(old)+s.count(new)==1;p.write_bytes(s.replace(old,new).encode('utf-8'))
a=H/'append_tests.py';s=a.read_text(encoding='utf-8');s=s.replace("a=s.index(b);z=s.index('\\n',s.index('ok(',a)if 'ok('in s[a:a+10]else a)","s=s.replace('"+old+"','"+new+"')");s=s.replace('before.read_bytes(),expected','before.read_bytes(),expected,expected.replace(b"'+new+'",b"'+old+'")');a.write_text(s,encoding='utf-8')
l=(O/'tests.log').read_text(encoding='utf-8');f=[x.strip()for x in l.splitlines()if 'ASSERT FAIL:'in x];n=len(re.findall(r'^  ok  ',l,re.M));assert n==3759 and len(f)==61,(n,len(f));assert 'FAILED — 61 error(s):'in l
base=json.loads((R/'docs/qa/stage_1_5_0914.json').read_text(encoding='utf-8'))['suite']['failureNames'];norm=lambda x:re.sub(r'\d+(?:\.\d+)?','#',x);assert {norm(x)for x in f}=={norm(x)for x in base}
b=json.loads((O/'results.json').read_text(encoding='utf-8'));assert len(b['checks'])==7 and all(c['pass']for c in b['checks'])and not b['errors']
run=(R/'assets/game.js').read_bytes();assert run==(O/'game.expected.js').read_bytes();assert b'\r\n'not in run
proof={'suite':{'passed':n,'failed':61,'exitCode':1,'finalSummaryReached':True,'failureNames':f,'newFailingAssertionNames':[],'section303Passed':3,'labelCorrection':'Following this run, an obsolete assertion label was corrected without changing its tested condition.'},'browser':b,'runtime':{'sha256':hashlib.sha256(run).hexdigest(),'LF':True,'testsCRLF':True},'visualReview':'Native Stage-3 cannon release screenshot inspected: side nozzles only, dark blue outer beams with narrow light core. All four shared warning families render authored green/yellow/red FOV plates.','video':{'status':'Partial recording retained; pause death explosion mix clips at peak 1.677 and must be corrected before publishing the combined preview.'}}
(R/'docs/qa/shared_laser_warnings_0914.json').write_text(json.dumps(proof,indent=2),encoding='utf-8')
for rel,txt in [('HANDOFF_CODEX.md','\n## 0914 shared laser warnings\nShared laser families now inherit the same three-second authored green/yellow/red FOV. Stage-3 cannons use dark-blue bodies and a narrow light core. Full suite 3759 pass / 61 baseline failures, exit 1; Chromium 7/0, no errors. Proof: docs/qa/shared_laser_warnings_0914.json. Combined pause/laser video is pending a clipping correction for overlapping death explosions. Retina target eligibility is next.\n'),('docs/OVERNIGHT_REQUESTS_0914.md','\nVerified shared laser-family FOV inheritance and dark-blue Stage-3 beams: suite 3759/61 exit 1, same baseline failures; Chromium 7/0. Remaining non-laser boss tells and Furious exceptions still pending. Pause video export exposed overlapping explosion audio clipping; correction queued with Retina work.\n')]:
 q=R/rel;q.write_bytes(q.read_bytes()+txt.encode('utf-8'))
print(n,len(f),'baseline names matched; Chromium 7/0.')
