from pathlib import Path
import json,re,hashlib
R=Path(__file__).resolve().parents[2];O=R/'_shots/easy_queue_0914';log=(O/'tests.log').read_text(encoding='utf-8');fail=[l.strip()for l in log.splitlines()if 'ASSERT FAIL:'in l];passed=len(re.findall(r'^  ok  ',log,re.M));assert 'FAILED —'in log and passed+len(fail)==3879
base=json.loads((R/'docs/qa/stage_1_5_0914.json').read_text(encoding='utf-8'))['suite']['failureNames'];norm=lambda s:re.sub(r'\d+(?:\.\d+)?','#',s);new=[x for x in fail if norm(x)not in{norm(x)for x in base}];assert not new
section=log[log.index('=== 307.'):log.index('============================================',log.index('=== 307.'))];assert len(re.findall(r'^  ok  ',section,re.M))==15
browser=json.loads((O/'results.json').read_text(encoding='utf-8'));assert len(browser['checks'])==25 and all(c['pass']for c in browser['checks'])and not browser['errors']and not browser['details']['loopError']
runtime=(R/'assets/game.js').read_bytes();tests=(R/'_BUILD_SOURCE/test_fl.js').read_bytes();assert runtime==(O/'game.expected.js').read_bytes()and b'\r\n'not in runtime;assert tests.count(b'\n')==tests.count(b'\r\n');sha=lambda x:hashlib.sha256(x).hexdigest()
report={'suite':{'passed':passed,'failed':len(fail),'exitCode':1,'finalSummaryReached':True,'section307Passed':15,'newFailingAssertionNames':new,'failureNames':fail,'baseline':'docs/qa/stage_1_5_0914.json'},'browser':browser,'runtime':{'sha256':sha(runtime),'testSha256':sha(tests),'LF':True,'testsCRLF':True,'syntaxCheckExitCode':0},'completed':['SPACE-15','MODE-06'],'settings':{'midpointLifeProbability':{'easy':.02,'normal':.02,'hard':.025,'furious':.025},'ordinaryDeathLifeProbability':{'easy':.01,'normal':.01,'hard':.0125,'furious':.0125},'ordinaryAmmoProbability':.062,'ordinaryShieldProbability':.028,'forcedPickups':'remain single grants; no extra roll','midpointPosition':'inside current camera with 40px margins','Decker':'SPACE FIGHTER DECKER fallback; actual model name pending'},'visualReview':'Nine native launch/reveal screenshots inspected; supplied eight names plus honest Decker fallback are visible and fit the canvas. Existing white reveal wash is unchanged. Native current Life Up art spawns inside camera and the HUD increments by one on collection. No art generated.','limitations':['New spaceship components/animation and replacement Life Up art remain pending.','Native probability checks inject boundary RNG values to prove routes; full population statistics are not inferred from a short gameplay sample.','Full suite remains nonzero with baseline failures.']}
(R/'docs/qa/easy_queue_0914.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8');print(passed,'passed /',len(fail),'failed, exit 1; native 25/0')
