const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/Mike/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const ROOT=__dirname, mkdir=d=>fs.mkdirSync(path.join(ROOT,d),{recursive:true});
const write=(file,value)=>fs.writeFileSync(path.join(ROOT,file),JSON.stringify(value,null,2)+'\n');
const M={version:1,date:'2026-10-07',tool:'built-in image_gen',status:'graphics_only_review_candidates',frames:{},sequences:{},tanks:{},sources:{},pilots:JSON.parse(fs.readFileSync(path.join(ROOT,'../ground/manifest.json'))).pilots,notes:['Machinists v2 is the selected grounded redesign. Original anime-influenced v1 is archived in source only.','No gameplay engine changes. Generated three-frame actions require temporal and socket review.']};
M.pilots.niel={body:'regular',color:'#d4eee3',lum:1,secondary:'#217b68',callsign:'Windstorm',ship:'Sirocco'};
M.pilots.wren={body:'heavy',color:'#d7d2bf',lum:1,secondary:'#b83b28',tank:'Foundry'};M.pilots.rolf={body:'regular',color:'#ae3c32',lum:1,secondary:'#e0d9bc',tank:'Vector'};M.pilots.chaz={body:'regular',color:'#dd8127',lum:1,secondary:'#1c344d',tank:'Redline'};
const Q={sourceAlpha:[],extractionWarnings:[],frameChecks:[],browserReview:null};
const transparent=(w,h)=>sharp({create:{width:w,height:h,channels:4,background:'#00000000'}});
function seq(id,frames,fps=6,loop=false,extra={}){M.sequences[id]={frames,fps,loop,...extra};}
async function exportFrame(id,buffer,folder,size,meta={}){mkdir(folder);let f=folder+'/'+id+'.png';await sharp(buffer).png().toFile(path.join(ROOT,f));M.frames[id]={file:f,size:[size,size],pivot:[size/2,size/2],...meta};return f;}
async function sheet(name,cols,rows,names,folder,scale,canvas,options={}){
 const file='source/'+name+'.png';const {data,info}=await sharp(path.join(ROOT,file)).ensureAlpha().raw().toBuffer({resolveWithObject:true}),w=info.width,h=info.height;
 const nearest=(x,y)=>Math.min(rows-1,Math.floor(y/h*rows))*cols+Math.min(cols-1,Math.floor(x/w*cols));
 const labels=new Int32Array(w*h).fill(-1),seen=new Uint8Array(w*h);let zeros=0;
 for(let p=0;p<w*h;p++){if(seen[p]||data[p*4+3]<16)continue;const list=[p];seen[p]=1;let sx=0,sy=0,x0=w,y0=h,x1=0,y1=0;
 for(let j=0;j<list.length;j++){const a=list[j],x=a%w,y=Math.floor(a/w);sx+=x;sy+=y;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);for(const b of [x?a-1:-1,x<w-1?a+1:-1,y?a-w:-1,y<h-1?a+w:-1])if(b>=0&&!seen[b]&&data[b*4+3]>=16){seen[b]=1;list.push(b);}}
 const joined=x1-x0>w/cols*1.7||y1-y0>h/rows*1.7;const index=nearest(sx/list.length,sy/list.length);if(joined&&list.length>500)Q.extractionWarnings.push({source:file,bounds:[x0,y0,x1,y1],reason:'joined alpha regions split at grid cell boundary'});for(const p of list)labels[p]=joined?nearest(p%w,Math.floor(p/w)):index;
 }
 const fringe=[];for(let p=0;p<w*h;p++)if(labels[p]>=0)fringe.push(p);for(let j=0;j<fringe.length;j++){const a=fringe[j],x=a%w,y=Math.floor(a/w);for(const b of [x?a-1:-1,x<w-1?a+1:-1,y?a-w:-1,y<h-1?a+w:-1])if(b>=0&&labels[b]<0&&data[b*4+3]){labels[b]=labels[a];fringe.push(b);}}
 const bounds=Array.from({length:cols*rows},()=>({x0:w,y0:h,x1:0,y1:0,count:0}));for(let p=0;p<w*h;p++){if(!data[p*4+3]){zeros++;continue;}if(labels[p]<0)labels[p]=nearest(p%w,Math.floor(p/w));const b=bounds[labels[p]],x=p%w,y=Math.floor(p/w);b.x0=Math.min(b.x0,x);b.y0=Math.min(b.y0,y);b.x1=Math.max(b.x1,x);b.y1=Math.max(b.y1,y);b.count++;}
 Q.sourceAlpha.push({file,size:[w,h],zeroAlphaPixels:zeros});M.sources[name]={file,size:[w,h],grid:[cols,rows]};mkdir('cuts');const atlas=[];
 for(let i=0;i<names.length;i++){const id=names[i],b=bounds[i];if(!b.count)throw Error('Empty cell '+id);let bx=w,by=h,ex=0,ey=0;const threshold=folder==='fx'?2:24;for(let y=b.y0;y<=b.y1;y++)for(let x=b.x0;x<=b.x1;x++){const p=y*w+x;if(labels[p]===i&&data[p*4+3]>=threshold){bx=Math.min(bx,x);by=Math.min(by,y);ex=Math.max(ex,x);ey=Math.max(ey,y);}}if(bx<w){b.x0=Math.max(b.x0,bx-3);b.y0=Math.max(b.y0,by-3);b.x1=Math.min(b.x1,ex+3);b.y1=Math.min(b.y1,ey+3);}const cw=b.x1-b.x0+1,ch=b.y1-b.y0+1,cut=Buffer.alloc(cw*ch*4);for(let y=b.y0;y<=b.y1;y++)for(let x=b.x0;x<=b.x1;x++){const p=y*w+x;if(labels[p]===i)data.copy(cut,((y-b.y0)*cw+x-b.x0)*4,p*4,p*4+4);}const raw=await sharp(cut,{raw:{width:cw,height:ch,channels:4}}).png().toBuffer();fs.writeFileSync(path.join(ROOT,'cuts/'+id+'.png'),raw);
 let s=Math.min(scale,(canvas-8)/cw,(canvas-8)/ch),nw=Math.max(1,Math.round(cw*s)),nh=Math.max(1,Math.round(ch*s));const small=await sharp(raw).resize(nw,nh,{kernel:'nearest'}).png().toBuffer();let left=Math.floor((canvas-nw)/2),top=Math.floor((canvas-nh)/2);const anchor=options.rowAnchors?.[Math.floor(i/cols)]||(options.cellAnchored?[w/cols/2,h/rows/2]:null);const target=options.targetAnchor||[48,66];if(anchor){left=Math.round(target[0]+(b.x0-(i%cols)*w/cols-anchor[0])*s);top=Math.round(target[1]+(b.y0-Math.floor(i/cols)*h/rows-anchor[1])*s);}if(left<0||top<0||left+nw>canvas||top+nh>canvas)throw Error('Anchor clips '+id);const rendered=await transparent(canvas,canvas).composite([{input:small,left,top}]).png().toBuffer();await exportFrame(id,rendered,folder,canvas,{source:file,sourceRect:[b.x0,b.y0,cw,ch],sourceScale:s,reviewPivot:true,...(anchor?{pivot:target,sourceCellAnchor:anchor}: {})});atlas.push({input:rendered,left:i%cols*canvas,top:Math.floor(i/cols)*canvas});
 }
 mkdir('atlases');await transparent(cols*canvas,rows*canvas).composite(atlas).png().toFile(path.join(ROOT,'atlases/'+name+'.png'));
}
async function identity(name,items){const file='source/'+name+'.png';for(const [id,r,size] of items){const img=await sharp(path.join(ROOT,file)).extract({left:r[0],top:r[1],width:r[2],height:r[3]}).resize(size,size,{fit:'contain',kernel:'nearest',background:'#00000000'}).png().toBuffer();await exportFrame(id,img,'identity',size,{source:file,sourceRect:r});}}
async function assembleTank(who,hullWidth){
 const id='tank_'+who,size=256,pivot=[128,151],hullPath='cuts/'+id+'_hull.png';const hmeta=await sharp(path.join(ROOT,hullPath)).metadata(),scale=hullWidth/hmeta.width,hh=Math.round(hmeta.height*scale),parts={};
 for(const part of ['hull','damaged_hull','left_track','right_track','turret','special_module']){const cut=path.join(ROOT,'cuts/'+id+'_'+part+'.png'),md=await sharp(cut).metadata();let s=scale,tw,th,left,top;if(part==='left_track'||part==='right_track'){s=hh/md.height;}if(part==='special_module')s=26/Math.max(md.width,md.height);tw=Math.max(1,Math.round(md.width*s));th=Math.max(1,Math.round(md.height*s));left=Math.round(pivot[0]-tw/2);top=Math.round(pivot[1]-th/2);
 if(part==='left_track')left=Math.round(pivot[0]-hullWidth/2-tw+10);if(part==='right_track')left=Math.round(pivot[0]+hullWidth/2-10);if(part==='turret')top=Math.round(pivot[1]-th*.76);if(part==='special_module')top=Math.round(pivot[1]+hh/2-th*.7);
 const input=await sharp(cut).resize(tw,th,{kernel:'nearest'}).png().toBuffer(),layer=await transparent(size,size).composite([{input,left,top}]).png().toBuffer();const fid=id+'_'+part+'_layer';await exportFrame(fid,layer,'tanks/layers',size,{pivot,part,scale:s,source:M.frames[id+'_'+part].source,sourceRect:M.frames[id+'_'+part].sourceRect});parts[part]={frame:fid,placement:[left,top,tw,th]};
 }
 const layerOrder=['left_track','right_track','hull','special_module','turret'];for(const state of ['assembled','damaged']){const layers=layerOrder.map(p=>({input:path.join(ROOT,M.frames[parts[state==='damaged'&&p==='hull'?'damaged_hull':p].frame].file),left:0,top:0}));const output=await transparent(size,size).composite(layers).png().toBuffer();await exportFrame(id+'_'+state,output,'tanks',size,{pivot,assembledFrom:layerOrder.map(p=>parts[p].frame)});}
 const tp=parts.turret.placement;M.tanks[who]={name:{wren:'Foundry',rolf:'Vector',chaz:'Redline'}[who],pivot,canvas:[size,size],parts,layerOrder,assembled:id+'_assembled',damaged:id+'_damaged',turretHeading:'north',muzzle:[128,tp[1]+4],socketStatus:'visually calibrated assembly; gameplay collision not authored',special:{wren:'Bastion',rolf:'Vector Splitter',chaz:'Redline Breach'}[who]};
}
(async()=>{
 for(const d of ['identity','previews','tanks','allies','players','fx','props','ui','ship'])mkdir(d);
 await identity('niel_identity',[['niel_portrait',[39,40,496,493],320],['niel_full_body',[638,0,357,627],512],['niel_front',[1118,0,321,627],512],['niel_smile',[105,629,365,375],256],['niel_combat',[616,629,369,375],256],['niel_avatar',[1159,695,246,250],128]]);
 await identity('machinists_identity_v2',[['wren_portrait',[118,8,371,406],320],['rolf_portrait',[583,8,371,406],320],['chaz_portrait',[1048,8,371,406],320],['wren_front',[127,416,352,607],512],['rolf_front',[585,416,357,607],512],['chaz_front',[1066,416,350,607],512]]);
 await sheet('niel_ship_ui',3,2,['niel_ship_idle','niel_ship_bank_left','niel_ship_bank_right','niel_ship_damaged','windstorm_icon','windstorm_box'],'ship',.28,192);
 const windNames=['tornado','volley','impact','charge'].flatMap(a=>Array.from({length:6},(_,i)=>'windstorm_'+a+'_'+i));await sheet('windstorm_fx',6,4,windNames,'fx',.48,160);for(const a of ['tornado','volley','impact','charge'])seq('windstorm_'+a,Array.from({length:6},(_,i)=>'windstorm_'+a+'_'+i),a==='tornado'||a==='volley'?9:12,['tornado','volley'].includes(a),{anchorCleanupNeeded:true});
 for(const who of ['wren','rolf','chaz']){await sheet('tank_'+who,4,2,['concept','hull','turret','left_track','right_track','damaged_hull','wreck','special_module'].map(p=>'tank_'+who+'_'+p),'tanks',.27,192);await assembleTank(who,{wren:100,rolf:89,chaz:81}[who]);}
 const allyActions=['run_east','run_north_draft','run_south','wall_tap','door','cover_lean','crawl','aim_fire','heal','signal'];
 for(const who of ['phoenix','hotwire']){const statics=['idle_north_draft','idle_east','idle_south','idle_west','crouch_east','prone_east'].map(a=>who+'_'+a);const names=[...statics,...allyActions.flatMap(a=>Array.from({length:3},(_,i)=>who+'_'+a+'_'+i))];await sheet('ally_'+who,6,6,names,'allies',.20,96);for(const a of allyActions)seq(who+'_'+a,Array.from({length:3},(_,i)=>who+'_'+a+'_'+i),7,['run_east','run_north_draft','run_south','crawl'].includes(a),{family:'ally',direction:a.includes('north')?'north':a.includes('south')?'south':'east',state:a.includes('draft')?'superseded_direction_candidate':'motion_candidate'});}
 await sheet('ally_north_correction',4,2,['phoenix','hotwire'].flatMap(w=>[w+'_idle_north',...Array.from({length:3},(_,i)=>w+'_run_north_'+i)]),'allies',.115,96);for(const w of ['phoenix','hotwire'])seq(w+'_run_north',Array.from({length:3},(_,i)=>w+'_run_north_'+i),7,true,{family:'ally',direction:'north',replaces:w+'_run_north_draft'});
 const interactions=['wall_tap_east','wall_tap_north','door_east','door_north','wall_lean','crate_peek','heal','noise_toss'];for(const body of ['regular','heavy','athletic','female']){const names=interactions.flatMap(a=>Array.from({length:3},(_,i)=>body+'_'+a+'_'+i));await sheet('interactions_'+body,6,4,names,'players',.19,96);for(const a of interactions)seq(body+'_'+a,Array.from({length:3},(_,i)=>body+'_'+a+'_'+i),6,false,{family:'player_interaction',body,direction:a.endsWith('north')?'north':'east'});}
 const tankFx=[];for(const who of ['wren','rolf','chaz'])tankFx.push(who+'_projectile',...Array.from({length:3},(_,i)=>who+'_muzzle_'+i),who+'_impact_0',who+'_impact_1',...Array.from({length:6},(_,i)=>who+'_special_'+i));await sheet('machinists_fx',6,6,tankFx,'fx',.5,160);for(const who of ['wren','rolf','chaz']){seq(who+'_muzzle',[0,1,2].map(i=>who+'_muzzle_'+i),14);seq(who+'_impact',[0,1].map(i=>who+'_impact_'+i),10);seq(who+'_special',[0,1,2,3,4,5].map(i=>who+'_special_'+i),10);}
 const props=['door_locked','door_unlocked','door_ajar','door_open','tap_spark','sound_ring_0','sound_ring_1','sound_ring_2','medkit_pickup','medkit_open','heal_pulse_0','heal_pulse_1','machinists_badge','wren_special_icon','rolf_special_icon','chaz_special_icon'];await sheet('stealth_props',4,4,props,'props',.4,160);seq('door_opening',['door_unlocked','door_ajar','door_open'],6);seq('sound_ping',['sound_ring_0','sound_ring_1','sound_ring_2'],9);seq('heal_pulse',['heal_pulse_0','heal_pulse_1'],5);
 const completionActions=[['grenade_throw',6],['roll_to_prone',6],['roll_to_stand',6],['hit',3],['stun',3],['death',6],['revive',6],['powerup',3],['assist_heal',3],['duck_to_prone',3],['recovery',3]];
 for(const who of ['phoenix','hotwire']){const names=completionActions.flatMap(([a,n])=>Array.from({length:n},(_,i)=>who+'_'+a+'_'+i));await sheet('ally_'+who+'_completion',6,8,names,'allies',.225,96);for(const [a,n] of completionActions)seq(who+'_'+a,Array.from({length:n},(_,i)=>who+'_'+a+'_'+i),a.startsWith('roll')?10:7,a==='stun',{family:'ally',direction:'east',state:'motion_candidate',rootMotionAuthored:false});}
 // The generated Hotwire third row is a get-up. Use the actual shoulder-roll row before its standing exit.
 M.sequences.hotwire_roll_to_stand.frames=[0,1,2,3].map(i=>'hotwire_roll_to_prone_'+i).concat(['hotwire_roll_to_stand_4','hotwire_roll_to_stand_5']);M.sequences.hotwire_roll_to_stand.reviewNote='Curated roll entry plus standing exit; source third row is primarily recovery.';
 M.sequences.phoenix_duck_to_prone.frames=['phoenix_duck_to_prone_0','phoenix_duck_to_prone_1','phoenix_recovery_0'];M.sequences.phoenix_duck_to_prone.reviewNote='Uses fully prone pose from following source cell for final state.';
 const fireRows=['phoenix_aim_fire_north','phoenix_aim_fire_south','hotwire_aim_fire_north','hotwire_aim_fire_south'];await sheet('ally_directional_fire',6,4,fireRows.flatMap(a=>Array.from({length:6},(_,i)=>a+'_'+i)),'allies',.185,96,{rowAnchors:[[128,240],[128,190],[128,240],[128,190]]});for(const a of fireRows)seq(a,Array.from({length:6},(_,i)=>a+'_'+i),10,true,{family:'ally',direction:a.endsWith('north')?'north':'south',events:[{frame:1,type:'fire'},{frame:3,type:'fire'}],state:'motion_candidate',rootMotionAuthored:false});
 for(const who of ['wren','rolf','chaz']){const names=['left','right'].flatMap(side=>Array.from({length:6},(_,i)=>'tank_'+who+'_'+side+'_track_move_'+i));await sheet('tank_'+who+'_tracks',6,2,names,'tanks',.27,192);M.tanks[who].trackSequences={};for(const side of ['left','right']){const part=side+'_track',placement=M.tanks[who].parts[part].placement,[left,top,width,height]=placement,ids=[];for(let i=0;i<6;i++){const original='tank_'+who+'_'+side+'_track_move_'+i,id=original+'_layer';const input=await sharp(path.join(ROOT,'cuts/'+original+'.png')).resize(width,height,{fit:'fill',kernel:'nearest'}).png().toBuffer();const rendered=await transparent(256,256).composite([{input,left,top}]).png().toBuffer();await exportFrame(id,rendered,'tanks/layers',256,{pivot:[128,151],source:M.frames[original].source,sourceRect:M.frames[original].sourceRect,part,placement,reviewPivot:true});ids.push(id);}const id='tank_'+who+'_'+side+'_drive';seq(id,ids,10,true,{family:'tank_track',direction:'north',state:'motion_candidate',distanceDrivenPlayback:true});M.tanks[who].trackSequences[side]=id;}M.tanks[who].trackMotionStatus='Six generated phases per independent track; housing drift and wrap require pixel cleanup before runtime registration.';}
 M.reuse={locomotion:'../ground/manifest.json',priorActions:'../onfoot/manifest.json',oldPreview:'../onfoot/preview.html',notes:'Previous crouch/prone/roll/grenade/death/revive/FOV graphics remain available. New interactions supplement those four shared families. Do not load superseded ally north draft sequences.'};
 await require('./build-ui-style-match.cjs')(M,Q);
 await require('./build-pass2.cjs')({M,Q,sheet,seq,exportFrame});
 if(fs.existsSync(path.join(ROOT,'source/machinists_identity_v4.png')))await require('./build-roster-v4.cjs')(M,Q);
 for(const [id,f] of Object.entries(M.frames)){const {data,info}=await sharp(path.join(ROOT,f.file)).ensureAlpha().raw().toBuffer({resolveWithObject:true});let alpha=0,border=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const a=data[(y*info.width+x)*4+3];if(a)alpha++;if(a&&(x===0||y===0||x===info.width-1||y===info.height-1))border++;}f.sha256=crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f.file))).digest('hex').slice(0,16);if(!alpha)throw Error('Empty export '+id);Q.frameChecks.push({id,nonzeroAlphaPixels:alpha,borderAlphaPixels:border,size:[info.width,info.height]});}
 Q.totals={frames:Object.keys(M.frames).length,sequences:Object.keys(M.sequences).length,sourceMasters:fs.readdirSync(path.join(ROOT,'source')).length};Q.missingReferences=[];for(const [id,s] of Object.entries(M.sequences))for(const f of s.frames)if(!M.frames[f])Q.missingReferences.push(id+':'+f);write('manifest.json',M);fs.writeFileSync(path.join(ROOT,'manifest.js'),'window.EXPANSION='+JSON.stringify(M)+';\n');write('verification.json',Q);console.log(JSON.stringify({totals:Q.totals,warnings:Q.extractionWarnings,missing:Q.missingReferences},null,2));
})();
